### ISSUE TITLE
Beginners Qst: Why do you use Neo4j?

### ISSUE THREAD

**Issue by shakesBeardZ** [thedevs-network/kutt#101]
I'm wondering why you guys are using Neo4j database here instead of using a normal no sql database or sql database

**Comment by trgwii** [comment]
Because graph databases makes insight-type queries cheaper and simpler than other alternatives.

Queries like "How many users have visited these links in the last 24h from Norway" are VERY expensive in Mongo / SQL databases, but very cheap in graph databases.
