### ISSUE TITLE
statistics configuration

### ISSUE THREAD

**Issue by josemgala** [thedevs-network/kutt#105]
Hello!
Is it possible to customize the colors of the graphics?
And on the other hand, is it possible to obtain other types of statistics?

regards

**Comment by trgwii** [comment]
> Is it possible to customize the colors of the graphics?

No, not without code changes.

> is it possible to obtain other types of statistics?

Yes, the easiest way (if you're hosting your own instance) is to install [Neo4j Desktop](https://neo4j.com/download/) and take a look at the data. This will show you everything Kutt stores.

**Comment by poeti8** [comment]
> Is it possible to customize the colors of the graphics?

No option in the app. 
If you're hosting the app yourself, you can change the colors directly in the code.
Each file in the Stats folder might contain color values (e.g. fill, stroke, etc.). 
https://github.com/thedevs-network/kutt/tree/develop/client/components/Stats/StatsCharts

> obtain other types of statistics

These are the only data we store if you want you can change the code in the server and add stuff. Then create a proper view for them in the front-end.
