### ISSUE TITLE
Gateway time-out (504) for short URLs

### ISSUE THREAD

**Issue by stefanes** [thedevs-network/kutt#109]
Site appears up and running, but 504 returned for short URLs.

Also, unable to login. Seems to time out with no message returned.

**Comment by poeti8** [comment]
Seems like it was a temporary database overload. I'm gonna keep this issue open until I find a way to handle that and also increase CPU cores and RAM for the database host.

**Comment by danielmorganessex** [comment]
still getting same problem

**Comment by danielmorganessex** [comment]
Gateway time-out (504) for short URLs 

has been happening for couple of days

**Comment by joaoramos** [comment]
And again, down already for a few hours.

**Comment by poeti8** [comment]
@joaoramos It wasn't down that time as I was working with it, what were you seeing? Which page?

**Comment by joaoramos** [comment]
Here's what I just learned:
- URL using the default domain work well
- URL using a custom domain throw a 504

Here's the `uptimerobot.com` report for one of my custom domain URL http://go.joao.pt/twitter, which had 50% downtime over the last few days. Does this help?

<img width="823" alt="Screenshot 2020-01-31 at 09 17 20" src="https://user-images.githubusercontent.com/1187347/73523241-b24d6600-440a-11ea-8dec-22e28f42bb84.png">

**Comment by poeti8** [comment]
Is your domain pointing to the correct IP address (the one in settings page)?

**Comment by joaoramos** [comment]
Yeah, the A record is pointed at the right IP address.

**Comment by poeti8** [comment]
@joaoramos  Sorry you are right the code I pushed yesterday had a small bug. Please try it's been fixed.

P.S. I have added https://kutt.it/api/v2/health for general health check.

**Comment by joaoramos** [comment]
Thanks, @poeti8. It's working perfectly now!
