### ISSUE TITLE
Your site got blocked by Swisscom

### ISSUE THREAD

**Issue by Eragonder** [thedevs-network/kutt#113]
![2018-11-06_15-05](https://user-images.githubusercontent.com/24879428/48069353-8c202280-e1d5-11e8-9145-d923c884655b.png)

The important links from the warning page:

Notify a false warning:
https://www.swisscom.ch/en/residential/help/internet/internetguard/formular.html?campID=BI_GUARD_LINK_FALSEWARNING#url=http%3A%2F%2Fkutt.it%2F

More about security:
https://www.swisscom.ch/en/residential/security.html

**Comment by poeti8** [comment]
Homepage? Anywhere to submit report for them?

**Comment by Eragonder** [comment]
@poeti8 No. I'm not sure what issued the block. If it's something that need a fix from your site a complaint made from you would make more sense

**Comment by poeti8** [comment]
Thank you. Submitted.

**Comment by Eragonder** [comment]
@poeti8 If you hear something from swisscom can you tell me what caused the report?

**Comment by poeti8** [comment]
Well, I already know why. Some people submit phishing websites to Kutt and they got reported to our host provider or even in this case, internet providers. I delete and ban links immediately after report but it seems like it's not enough.

**Comment by Eragonder** [comment]
> Well, I already know why. Some people submit phishing websites to Kutt and they got reported to our host provider or even in this case, internet providers. I delete and ban links immediately after report but it seems like it's not enough.

@poeti8 I will ask someone from Swisscom what you can do to prevent that. Thanks

**Comment by poeti8** [comment]
@Eragonder Do you still have the issue?

**Comment by Eragonder** [comment]
It's working fine now. Thx
