### ISSUE TITLE
Verificate old users

### ISSUE THREAD

**Issue by omergulen** [thedevs-network/kutt#118]
Since we have verification anymore, old un-verified users needed to be verified.

In the login page, there is an error message if you are not verified by email while logging in.
But there no re-send button or etc. 

UI/UX should be better. Also, it should give information about the verification process that "you are an old user which is not verified, but since we have a mandatory verification rule, you need to be verified by email. Please click the button to send verification to your email." etc.

**Comment by caltlgin** [comment]
Yes, this affects me. I cant login. All I get is a message saying `Your email address is not verified`. Trying to reset my password doesn't work either.

**Comment by poeti8** [comment]
Use sign up to get the verification email. I'll add another form soon.

**Comment by caltlgin** [comment]
Awesome. Thanks @poeti8, that worked.
