### ISSUE TITLE
Add new 3rd Party API packages to README

### ISSUE THREAD

**Issue by caltlgin** [thedevs-network/kutt#119]
I have created a bash script which allows simple access to the Kutt.it API.

Rather than create a fork and then a PR to the README. I was wondering if @poeti8 could add a link to my kutt-bash script to the 3rd Party API packages in the [README](https://github.com/thedevs-network/kutt#user-content-3rd-party-api-packages)

Here is the GitHub repository for the bash script. https://github.com/caltlgin/kutt-bash

With the testing I have done, the script is working as expected. Although there is always room for improvement. :smiley:

**Comment by poeti8** [comment]
Thank you. Added.
