### ISSUE TITLE
Question about Neo4j 

### ISSUE THREAD

**Issue by thiamsantos** [thedevs-network/kutt#12]
First, congratulations for the awesome project! But I would like to know a few things recarding the chosen stack of the project.

Why do you chose Neo4j as the main database? Why not some other relational or key-value database? What you took into account to make that choice? Why a graph database is the best fit for a url shortener?

**Comment by trgwii** [comment]
This has been answered on Reddit:

https://www.reddit.com/r/web_design/comments/7xg6rc/comment/du87zev

**Comment by thiamsantos** [comment]
Thanks for the quick answer! You rock :fist_oncoming:
