### ISSUE TITLE
Verification emails stopped replacing {{verification}}

### ISSUE THREAD

**Issue by wiglesworthj** [thedevs-network/kutt#121]
I had a fully working version of kutt, but I needed to configure SSL. I decided to use nginx as reverse proxy and SSL. All went well. But now I have this seemingly unrelated issue:

Verification email links no longer have verification codes. All links appear as: http://mydomain.com/verify/%7B%7Bverification%7D%7D

All other aspects of the app continue to work. Any help is much appreciated!!

**Comment by wiglesworthj** [comment]
when I console.log the newuser verification string before replacing, it logs the string that should be there.

**Comment by wiglesworthj** [comment]
Alright, so somehow installing nginx broke string replacing in authController.js on lines 117-118: 

    text: verifyMailText.replace('{{verification}}', newUser.verificationToken),
    html: verifyEmailTemplate.replace('{{verification}}', newUser.verificationToken),

all other string replacing in this file works because it uses regex pattern matching (e.g., /{{domain}}/gm). I was able to fix by changing line 117 and 118 to replace by regex instead of string...I'm still not sure how installing nginx broke this. But at least there's a fix. If anyone sees this and has any insight it would be much appreciated. I'm sure i just messed up a configuration in nginx.

**Comment by poeti8** [comment]
Not sure how NGINX could mess this up. Is `newUser.verificationToken` undefined? Is your code up to date with this repo?

**Comment by wiglesworthj** [comment]
> Not sure how NGINX could mess this up. Is `newUser.verificationToken` undefined? Is your code up to date with this repo?

As I stated in my previous comment, console.log(newUser.verificationToken) right before the email sent, showed the verification token that should've been placed into the email. The problem is that somehow .replace method quit working with strings, it only works now with regex pattern matching.

**Comment by abhijithvijayan** [comment]
Verification fails 

Inbox link for verification. 

![2019-02-10_12-26-37](https://user-images.githubusercontent.com/34790378/52530699-2771e800-2d2f-11e9-9926-f518dcdff862.png)
