### ISSUE TITLE
Do we need to change the URL?

### ISSUE THREAD

**Issue by RakeshDL** [thedevs-network/kutt#124]
Hello there!
I've hosted this repo in a Google cloud VM instance and did exactly as you mentioned in the documentation, and when i started as production its showing 

> user@1.2.0 start /home/dev/user
> NODE_ENV=production node ./server/server.js
> Ready on http://localhost:3000

can we access the site through my custom URL? (which is tunl.in)
do we need to change the URL anywhere else except config files?

you can check the screenshot below

![image](https://user-images.githubusercontent.com/19234546/50314635-98d2ae80-04d5-11e9-9bf2-9dfd5ea13e68.png)
![image](https://user-images.githubusercontent.com/19234546/50315335-65ddea00-04d8-11e9-942d-d10be67307be.png)

**Comment by RakeshDL** [comment]
It's fixed, I changed the port from 3000 to 80 and it worked!
first of all, DNS took overnight to resolve then tried with port 80
Thanks

**Comment by RakeshDL** [comment]
It's fixed, I changed the port from 3000 to 80 and it worked!
first of all, DNS took overnight to resolve then tried with port 80
Thanks

**Comment by abhijithvijayan** [comment]
> It's fixed, I changed the port from 3000 to 80 and it worked!
> first of all, DNS took overnight to resolve then tried with port 80
> Thanks

what's your webserver config?
