### ISSUE TITLE
[Feature] Make LibreJS Compliant

### ISSUE THREAD

**Issue by asddsaz** [thedevs-network/kutt#128]
**Description**: Make Kutt.it [LibreJS](https://www.wikipedia.org/wiki/LibreJS) compatible.
I've been messing around with this extension, LibreJS. Seeing which sites are labeled as FLOSS. Kutt.it seems to have mistakenly been labeled non-free.
Here is the documentation to change this: https://www.gnu.org/software/librejs/free-your-javascript.html

**Comment by poeti8** [comment]
I have no control over packages I use and I don't think I can change that.
