### ISSUE TITLE
Not Running on the domain

### ISSUE THREAD

**Issue by abhijithvijayan** [thedevs-network/kutt#129]
![](http://bit.ly/2FdpzKq)

**Comment by abhijithvijayan** [comment]
I'm on nginx web server, so configuration needs any special configs?

**Comment by poeti8** [comment]
First visit `<ip>:3000` to make sure app is up. You need to proxy domain to `localhost:<port>` in nginx. So domain resolves to `localhost:<port>`.

**Comment by abhijithvijayan** [comment]
@poeti8 
Got it working but throwing errors

![](https://i.imgur.com/8bo6QTQ.png)

**Comment by abhijithvijayan** [comment]
Have to install nodemailer I guess

**Comment by poeti8** [comment]
@abhijithvijayan Not sure about POSTFIX. You can check [ethereal.email](https://ethereal.email/) for temporary email tests.

**Comment by abhijithvijayan** [comment]
> @abhijithvijayan Not sure about POSTFIX. You can check [ethereal.email](https://ethereal.email/) for temporary email tests.

Just the credentials are enough? And BTW had some trouble with neo4j setup.
Should add something about the firewall ports in readme as I barely thought about it while setting up. Uses ufw btw.

**Comment by poeti8** [comment]
Yes only credentials. 
Explaining how to install Neo4j or Node.js is out of this repo's topic and I can't cover every case. they have docs for that purpose. Although I can share they way I'm using them, that would be helpful.

**Comment by abhijithvijayan** [comment]
[Fixed]
