### ISSUE TITLE
kutt.it down? 

### ISSUE THREAD

**Issue by stefanes** [thedevs-network/kutt#130]
Unable to login or use any of my short URLs.

**Comment by trgwii** [comment]
Works for me :shrug:

**Comment by abhijithvijayan** [comment]
@poeti8 I notice it often when I try with extension. Do you mind upgrading to the latest release in the stores as this one is the latest stable release with time out feature. Kutt.it as of now is down.

**Comment by poeti8** [comment]
@abhijithvijayan of course, that's what I'm preparing for the next version. Also have been having some database operations these days to improve the speed and the stability of the database, I think they might be the reason for this. Hopefully we can finish them this week.

**Comment by poeti8** [comment]
#140 Should resolve this issue.
