### ISSUE TITLE
Feature request: word based URLs

### ISSUE THREAD

**Issue by DonaldTsang** [thedevs-network/kutt#138]
Something similar to https://noun.ly except it can use any wordlist, and it can be a chain of N words from the list of M words.
The wordlists can be from [Bitcoin BIP39](https://github.com/bitcoin/bips/blob/master/bip-0039/bip-0039-wordlists.md), [Diceware tables](https://github.com/grempe/diceware) or [https://en.wikipedia.org/wiki/PGP_word_list](https://en.wikipedia.org/wiki/PGP_word_list)

**Comment by DonaldTsang** [comment]
Niceware can be used to generate these URLs

**Comment by poeti8** [comment]
I don't see how is this useful?

**Comment by DonaldTsang** [comment]
@poeti8 memorability would be useful, have you ever heard of `correct horse battery staple` or other mnemonic-based password generators? Having a memorable URL would be great.
Exmaple 1: https://xkcd.com/936/
Example 2: http://worrydream.com/tripphrase/

**Comment by poeti8** [comment]
But it would unnecessary take meaningful names where users can use them to shorten links that are actually related to that word. For example kutt.it/Apollo should redirect to a link that is related to Apollo.

**Comment by DonaldTsang** [comment]
@poeti8 It would be great if a URL shortening service that delegates random URLs did it in a way that is memorable instead of badly designed, especially ones that uses both uppercase and lower case. The chosen random words should be those that are understood to be part of "basic English".

**Comment by trgwii** [comment]
For me it's much easier to remember a 6-character random string than a 4-word mnemonic device

**Comment by DonaldTsang** [comment]
@trgwii depends from person to person, but XKCD's "correct horse battery staple" is a classic with larger set of entropy, since one word has an entropy of 10~12 bits, every word would be equal to 1.5~2 base64 characters

**Comment by trgwii** [comment]
And larger entropy is worse for a url SHORTENER

**Comment by DonaldTsang** [comment]
@trgwii ease of memorability is a good price for character count, but remembering a single word is worth 2 base64 characters (with uppercase AND lowercase). If a URL requires 8 base64 characters that is only 4 words. With base32, the gain is even more as 2 words would be 5 base32 characters.

**Comment by trgwii** [comment]
We use a much higher base tho, so the gain is much lower

**Comment by DonaldTsang** [comment]
@trgwii have you actually seen how https://noun.ly works?

**Comment by trgwii** [comment]
Yep

**Comment by DonaldTsang** [comment]
@trgwii how so, if it has been demonstrated to be useful for with passwords, BIP39 and what3words?
If you use a much higher base then upper case and lower case, confusion would occur.
If you use only lower case then the amount of entropy is lower, such that using words would be a good tradeoff for increasing memorability.

Also @poeti8 what do think about this idea, and the conversation surrounding it? The Apollo idea is useful, but it can be generalized to apply to many other websites that does not need a specific name.
