### ISSUE TITLE
Admin account

### ISSUE THREAD

**Issue by sitemapxml** [thedevs-network/kutt#144]
Hi, 
I wonder how can I login to admin account? So I can manage spam links and ban users if needed.

**Comment by poeti8** [comment]
Enter your email in the server config file: `ADMIN_EMAILS: ['admin@example.com']`. Then you can see the form in the setting page.

**Comment by 8sd** [comment]
I add the mail I want to use as admin in the `.env`-file: `ADMIN_EMAILS=['info@....de']`.

Afterward, I created the account with the mail address. 

When I log in, there is no `admin`-form on the settings page.

I'm not sure if I set the variable correctly in the `.env`-file. Can I check this somehow?

**Comment by poeti8** [comment]
It's not an array, separate them by comma: `ADMIN_EMAILS=one@example.com,two@example.com`

**Comment by 8sd** [comment]
Okay, I did so. There is still no `admin`-form shown...

**Comment by poeti8** [comment]
There's no admin form. You can see a checkbox in table to search all links and and extra actions to ban and delete listed links.

**Comment by 8sd** [comment]
The image shows all of my settings-page.

![image](https://user-images.githubusercontent.com/32878822/89784367-d48e1200-db18-11ea-9b04-6a994c00daa9.png)

**Comment by 8sd** [comment]
Ahh, the table is on the home page...
