### ISSUE TITLE
utm parameters

### ISSUE THREAD

**Issue by kuttim** [thedevs-network/kutt#145]
Any plans for adding utm parameters to the url automatically?
e.g 
kutt.it/GfV6tz would become kutt.it/GfV6tz?utm_source=twitter&utm_medium=feed for example.

**Comment by nsomaru** [comment]
What's the need for this? Wouldn't you want to track utm parameters on the final desitination and shorten them in the url?

**Comment by williangd** [comment]
It would be interesting if there was an option to preserve the query parameters in the link.
Ex:  kutt.it/GfV6tz?utm_source=twitter redirects to https://example.com?utm_source=twitter

**Comment by Grienauer** [comment]
why was this issue closed without any notice?
I read the main request as following:
As a user, I want to have on all urls I add to the system automatically a UTM Parameter.
The original login parameter should have the UTM Parameter automatically added.
With that, one could track users better and see from where the users are coming.

this would need a setting in the backend or as a config, for the whole system.
