### ISSUE TITLE
[Suggestion on extension]

### ISSUE THREAD

**Issue by Relentlessy** [thedevs-network/kutt#147]
1. When the link of long-website-name was created, show the link one and make a choice to "create new link" and "replace with new link (delete and generate the new one)"

2. Have an option, click the extension icon auto-generate and auto-copy link into clipboard

**Comment by poeti8** [comment]
Please create issues on extension's own repository:
https://github.com/abhijithvijayan/kutt-extension/issues

The auto-copy feature is already done and I'm publishing the new version.

**Comment by abhijithvijayan** [comment]
> 1. When the link of long-website-name was created, show the link one and make a choice to "create new link" and "replace with new link (delete and generate the new one)"
> 2. Have an option, click the extension icon auto-generate and auto-copy link into clipboard

@Relentlessy Please transfer this issue to https://github.com/abhijithvijayan/kutt-extension/issues

I will look on to it.
