### ISSUE TITLE
How to pass real user ip when using cloudlfare?

### ISSUE THREAD

**Issue by xianx** [thedevs-network/kutt#151]
Hello,

my kutt installation is behind nginx proxy and set the following header in nginx

    proxy_set_header  Host $host;
    proxy_set_header  X-Real-IP $remote_addr;
    proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header  X-Forwarded-Proto $scheme;

but now i am using cloudflare in front of nginx.

So now how to get real visitor ip on kutt when behind cloudflare? For cloudflare my country stat are showing wrong I think.

**Comment by poeti8** [comment]
It should be fine, I'm also using Cloudflare and I didn't encounter any problems.

**Comment by xianx** [comment]
but stat collecting data of proxy not real user.

**Comment by yumusb** [comment]
> Hello,
> 
> my kutt installation is behind nginx proxy and set the following header in nginx
> 
> ```
> proxy_set_header  Host $host;
> proxy_set_header  X-Real-IP $remote_addr;
> proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
> proxy_set_header  X-Forwarded-Proto $scheme;
> ```
> 
> but now i am using cloudflare in front of nginx.
> 
> So now how to get real visitor ip on kutt when behind cloudflare? For cloudflare my country stat are showing wrong I think.

proxy_set_header  X-Real-IP  $remote_addr;

this is the key header. you should keep x-real-ip is real.
