### ISSUE TITLE
Where can I find a really working setup step by step ?

### ISSUE THREAD

**Issue by danysz** [thedevs-network/kutt#153]
Hi

I am hosting the platform on a VPS with CentOS
I added all the relevant data in the config.
I started the app with nom start and I started to get errors:

1. (node:5815) UnhandledPromiseRejectionWarning: Neo4jError: The client is unauthorized due to authentication failure. - I didn't add any authentication to the neo4j

2. I don't understand how to start the client

3. what is the proper way to put everything ?

Thanks a lot

Daniel

**Comment by xianx** [comment]
We prodive kutt installation on our hosted platform on your own domain with clustering support. If you are interested please ping me  on Discord Xian#9468

**Comment by poeti8** [comment]
Hey @danysz, currently we don't have tutorial on how to install Node.js or Neo4j, because they are out of the scope of this repository. If you have them installed and filled the configs files correctly, then you should be fine.
If enough people request, I may create a video tutorial on how to deploy Kutt on a VPS.

**Comment by XiRealizeX** [comment]
> Hey @danysz, currently we don't have tutorial on how to install Node.js or Neo4j, because they are out of the scope of this repository. If you have them installed and filled the configs files correctly, then you should be fine.
> If enough people request, I may create a video tutorial on how to deploy Kutt on a VPS.

Definitely needed. I don't have a clue on what to do. I give up.

**Comment by Peppuz** [comment]
Hey guys! I'm stuck here too. 
I've read that i have to change default credentials for neo4j and it should work, is it true? 
`systemctl status neo4j` tells me the service is active and running. But when I go `neo4j status` says Neo4j is not running. Idk who to believe.

So my problem as @danysz explained is the authentication error of Neo4J. 
I set the password with `set-initial-password` of neo, but its still gives me this error. 
Do you guys think it's neo4j fault for not being really active?

**Comment by poeti8** [comment]
Wait a few days, I'll make a video tutorial.

**Comment by Peppuz** [comment]
I mean, there is no need for a video, if you just gave a little bit of more documentation and references to other dependencies. 
I can edit the setup so that it can be a bit more helpful to get faster to a production-ready clone.

**Comment by uhlhosting** [comment]
I have 

> Hey @danysz, currently we don't have tutorial on how to install Node.js or Neo4j, because they are out of the scope of this repository. If you have them installed and filled the configs files correctly, then you should be fine.
> If enough people request, I may create a video tutorial on how to deploy Kutt on a VPS.

This is a very untrue, I have managed to setup Node.js, Neo4j and NPM as required prior to kutt. Did made minimal config.js changes and to my amaze, nothing works. Nothing to debug, no logs, ip has nothing on it, no options to add SSL from what I seen. If so, this now needs to be redirected to a browser, since it seems the 1 > 7 steps from the Readme.MD are good for who wrote it, not for rest.

**Comment by poeti8** [comment]
Alright then, I'll write everything I know on how I deployed Kutt and I'll add it to the repo as soon as I can. If you guys could tell where you had the most issues or where it was the most confusing part for you then I'll focus on that part more.

I'll also record a full walkthrough after.

**Comment by uhlhosting** [comment]
> Alright then, I'll write everything I know on how I deployed Kutt and I'll add it to the repo as soon as I can. If you guys could tell where you had the most issues or where it was the most confusing part for you then I'll focus on that part more.
> 
> I'll also record a full walkthrough after.

Well, i mentioned what I found as a issue during my attempt to install on Ubuntu 18.04. In the end one almost has no logs to read, nothing on the IP.

**Comment by Peppuz** [comment]
I had some issues on installing neo4j, but looked for the official guide which was an easy step-by-step for Debian stretch. I suggest to link them out: [debian installation](http://debian.neo4j.org/).
Redis was pretty straight forward tho.

I'm stuck at the index, i started the frontend, filled the config (except for the Google Ads), trying to use the shortner it goes on infinite loading. 😢

**Comment by uhlhosting** [comment]
@Peppuz what have you done until now? and what you use a frontend? nginx or apache? Did you checked latest wiki updates?
