### ISSUE TITLE
error with : process.env.NODE_ENV !== production

### ISSUE THREAD

**Issue by tavakoli-ali** [thedevs-network/kutt#155]
I have issue with run : 
here is my log 

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@6.7.0
3 info using node@v11.11.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle kutt@1.2.0~prestart: kutt@1.2.0
6 info lifecycle kutt@1.2.0~start: kutt@1.2.0
7 verbose lifecycle kutt@1.2.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle kutt@1.2.0~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/alitavakoli/Downloads/kutt-develop/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle kutt@1.2.0~start: CWD: /Users/alitavakoli/Downloads/kutt-develop
10 silly lifecycle kutt@1.2.0~start: Args: [ '-c', 'NODE_ENV=production node ./server/server.js' ]
11 silly lifecycle kutt@1.2.0~start: Returned: code: 1  signal: null
12 info lifecycle kutt@1.2.0~start: Failed to exec start script
13 verbose stack Error: kutt@1.2.0 start: `NODE_ENV=production node ./server/server.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:197:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:197:13)
13 verbose stack     at maybeClose (internal/child_process.js:984:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
14 verbose pkgid kutt@1.2.0
15 verbose cwd /Users/alitavakoli/Downloads/kutt-develop
16 verbose Darwin 18.2.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v11.11.0
19 verbose npm  v6.7.0
20 error code ELIFECYCLE
21 error errno 1
22 error kutt@1.2.0 start: `NODE_ENV=production node ./server/server.js`
22 error Exit status 1
23 error Failed at the kutt@1.2.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by poeti8** [comment]
Did you install dependencies? Did you build the app before starting it?

**Comment by tavakoli-ali** [comment]
yeah ,I did it : 
You need to have Node.js, Neo4j and Redis installed on your machine.

**Comment by tavakoli-ali** [comment]
its fixed by : npm install -D fsevents@1.2.4
and sudo su
