### ISSUE TITLE
In cant access Kutt with port 3000 it redirect me to my nginx page

### ISSUE THREAD

**Issue by marrobHD** [thedevs-network/kutt#158]
In cant access Kutt with port 3000 it redirect me to my nginx page

**Comment by poeti8** [comment]
Probably your NGINX config is not set correctly. I can't tell without looking at the code.

**Comment by abhijithvijayan** [comment]
@marrobHD set up nginx reverse proxy for the domain after creating nginx virtual hosts.
set **root**  to point to kutt directory and proxy nginx to the correct port.


try https://www.digitalocean.com/community/tutorials/how-to-set-up-a-node-js-application-for-production-on-ubuntu-16-04

**Comment by poeti8** [comment]
Shared my NGINX config here:
https://github.com/thedevs-network/kutt/wiki/Setup-and-deployment
