### ISSUE TITLE
How to run locally without it redirecting to kutt.it

### ISSUE THREAD

**Issue by ayoungh** [thedevs-network/kutt#16]
Sorry if this is a silly question, but how can I run dev locally without going to localhost and it redirects to your site? Thanks

**Comment by poeti8** [comment]
Have you entered your domain in `server/config.js`? Try adding `localhost:8888` (or your configed port) to the config file.

**Comment by trgwii** [comment]
Port shouldn't be part of domain tbh, just get it from the port value :P

**Comment by ayoungh** [comment]
![screen shot 2018-02-27 at 17 55 50](https://user-images.githubusercontent.com/404328/36745484-910c6498-1be7-11e8-890f-e4e9e839913f.png)

I've tried doing just localhost but I have apache running to serve some php stuff on localhost too, could this be the issue? I have also tried to add a line to my host file like `127.0.0.1 kutttry.it` and set the config to this domain but it just shows my directory listing that I have set for php stuff

**Comment by poeti8** [comment]
@ayoungh Make sure latest version of Node.js and Neo4j is installed and make sure that you have started Neo4j database. Also, change the port to something that is not used by another service.

**Comment by sarthak0906** [comment]
Using localhost:3000 as default domain the app starts at index but crashes as soon as it loads completely.
Any reason for this one

**Comment by trgwii** [comment]
Are you accessing it through `http://localhost:3000/` or `http://127.0.0.1:3000/` ?

The way you access it should match what your config points to
