### ISSUE TITLE
Install Kutt

### ISSUE THREAD

**Issue by sgorki** [thedevs-network/kutt#163]
I have a web hosting. How to install Kutt?
Is there any video show how to install?

**Comment by Peppuz** [comment]
Hi, I don't think you can install the repository with a webhost.
You might need a VPS, or at least a terminal, to install the repo and dependencies like Neo4j and Redis for making it run properly.

**Comment by poeti8** [comment]
If you're going to host the app and the database yourself then you're gonna need a VPS. 
And regarding the video, I'll make a tutorial on how to install Kutt on a VPS soon.
