### ISSUE TITLE
Setting up custom domain - when self hosting

### ISSUE THREAD

**Issue by coolboi567** [thedevs-network/kutt#164]
Using `kutt.it`, I was able to use custom domain but, I found that there are API limits.

So, I wanted to setup custom domain when I am self-hosting **kutt**.

**Comment by trgwii** [comment]
wat

**Comment by coolboi567** [comment]
@trgwii Lol, I saw that coming.

I have edited the issue. Please, have a look at it again.

**Comment by coolboi567** [comment]
The issue has been resolved.

There was a silly mistake from my side.
