### ISSUE TITLE
Did someone managed to deploy this in Production?

### ISSUE THREAD

**Issue by uhlhosting** [thedevs-network/kutt#167]
If someone managed to deploy this a tutorial would be appreciated. worst readme ever/.

**Comment by abhijithvijayan** [comment]
I had in the past. The only difficulty is when you set up Neo4j and Redis. For that you have to follow Neo4j and Redis official documentation and also set up nginx reverse proxy to deploy Node App.

**Comment by uhlhosting** [comment]
@abhijithvijayan can you share your nginx config? I managed to make it visible alto some SSL weird issue is hitting the node.js console.

**Comment by poeti8** [comment]
https://github.com/thedevs-network/kutt/wiki/Setup-and-deployment
