### ISSUE TITLE
Browser Extension

### ISSUE THREAD

**Issue by Armaldio** [thedevs-network/kutt#17]
What about having a browser extension like when you click on the extension icon it generates you directly a shorten url without leaving the page ?

**Comment by poeti8** [comment]
That's a great idea. Although I haven't created a browser extension so far. I'll look into it.

**Comment by armaldio** [comment]
There is now a WebExtension API
https://developer.mozilla.org/fr/Add-ons/WebExtension to write
cross-browser extensions

I can also help

Le lun. 26 févr. 2018 à 22:29, Pouria Ezzati <notifications@github.com> a
écrit :

**Comment by armaldio** [comment]
@poeti8 Are you on this ? Otherwise I should be able to at least make a draft if you want

**Comment by poeti8** [comment]
@armaldio would be amazing if you do.

**Comment by armaldio** [comment]
I don't know more about how login and saving works internally for kutt so I dind't made anything related to that but I've grabbed a boilerplate for cross-browser extension and  I've customized it: [KuttExtension.zip](https://github.com/thedevs-network/kutt/files/1839599/KuttExtension.zip)

**Comment by ltjdym** [comment]
This would be awesome!

**Comment by MKRhere** [comment]
I can take this issue. I'll work on some weekends. Shouldn't be too hard.

**Comment by abhijithvijayan** [comment]
It would be awesome if the url shortener was for major browsers and incl a qr code and the link at the time of clicking the extention


As seen in Goo.gl extension in chrome (unofficial)

**Comment by abhijithvijayan** [comment]
https://github.com/abhijithvijayan/kuttUrl-Chrome

**Comment by poeti8** [comment]
@abhijithvijayan Good job, some improvements:
1- Change logo to Kutt's logo
2- Instead of setting API key by hand, add it to settings.
3- Settings also should have custom domain and password options.

**Comment by abhijithvijayan** [comment]
@poeti8 The api only permits 50 requests per day. Any thought on increasing that?

Thanks for the other suggestions.

**Comment by poeti8** [comment]
Not for now, I might add a paid plan.

**Comment by abhijithvijayan** [comment]
> @abhijithvijayan Good job, some improvements:
> 1- Change logo to Kutt's logo
> 2- Instead of setting API key by hand, add it to settings.
> 3- Settings also should have custom domain and password options.

I have implemented the first two features as requested.
The Extension Icon is set and also API can be set on the options page.

Due to CORS issue, I had to temporarily set up a cors policy to shorten urls.

**Comment by poeti8** [comment]
Forget about the custom domain, it must be set from the app's setting not there. You can add password though.
Today I need to move db and do some stuff after that I'll add CORS headers.

**Comment by poeti8** [comment]
Well, if user sets a password in settings, all links are going to be shortened by that password, no need to do it two times.
For API delay, there was some issues today, might be because of that.

**Comment by abhijithvijayan** [comment]
@poeti8 I thought of setting new password every time for a new link. seems like that is not a good approach to simplicity. I'll add the single password then. :grinning:

**Comment by poeti8** [comment]
@abhijithvijayan Yes just make sure its text clrealy says password for URLs so user don't mistake it with account password.

**Comment by abhijithvijayan** [comment]
@poeti8 Done. Test it out now with the new release on extension's release page. Feedbacks are welcome.

**Comment by poeti8** [comment]
@abhijithvijayan Great. I'll test it soon. Please also see if you can also make it work on Firefox and I'll publish them in their stores and also will update the readme and the website to tell users about the extension.

**Comment by abhijithvijayan** [comment]
I'll see if I can make it work in firefox too with `web-ext`.

I'll try that the week after next week.

and thanks for the support :grinning:

**Comment by stefanes** [comment]
From the README:
> Kutt.it API permits 50 URLs shortening per day using the API Key. Upgrade to Paid plan for more.

There is no paid plan (yet) right? If not, this is misleading.

**Comment by poeti8** [comment]
> There is no paid plan (yet) right? If not, this is misleading.

Yes that should be removed.

**Comment by abhijithvijayan** [comment]
@stefanes Thank you for noticing.
I'm porting the extension to work with Firefox too now.
I'll remove it soon when I'm done.

**Comment by abhijithvijayan** [comment]
What are all the other possible return status codes for the API call?
400 for Long Length limit
429 for API daily limit

**Comment by poeti8** [comment]
400 for general errors
401 for unauthorized
429 for limit

All of them return a JSON with error message, you can just show that message.
`{ error: <message> }`

**Comment by poeti8** [comment]
Kutt extension is now published for Firefox:
https://addons.mozilla.org/en-US/firefox/addon/kutt/

**Comment by abhijithvijayan** [comment]
> Kutt extension is now published for Firefox:
> https://addons.mozilla.org/en-US/firefox/addon/kutt/

Instruction to generate the API key could be mentioned in that url

**Comment by IamTregsthedev** [comment]
Is there one for chrome?

**Comment by abhijithvijayan** [comment]
@IamTregsthedev it is yet to be published to chrome store. meanwhile, you can try it out by downloading the latest release zip file and following guidelines on the contributing.md page.

**Comment by IamTregsthedev** [comment]
Alright, Thanks.

**Comment by poeti8** [comment]
Kutt extension is now published on Chrome store too.
https://chrome.google.com/webstore/detail/kutt/pklakpjfiegjacoppcodencchehlfnpd

**Comment by abhijithvijayan** [comment]
Thanks @poeti8 
I'll update the links in the readme of the [repo](https://github.com/abhijithvijayan/kutt-extension)

**Comment by abhijithvijayan** [comment]
@poeti8 I noticed the steep in extension users.
In order to improve the UX, updating the store versions to 0.6.2 could be good.
Thanks

**Comment by poeti8** [comment]
@abhijithvijayan Updated, thanks.

**Comment by abhijithvijayan** [comment]
@poeti8 Please update to version 1.0.2. It includes some fixes and unnecessary code removal.

**Comment by abhijithvijayan** [comment]
@poeti8 Please update to version 1.0.4.

**Comment by poeti8** [comment]
@abhijithvijayan Updated. You forgot to update the version in manifest files. I watch releases in the repo to get notifications.You can also mail support@kutt.it instead of sending a message here.

**Comment by abhijithvijayan** [comment]
> @abhijithvijayan Updated. You forgot to update the version in manifest files. I watch releases in the repo to get notifications.You can also mail [support@kutt.it](mailto:support@kutt.it) instead of sending a message here.

Sorry about that. I will fix that soon. Release notification sounds great.

**Comment by RokeJulianLockhart** [comment]
https://addons.mozilla.org/en-US/firefox/addon/kutt/

> Oops! We can’t find that page
