### ISSUE TITLE
Kutt it redirection

### ISSUE THREAD

**Issue by uhlhosting** [thedevs-network/kutt#170]
How can one solve this? we have in place all requirements:
Node.js, NPM, Neo4j

And made all steps like explained in Readme
```
root@for:/home/cosmic/kutt-develop# npm start

> kutt@1.2.0 start /home/cosmic/kutt-develop
> NODE_ENV=production node ./server/server.js
> Ready on http://localhost:3000
node_redis: Warning: Redis server does not require a password, but a password was supplied.

root@for:/# curl http://localhost:3000
Moved Permanently. Redirecting to https://uhl.site/
root@for:/# curl https://uhl.site/
curl: (7) Failed to connect to uhl.site port 443: Connection refused

```

**Comment by poeti8** [comment]
How are you handling SSL? Seems like HTTPS is not yet implemented for your website.

**Comment by uhlhosting** [comment]
Well I do not handle it, since no where I was having the option to add ssl for node or kutt durring the setup guide.

**Comment by poeti8** [comment]
It has nothing to do with Kutt or Node.js, you should handle SSL yourself. See Let's Encrypt for free SSL service.

**Comment by uhlhosting** [comment]
@poeti8 I solved the SSL now the instance is on at https://uhl.site
The only things left is that every second third refresh gives me an error on page, also the login account I cannot reset it. It seems to give me some errors.

`(node:6102) UnhandledPromiseRejectionWarning: Error: Error: 140558557539200:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:s23_clnt.c:827:

    at fn.catch.err (/home/cosmic/kutt-develop/server/server.js:32:13)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
(node:6102) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6102) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`
