### ISSUE TITLE
Issues after Nginx Proxy in place

### ISSUE THREAD

**Issue by uhlhosting** [thedevs-network/kutt#171]
After following the updates on the wiki side, I have managed to bring online the first instance of kutt.it at uhl.site now I am left with these issues:

- I cannot reset the password for current user
`Sorry an error ocurred. Please try again later.`
- When trying to create a new user on Web I get:
`Sorry an error ocurred. Please try again later.`
 On CLI:
```
(node:6102) UnhandledPromiseRejectionWarning: Error: Error: 140558557539200:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:s23_clnt.c:827:

    at fn.catch.err (/home/cosmic/kutt-develop/server/server.js:32:13)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
(node:6102) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

- Related to SSL not sure what the issue could be, the SSL was deployed by NGINX documentation,
here have made some [SSL tests](https://www.ssllabs.com/ssltest/analyze.html?d=uhl.site)

**Comment by uhlhosting** [comment]
This is related to somehow not accepting the mailserver settings from cpanel. Moved to Zimbra and it worked fine to create account. The only thing was this remaining:

```
Refused to execute script from 'https://uhl.site/analytics.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
settings:1 Uncaught (in promise) DOMException
api/auth/usersettings:1 Failed to load resource: the server responded with a status of 400 ()
api/auth/renew:1 Failed to load resource: the server responded with a status of 400 ()
```

**Comment by poeti8** [comment]
Show me the error on the server side.

**Comment by uhlhosting** [comment]
On server side from pm2 logs 0 --lines 1000 nothing shows up while I do the reset password process. Yet on Inspect website this shows up:

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/6324047/57777326-f6d08e80-7721-11e9-8c89-04e3901623bf.png">

```
[Error] Refused to execute https://uhl.site/analytics.js as script because "X-Content-Type: nosniff" was given and its Content-Type is not a script MIME type.
[Error] Unhandled Promise Rejection: TypeError: Script https://uhl.site/reset-password/sw.js load failed
[Error] Failed to load resource: the server responded with a status of 400 () (usersettings, line 0)
[Error] Failed to load resource: the server responded with a status of 400 () (renew, line 0)
```

**Comment by uhlhosting** [comment]
`[Error] Failed to load resource: the server responded with a status of 400 () (submit, line 0) https://uhl.site/api/url/submit`

This is sudden error, not sure what is causing this...
