### ISSUE TITLE
Enabling Safe Browser breaks website.

### ISSUE THREAD

**Issue by uhlhosting** [thedevs-network/kutt#174]
I have enabled and tried to test Safe Browser limits from Safe google API. And this crashed the URL shortener.

**Comment by uhlhosting** [comment]
```
root@uhl:/etc/nginx# grep -iRl "includeSubDomains" /home/cosmic/kutt-develop/
/home/cosmic/kutt-develop/node_modules/hpkp/README.md
/home/cosmic/kutt-develop/node_modules/hpkp/index.js
/home/cosmic/kutt-develop/node_modules/helmet/CHANGELOG.md
/home/cosmic/kutt-develop/node_modules/hsts/README.md
/home/cosmic/kutt-develop/node_modules/hsts/CHANGELOG.md
/home/cosmic/kutt-develop/node_modules/hsts/index.js
root@uhl:/etc/nginx# 

```

These are only places where the HSTS elements are mentioned. Can someone help with this settings I need to put site in preload.

**Comment by trgwii** [comment]
We would need much more information than this:

* Which settings did you change?
* What was the console output of Kutt?
* What did the website do that wasn't correct behavior?

Etc

**Comment by uhlhosting** [comment]
@trgwii 
I enabled the Safe Browsing API in server.js

The only thing left for me to try is to do a test again with the Safe Browsing API
