### ISSUE TITLE
Add filter to avoid same url duplicates.

### ISSUE THREAD

**Issue by uhlhosting** [thedevs-network/kutt#175]
If one goes to same url and makes 10 different shortcuts via the kutt extension for example, the server will just create the entries, without querying to see if there is already a url shortened for the current address. Its maybe a great thing to avoid duplicates.

**Comment by poeti8** [comment]
Duplicated issue, we have already implemented `reuse: true` for API users. #74

**Comment by uhlhosting** [comment]
@poeti8 can you check and give me some hints on the HSTS issue I have, I am not sure how to enable this on server side, since it is managed by the kutt and not by nginx.
