### ISSUE TITLE
Redis server does not require a password, but a password was supplied.

### ISSUE THREAD

**Issue by dinhkhanh** [thedevs-network/kutt#176]
I've install all dependencies with `npm install`.
Redis and Neo4j are running properly (working with other web app on my manchine).

When I run `npm run dev`, it says:
```
/usr/local/bin/node /usr/local/lib/node_modules/npm/bin/npm-cli.js run dev --scripts-prepend-node-path=auto

> kutt@1.2.0 dev /Users/dinhkhanh/Downloads/kutt-develop
> nodemon -w ./server/**/*.js ./server/server.js

[nodemon] 1.18.10
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: ./server/controllers/authController.js
[nodemon] starting `node ./server/controllers/urlController.js ./server/controllers/validateBodyController.js ./server/db/neo4j.js ./server/db/url.js ./server/db/user.js ./server/mail/mail.js ./server/mail/text.js ./server/offline/sw.js ./server/utils/index.js ./server/server.js`
node_redis: Warning: Redis server does not require a password, but a password was supplied.
```

It stucked there. I don't know what to do next.

I'm using macOS Mojave. Redis with no password. Neo4j with password. I'm sure that I have properly configuration files.

Thanks

**Comment by trgwii** [comment]
This just looks like a non-critical warning from Redis? Does this break the functionality of Kutt or is the app actually working?

**Comment by poeti8** [comment]
As Thomas said it's just a warning and does not have any affects on the app. So the problem should be something else. I pushed a commit to not get the warning anymore and also fixed an issue with nodemon in macOS. Try again and let me know if it is resolved.

**Comment by dinhkhanh** [comment]
HI @trgwii and @poeti8 

I confirm that it works now. 
So, it's not just a warning. I think on macOS, it breaks and stops the nodemon. 

Thank you anyway, so far so good.
