### ISSUE TITLE
redirect to localhost:3000 is crashing react application

### ISSUE THREAD

**Issue by sarthak0906** [thedevs-network/kutt#179]
When redirecting the request to the localhost:3000 crashes the react app as soon as the react app is loaded completely.

**Comment by poeti8** [comment]
Show us an error or something, I can't guess what's happening.

**Comment by sarthak0906** [comment]
I would love an error or something along those lines but the index page crashes without any error in console.
To elaborate my error I am trying to open the localhost:3000 on my browser(after clearing all the cookies so that I do not go to Kutt.it by default) but if I set default domain to localhost:3000 the index loads and then automatically crashes.
the problem doesn't seem to affect any other page as if I directly redirect to them from localhost:3000/key it works fine. Also, the elements seem to be working fine too as I did checked putting them in other pages and the pages worked just fine.
I need a bit assistance in this as I am just not able to understand what is happening or why!

**Comment by trgwii** [comment]
What do you mean by "crashes"? Your web browser closes?

**Comment by poeti8** [comment]
Have you tried using another port?

**Comment by dre-delano** [comment]
> 
it website shows briefly the goes to a blank screen, only when accessing on localhost3000, website functions as intended on localnetwork
