### ISSUE TITLE
reset password token expiry

### ISSUE THREAD

**Issue by abhijithvijayan** [thedevs-network/kutt#184]
a token and a reset password expiry time already given, but it appears that the user can reset it any time even after the time is expired.

It is the cause of matching the user just with the reset token and not including the expiry check condition.

I can submit a PR if you want. 

also I find that the verification of user is just done by searching the db with the verification email code, isnt is more convenient to add email to the verification url as a param and search the db with 2 params?

**Comment by poeti8** [comment]
> I can submit a PR if you want.

Yes please.

> isnt is more convenient to add email to the verification url as a param and search the db with 2 params?

No, I don't see an issue with the current process.

**Comment by abhijithvijayan** [comment]
What is your say on creating a timer for verifying the account?
i.e, Limiting user to an hour for verifying the account.

Even if they fail to verify, they can sign up for a new account (which is already implemented in the db query)
