### ISSUE TITLE
unable to login or use API

### ISSUE THREAD

**Issue by Dragonblitz10** [thedevs-network/kutt#190]
HTML1300: Navigation occurred.
kutt.it (1,1)

 SEC7112: Script from https://kutt.it/analytics.js was blocked due to mime type mismatch
kutt.it (1,1)

 DOM7009: Unable to decode image at URL: ‘data:image/png;base64,iVBORw0KGgBpLSYkOkU9XLAVOfqFLrz4wBw0YFXJXInXNlFFeX2ukBmdJxVw6icC+l2Q/lEwBZc+3OdDs1/j9X/8BtXt+r2qAI2/srwBXjvPtRQ7D8kBSWTMEItWQgBYT2L58brJiguXWQoRzxjB5j6Xrsj2zEwSzD6bC7FTdQB60wwo8ruofstCLNhHH5omTABfTcjDig7LNi1abmZfwBrJ1vuRj88QBYy65REUBdqIbBi0yubbufOVRhNb84WyEB9mBbIcZoBVVQ6Uo6Qb40ptMeb1UHwB89V5XHA+BrSUOOyXWBp3WAf5qQBLPJFj0Rlx8wBdaQiVmS+iAMBAd+sCUxtXrP+/wBWbZwO5Y9RCTSBbx5GQY+vjEABqvec5ov9KrsKaIHx’ with MIME: ‘image/png’.
wBWbZwO5Y9RCTSBbx5GQY+vjEABqvec5ov9KrsKaIHx (1,1)

3 SCRIPT12030: SCRIPT12030: WebSocket Error: Network Error 12030, The connection with the server was terminated abnormally

**Comment by Wexx** [comment]
Experiencing the same thing. Chrome and Firefox.

**Comment by mrmmg** [comment]
I have the same issue. please consider it.

**Comment by devakira** [comment]
I've got the same issue as well.

**Comment by mrcodekiddie** [comment]
Probably , their hosting issue.. Working perfectly in my localhost  🍷

**Comment by Wexx** [comment]
Yeah, it started working again later that day. Planning on moving to my own host eventually.

**Comment by Dragonblitz10** [comment]
same

**Comment by poeti8** [comment]
It's not a hosting issue. We're having too much requests, more than I expected, I'm working on scaling the app.

**Comment by abhijithvijayan** [comment]
still down?

**Comment by poeti8** [comment]
@abhijithvijayan No it hasn't been down since then. Did you had issues?

**Comment by abhijithvijayan** [comment]
@poeti8 yeah, at the time of the comment.

**Comment by poeti8** [comment]
#197 is going to solve this issue.
