### ISSUE TITLE
Step by Step Kutt.it Install Procedure

### ISSUE THREAD

**Issue by dkarthe** [thedevs-network/kutt#193]
Hi,
Anyone help me to build a kutt based urlshortner on self-hosted machine.. 
in my case neo4j installation step was failed. anyone can help me out via remote method.

**Comment by mrcodekiddie** [comment]
making an installer, Hold on for a week  😛

**Comment by agenceKanvas** [comment]
Hello !
Any update on the installer ?
I can't get it to work ... 
I have a 502 bad gateway and in logs : 
[error] 8900#8900: *15 connect() failed (111: Connection refused) while connecting to upstream, client: 81.80.95.211, server: www.mydomain.me, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8888/", host: "mydomain.me"

**Comment by agenceKanvas** [comment]
Bump :) That would be awesome. I'm planning to use that for my team of journalists 👍

**Comment by poeti8** [comment]
@mrcodekiddie Be aware that I'm rewriting the back-end (#197), so don't waste time on the Neo4j part.

**Comment by agenceKanvas** [comment]
@poeti8 Do you have a step by step to make it run on our server ? For total noobs in node and npm please ? :)

**Comment by poeti8** [comment]
@agenceKanvas I wrote one in the wiki:
https://github.com/thedevs-network/kutt/wiki/Setup-and-deployment

**Comment by agenceKanvas** [comment]
@poeti8 Yes thanks for that :) But even with folliowing it, at the end I have a :  
502 bad gateway and in logs :
[error] 8900#8900: *15 connect() failed (111: Connection refused) while connecting to upstream, client: 81.80.95.211, server: www.mydomain.me, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8888/", host: "mydomain.me"
