### ISSUE TITLE
Docker usage

### ISSUE THREAD

**Issue by yassinehamouten** [thedevs-network/kutt#196]
Hello,

How do you use docker with Kutt?
Can you give an .env example working with docker ?

I have an error with redis. App cannot connect to redis

**Comment by poeti8** [comment]
Remember when use Docker `REDIS_HOST` is `redis` not localhost.

**Comment by yassinehamouten** [comment]
Thank you for the fast reply :) 

Yes I tried with redis as host but still in error. Do you pass port when using redis as host ?

**Comment by poeti8** [comment]
The default port, yes. What error do you get?

**Comment by yassinehamouten** [comment]
*facepalm* 
I tried with REDIS_HOST="redis" but that working like this -> REDIS_HOST=redis
