### ISSUE TITLE
Migrating from Neo4j to Postgres

### ISSUE THREAD

**Issue by poeti8** [thedevs-network/kutt#197]
I chose Neo4j for Kutt because it was easier for me to think in graphs when I was planning on how to structure visits and stats for links. Now after a year of Kutt's release, I encountered some issues with performance, efficiency and accuracy of the current model.

I decided to change the way I store stats and I realized that in the new model I don't rely on graphs really. And that lead up to thinking in migrating to ~~MongoDB~~ Postgres.

Some advantages I see with ~~MongoDB~~ Postgres:
- New stats model, faster stats, better performance
- Less usage of resources (RAM and CPU)
- Easier to deploy and scale (Neo4j needs enterprise license)
- Better community, easier to search for issues
- People who want to use Kutt, are probably way more familiar with ~~MongoDB~~ Postgres

Although I like Neo4j, but it seems like it's not suitable for my use case anymore.

**Comment by abhijithvijayan** [comment]
I can also work with you on this in the free time.

But relationships in mongodb are somewhat not as much as simple and free as in neo4j

**Comment by abhijithvijayan** [comment]
Did you start working on this? i can help on this too.

I too find neo4j lacking performance.

**Comment by poeti8** [comment]
It's done, I'm doing migration script and will go live soon!

**Comment by LogoiLab** [comment]
@poeti8 I can't seem to see any reference to the change in the repo. The latest commit to the neo4j-to-mongodb branch is 2 months old. Have you just not pushed any code?

**Comment by poeti8** [comment]
@LogoiLab Well, when I finished moving to MongoDB I decided that Postgres could be a better option, so I worked on that and now it's in another branch that I'll push to soon in coming days.

**Comment by LogoiLab** [comment]
Cool. Going to spin up an instance on my domain at https://redi.rs/ for public use. I want to wait till you settle on something.

**Comment by poeti8** [comment]
New version is live at kutt.it! Just some minor bug fixes and completing README.

**Comment by nightah** [comment]
@poeti8 the migration script doesn't seem to quite work properly.

First 3 steps (hosts, users. domains) all seem to work without error though links errors out a significant amount per: https://pastebin.com/cShaBVDZ

Despite all the errors I still see: ✅ Done! It took 1.214 seconds.

When I look in the underlying postgres DB, It looks like it still does migrate the links, just not any of the visits as the table is empty.

**Comment by poeti8** [comment]
@nightah Ah, I think it's because I have updated `date-fns` dependency a few days back. I'll update the script to match new `date-fns` API.

**Comment by nightah** [comment]
I'll standby for the update, if you need me to test anything in the interim let me know.

**Comment by poeti8** [comment]
@nightah Test again now.

**Comment by nightah** [comment]
@poeti8 confirmed working now.
