### ISSUE TITLE
Error: Request failed with status code 403

### ISSUE THREAD

**Issue by TheYahya** [thedevs-network/kutt#20]
I get this warning when try to submit a url:
```
(node:29527) UnhandledPromiseRejectionWarning: Error: Error: Request failed with status code 403
    at fn.catch.err (/path/to/kutt/server/server.js:27:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
(node:29527) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:29527) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by poeti8** [comment]
Make sure database is connected properly.

**Comment by TheYahya** [comment]
hi @poeti8 
It's connected, I just signed-up and user created in database.

**Comment by poeti8** [comment]
@TheYahya Did you also provided all the API keys in the config file?

**Comment by maykonl** [comment]
I have the same problem:

POST /api/auth/renew 200 184.011 ms - 240
GET /_next/-/page/_error.js.map 404 21.453 ms - 31516
GET /_next/webpack/b1405e7c94c5ed8fd82b.hot-update.json 200 3.489 ms - 35
GET /api/url/geturls?isShortened=false&count=10&countAll=0&page=1&search=& 200 198.369 ms - 24
GET /_next/on-demand-entries-ping?page=/ 200 2.658 ms - -
GET /images/loader.svg 200 1.134 ms - 731
POST /api/url/submit 500 277.878 ms - 59
(node:15374) UnhandledPromiseRejectionWarning: Error: Error: Request failed with status code 403
    at fn.catch.err (/portal/kutt-develop/server/server.js:27:13)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
(node:15374) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:15374) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
GET /_next/on-demand-entries-ping?page=/ 200 1.410 ms - -
GET /_next/on-demand-entries-ping?page=/ 200 1.434 ms - -
GET /_next/on-demand-entries-ping?page=/ 200 1.326 ms - -
GET /_next/on-demand-entries-ping?page=/ 200 1.058 ms - -

**Comment by larue3000** [comment]
@TheYahya 

I encountered the same problem. Make sure Google Safe Browsing API is enabled.

.../server/controllers/urlController.js  performs a post request to Google Safe Browsing API. 

Here is body of the 403 response from Google Safe Browsing API

"error": {
    "code": 403,
    "message": "Google Safe Browsing API has not been used in project projectname-000000 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/safebrowsing.googleapis.com/overview?project=projectname-000000 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.",
    "status": "PERMISSION_DENIED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.Help",
        "links": [
          {
            "description": "Google developers console API activation",
            "url": "https://console.developers.google.com/apis/api/safebrowsing.googleapis.com/overview?project=projectname-000000"
          }
        ]
      }
    ]
  }
}

To verify try the following:

curl -kvi -H "Content-Type:application/json" -H "Accept: application/json" --data-binary "{ \"client\": { \"clientId\": \"yoursitecom\", \"clientVersion\": \"1.5.2\" }, \"threatInfo\": { \"threatTypes\": [\"MALWARE\", \"SOCIAL_ENGINEERING\"], \"platformTypes\": [\"ANY_PLATFORM\"], \"threatEntryTypes\": [\"URL\"], \"threatEntries\": [{\"url\": \"https://website.com/static/demo.html\"} ] } }" -X POST "https://safebrowsing.googleapis.com/v4/threatMatches:find?key=your-api-key"

**Comment by maykonl** [comment]
Thankyou Yahya, i had not enabled api safe browsing previously created on google.

**Comment by TheYahya** [comment]
Thanks @maykonl, I will check that.
