### ISSUE TITLE
shows wrong location stats 

### ISSUE THREAD

**Issue by ajay01994** [thedevs-network/kutt#202]
Hi Thanks for developing Kutt , 
I was testing Kutt on my chrome browser .Everything looks fine but the stats showed wrong location , i was testing it on my browser in India but it showed the loaction to ber in SG (Singapore )
![kutt location ](https://user-images.githubusercontent.com/31235529/61964551-c3489500-afeb-11e9-9ca0-5046093f4e12.png)
Thank you !

**Comment by MKRhere** [comment]
Limitation of the MaxMind GeoIP database Kutt uses; an IP they identified as being from Singapore has since changed (?), or was misidentified. This is to be expected from any IP-based country identification system, and there's not much Kutt can do here. The idea is one off errors are tolerable.

**Comment by Saleh56** [comment]
S

**Comment by Saleh56** [comment]
F

**Comment by Saleh56** [comment]
> F
