### ISSUE TITLE
Kutt.it is down!

### ISSUE THREAD

**Issue by Saad-LUMS** [thedevs-network/kutt#204]
Kutt.it is down for the third time in a month.

Unable to login, won't open links and this error shows:
![image](https://user-images.githubusercontent.com/26320083/62102296-e73cfc80-b2b1-11e9-9852-eba2c5e8d7f6.png)

This is the third time I'm seeing this in a month's time span. I loved the service but due to random and long outages I will be switching to some other link shortener.

**Comment by poeti8** [comment]
I'm aware of the issue and I'm rewriting the app right now (#197), a new version will be up in the next week.
