### ISSUE TITLE
How Can I use Kutt API as URL Format and Get Response As Plain Text

### ISSUE THREAD

**Issue by xianx** [thedevs-network/kutt#208]
Hello,

I am using a service where to create short url and to use, it need short url to be like this

http://myshorturlservice.com/api/url/submit?login=janedoe&amp;apiKey=48d1d55b5a48d4ec2c5152f4419b3c44&amp;url=@URL@

and need to get plain text result like http://myshorturlservice.com/skdfjs

How can I use kutt api like this?

is it possible to change nginx config and post and get result like this?

**Comment by trgwii** [comment]
I'm not sure what you're asking for here, can you try to explain it more clearly?

**Comment by hi-too** [comment]
@xianx  Hello, check this out: https://v.ht/API-Docs/en.html

**Comment by xianx** [comment]
kutt API now only output json result. We want to output API result as text only. API result will be just the shortened url like kutt.it/R2345

How to do that?

**Comment by poeti8** [comment]
Kutt only sends JSON you need to fork and set up your own instance to change the behavior.
