### ISSUE TITLE
Option to disable anonymous creation of short-links

### ISSUE THREAD

**Issue by FlorianLudwig** [thedevs-network/kutt#210]
When having a private instance of kutt.it it would be great to make it fully private: No anonymous link creation and no user account creation.

**Comment by trgwii** [comment]
I think a better idea would be to have config switches for each thing:
disallowAnonymousLinks=true
disallowRegistration=true

Then you could simply set both of these to true after creating a single account and restart kutt, and you'd be done.

**Comment by NX211** [comment]
I host Kutt locally and would love to see this feature implemented.

**Comment by poeti8** [comment]
> I think a better idea would be to have config switches for each thing:
> DISALLOW_ANONYMOUS_LINKS=true
> DISALLOW_REGISTRATION=true

This is implemented now.
