### ISSUE TITLE
API rate limit

### ISSUE THREAD

**Issue by FingerlessGlov3s** [thedevs-network/kutt#213]
Hi,

What is the API rate limit of normal account? 
How many links can you shorten per hour?

**Comment by poeti8** [comment]
It's 50 per day for kutt.it for now.

**Comment by FingerlessGlov3s** [comment]
50 per day isn't too bad but not enough for the IRC RSS BOT I have in mind. It's currently doing 200ish shortens a day for maintainers instance.

I was hoping it was higher as he could then implement Kutt, instead of bitly. Which would allow people to selfhost if they wanted.

**Comment by poeti8** [comment]
If you want to host it there's an option to set the limit to whatever amount you want. For the live website however, we will add free and paid plans in future.
