### ISSUE TITLE
Docker Setup Documentation

### ISSUE THREAD

**Issue by 8sd** [thedevs-network/kutt#214]
In the Readme file there is a link to the Docker Setup Guide [1] but the link is not working.
Futhermore an example `.env` file, making the docker image work out of the box, would be awesome.

[1] (https://github.com/thedevs-network/kutt/blob/develop/docker-examples)

**Comment by poeti8** [comment]
Old Docker docs have been removed and the Dockerfile has been updated.

**Comment by 8sd** [comment]
Well, only doing this is not enough. 
> You can use Docker to start the app. The simplest way is to just run docker-compose up command and then the app should be ready on port "3000".

Like you have to change the config for `redis` and `postgres` and so on.

There should be the dockerfile, which downloads a kutt image from dockerhub. 
The internal dependencies like `redis` should already work and the admin only needs to add the config like `DEFAULT_DOMAIN`.

**Comment by poeti8** [comment]
Reopening to improve the docs.

**Comment by botzill** [comment]
Also will be nice to have a public docker build so that we can easily test this in an environment like kubernetes. 

Thx.

**Comment by masterkain** [comment]
helm chart too.. _don't hate me_

**Comment by kiilo** [comment]
I dont get it to work with docker-compose.yml file provided

what changes? where?
`docker-compose up` get a bright:
```
...
kutt        | > Ready on http://localhost:3000
kutt        | events.js:287
kutt        |       throw er; // Unhandled 'error' event
kutt        |       ^
kutt        | 
kutt        | Error: Redis connection to "127.0.0.1":6379 failed - getaddrinfo ENOTFOUND "127.0.0.1"
kutt        |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:64:26)
kutt        | Emitted 'error' event on RedisClient instance at:
kutt        |     at RedisClient.on_error (/usr/src/app/node_modules/redis/index.js:406:14)
kutt        |     at Socket.<anonymous> (/usr/src/app/node_modules/redis/index.js:279:14)
kutt        |     at Socket.emit (events.js:310:20)
kutt        |     at Socket.EventEmitter.emit (domain.js:482:12)
kutt        |     at emitErrorNT (internal/streams/destroy.js:92:8)
kutt        |     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
kutt        |     at processTicksAndRejections (internal/process/task_queues.js:84:21) {
kutt        |   errno: 'ENOTFOUND',
kutt        |   code: 'ENOTFOUND',
kutt        |   syscall: 'getaddrinfo',
kutt        |   hostname: '"127.0.0.1"'
kutt        | }
...
```

@8sd - if you have a solution, document it please ...

thank you

**Comment by Niggl1999** [comment]
If you used an env file based on the .example.env you havt to change the redis config to reflect this:
```
# Redis host and port
REDIS_HOST=redis
REDIS_PORT=6379
REDIS_PASSWORD=
```
Alternatively you could also add `REDIS_HOST: redis` to then environment section of the kutt container in the docker-compose.yml.

I just started to play around with kutt in docker and ran into the same issue.
