### ISSUE TITLE
kutt forgets url

### ISSUE THREAD

**Issue by FlorianLudwig** [thedevs-network/kutt#215]
I am not sure what is happening, if kutt is actually forgetting them actually (as in somehow getting lost in the database) or if the api is answers are random.

After inserting a new link via the api the count of how many links changes in random patterns. Sometimes going up, sometimes going down.

I have caching/redis disabled.

I created a script which requests `/api/url/geturls` and prints `countAll` of the response and then submits a link via the api (and prints an error if the response is `!= 200` - no errors occuring):

```
countAll = 26
creating 1 link
countAll = 26
creating 1 link
countAll = 27
creating 1 link
countAll = 59
[... after some more it got back down... ]
countAll = 28
```

**Comment by poeti8** [comment]
@FlorianLudwig Can you test again please, I have re-written most of the app for v2 beta and it's live.

**Comment by trgwii** [comment]
@FlorianLudwig Posting the script you created would also be helpful, so we can make sure it's correct as well.

**Comment by FlorianLudwig** [comment]
I don't have the code anymore that I used to "stresstest" above.  The code I used to interact with the API is the following python class and added a similar main method to demonstrate:

```python
import requests

class Kutt:
    def __init__(self, apikey, base_url=""):
        self.apikey = apikey
        self.base_url = base_url.rstrip("/")

    @property
    def headers(self):
        return {'X-API-Key': self.apikey}

    def list(self):
        req = requests.get(f'{self.base_url}/api/url/geturls?count=10000', headers=self.headers)
        data = req.json()
        if len(data["list"]) != data["countAll"]:
            raise IOError("ERROR GETTING LIST OF ALL URLS")

        return data['list']

    def new(self, url, **args):
        payload = {}
        payload['target'] = url
        payload["domain"] = "example.com"
        payload.update(args)
        payload.setdefault('reuse', True)

        r = requests.post(f'{self.base_url}/api/url/submit', data=payload, headers=self.headers)
        if r.status_code != 200:
            print("error creating entry:", r.json()["error"])
            return False
        else:
            data = r.json()
            return data

    def delete(self, id):
        payload = {'id': id, "domain": "example.com"}
        r = requests.post(f'{self.base_url}/api/url/deleteurl', data=payload, headers=self.headers)

        if r.status_code != 200:
            print('eror delting', r.json())
            return False

        return True

def main():
    kutt = Kutt(KUTT_KEY, "http://127.0.0.1:3000")
    for i in range(1000):
       print(count(kutt.list())
       kutt.new("some-url", customurl=str(i))
```

Also.. I gave up on figuring out what was wrong with kutt and reimplemented it from scratch before you were done with your rewrite, so I never tested the rewrite:sweat_smile: 

So from my point of view this can be closed.
