### ISSUE TITLE
Wrong URL when use custom domain

### ISSUE THREAD

**Issue by lapphan** [thedevs-network/kutt#216]
When access stats page of a Kutt shortened URL with custom domain, the link in "Stats for:..." line is not updated with custom domain but **kutt.it** instead. When I click to this link I will get 404 page because the correct URL must be [custom domain]/[id], not **kutt.it**/[id]

I tried to make a PR but I am not familiar with React so...

![image](https://user-images.githubusercontent.com/11986206/64793702-a4a35b00-d5a5-11e9-9e05-777479f80c7c.png)

**Comment by poeti8** [comment]
@lapphan Do you still have this problem? We have updated Kutt to v2, would be nice if you check again and let me know.

**Comment by lapphan** [comment]
@poeti8 This problem is fixed. Thank you.
