### ISSUE TITLE
404 error - custom domain

### ISSUE THREAD

**Issue by Srini-B** [thedevs-network/kutt#22]
I used the IP provided in the settings panel to point A record to it and then added the domain name on the settings page. But I'm getting a 404 error, am I doing anything wrong or should i " * " or something on DNS record. My site has SSL installed is that any of problem

**Comment by poeti8** [comment]
It should be @ record. SSL might cause the problem too because the certificate is not set in our side.

**Comment by Srini-B** [comment]
The link works now but I get a security exception that the link is not secure. Accepting the risk goes to the destination

**Comment by poeti8** [comment]
You should disable the SSL for your domain. I'll work to add #18 feature soon.
