### ISSUE TITLE
Can't change the url or delete the domain off the main site 

### ISSUE THREAD

**Issue by Dragonblitz10** [thedevs-network/kutt#224]
It says it has changed but uses the old url and reloading the page changes it back once I got an internal server error

**Comment by poeti8** [comment]
Are you talking about setting a custom domain? Can you send the values you're trying to set here or to support@kutt.com so I can investigate.

**Comment by Dragonblitz10** [comment]
I emailed support@kutt.com all the details but the issue resolved itself might have been a database issue

**Comment by poeti8** [comment]
Actually I found the issue. Updating the domain works but user has been cached so it's returning old data. I need to invalidate the cache to fix this issue.
