### ISSUE TITLE
Internal Server Error on getting URL stats

### ISSUE THREAD

**Issue by agusmasu** [thedevs-network/kutt#225]
I’ve been using Kutt for a time now. Right now I’m experiencing some troubles when accesing to the following URL:

https://kutt.it/api/url/stats

I am performing a GET request to this URL with the id as a query parameter. An example of the full URL Is https://kutt.it/api/url/stats?id=q7x4bF
I was wondering if you could fix this error or, otherwise, let me know so I can take action on this problem.

Right now, when I make this request, with my API Key in the correct header, what I get is a HTML document that only displays “Internal Server Error”. Exactly, the HTML Response is the following:

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
</head>

<body>
    <pre>Internal Server Error</pre>
</body>

</html>

I wonder if you could help me.

Thank you very much.

**Comment by abhijithvijayan** [comment]
Kutt.it is down

**Comment by abhijithvijayan** [comment]
![Screenshot from 2019-11-04 20-19-38](https://user-images.githubusercontent.com/34790378/68130007-9f78e180-ff40-11e9-9744-cdc6bd5c14d6.png)

**Comment by poeti8** [comment]
This should be fixed, I have moved to a new server and implemented queue system to lower the database requests.
