### ISSUE TITLE
post api request to /app/url/deleteurl does not seem to work

### ISSUE THREAD

**Issue by ucphinni** [thedevs-network/kutt#227]
using python 3.7 windows.

Used a somewhat modified (was not working) kutt-cli python app to delete
Also wrote my own using aiohttp (client calls) for posting the url.

Both generate the error "Couldn't delete the short link." with error 400 (Malformed query)

Here is the method call. name is 'someting', not 'https://kutt.it/something

    async def deleteurl(self,name):
        async with aiohttp.ClientSession(headers=self.headers) as client:
            data = {}
            data['id']= name
            async with client.post('https://kutt.it/api/url/deleteurl',data=data) as resp:
                return await resp.text()

This works within the interface of kutt.it when logged in. 

The get list and the submit work as expected.

**Comment by ucphinni** [comment]
Thank you for fixing this. Has this change been pushed out to the kutt.it server?

**Comment by poeti8** [comment]
Yes, still have issues?

**Comment by ucphinni** [comment]
Yes. Here is the a small but complete version

    import aiohttp
    import asyncio

    class KuttItShortner:
        def __init__(self,apikey):
            headers = {}
            headers['X-API-Key'] = apikey
            self.headers = headers
        async def deleteurl(self,name):
            async with aiohttp.ClientSession(headers=self.headers) as client:
                data = {}
                data['id']= name
                async with client.post('https://kutt.it/api/url/deleteurl',data=data) as resp:
                    return await resp.text()

    async def start():
        urlsh = KuttItShortner('<<SECRET KEY>>')
        print(await urlsh.deleteurl('friend_handup'))

    loop = asyncio.get_event_loop()
    loop.run_until_complete(start())
    loop.run_forever()

Here is the result

     {"error":"Couldn't delete the short link."}

**Comment by poeti8** [comment]
Are you using a custom domain? If so should include in the data. And make sure you're sending JSON.

**Comment by ucphinni** [comment]
updated previous comment.
added optional domain='kutt.it' 
changed to send as json (had this before but overlooked when doing this post, sorry)

Still no bueno.

**Comment by poeti8** [comment]
Request body should be like this:

```
// With domain
{ id: "2KsF7", domain: "custom.com" }

// Without domain
{ id: "2KsF7" }
```

Try with postman or cURL.

**Comment by ucphinni** [comment]
on a small windows box. when I get access to a Linux machine will try the curl. I did update it and now got a different error. removed custom domain.  Comment has been update.

**Comment by poeti8** [comment]
Not sure how Python works but I think you should pass object as request body and set header content type to `application/json`

**Comment by ucphinni** [comment]
{"message":"Short link deleted successfully"}

Problem was on my side.  My test was not valid.  Thank you for your help.  I will send an updated version as a comment.

**Comment by ucphinni** [comment]
For anyone who is searching, this python object works for bear minimum functionality with aiohttp. (The one in the github no longer works.)

    import aiohttp, asyncio

    class KuttItShortner:
        baseurl='https://kutt.it'

        def __init__(self,apikey,client = None):
            self.headers,self.client = {'X-API-Key':apikey}, client

        async def deleteurl(self,_id,client = None, domain = None):
            data={'id':_id} if domain is None else {'id':_id,'domain':domain}

            return await self._cli_post(self.baseurl+'/api/url/deleteurl',client,data)

        async def submiturl(self,_id,target,client = None, reuse = False,password=None):
            data={'customurl':_id,'target':target,'reuse':reuse}
            if password is not None:
                data.update({'password':password})

            return await self._cli_post(self.baseurl+'/api/url/submit',client,data)

        async def _cli_post(self,url,cli,data):
            async def _cli_post2(url,client,hdrs,data):
                async with client.post(url,headers= hdrs,json=data) as resp:
                    return await resp.json()

            if cli is None or self.client is None:
                async with aiohttp.ClientSession() as client:
                    return await _cli_post2(url,client,self.headers,data)

            return await _cli_post2(url,self.client,self.headers,data)


    async def start():
        urlsh = KuttItShortner('<<SECRET API KEY>>')
        print(await urlsh.deleteurl('<<a new id>>))
        print(await urlsh.submiturl('<<a new id>>','http://google.com'))
    loop = asyncio.get_event_loop()
    loop.run_until_complete(start())
    loop.run_forever()
