### ISSUE TITLE
Down

### ISSUE THREAD

**Issue by stefanes** [thedevs-network/kutt#228]
Unable to reach shortened URLs.

![Screenshot_20191103-184808_Firefox](https://user-images.githubusercontent.com/5484354/68089592-bd741280-fe6a-11e9-872d-3c6f90043971.jpg)

**Comment by bvdlingen** [comment]
Same here.

**Comment by Fabian9799** [comment]
Same here

**Comment by bvdlingen** [comment]
Looks like the issue has been solved.

**Comment by poeti8** [comment]
Sorry guys, Kutt had hundred thousands of requests at the same time, I optimized it for now and will investigate further more to push changes to the repo as well soon. I'm going to close this issue since this is resolved, however you can follow performance improvements in #229
