### ISSUE TITLE
Feature Request: Multiple custom domain

### ISSUE THREAD

**Issue by lapphan** [thedevs-network/kutt#230]
I want the ability to add more than one custom domain within an Kutt.it website account.

**Comment by yakovmanshin** [comment]
It’d also be great to be able to link multiple domain names to a single *self-hosted* Kutt.it installation.

**Comment by TheUltimateC0der** [comment]
That is why I am not using it currently. Would love to see that feature.

**Comment by aidik** [comment]
@yakovmanshin I believe you can do that. You will just need a separate user for each custom domain.

**Comment by aidik** [comment]
Also, I did a little bit of digging and it seems to me, that the support can be enabled pretty easily. 

[The unique constraint](https://github.com/thedevs-network/kutt/blob/develop/server/models/domain.ts#L27) can be omitted and [this `if`](https://github.com/thedevs-network/kutt/blob/develop/client/components/Settings/SettingsDomain.tsx#L81) can be altered to allow the addition of multiple domains

**Comment by hugomd** [comment]
I've opened a PR for this #317. If you're running it with node you can check out the branch locally to take it for a spin:

```bash
git fetch origin pull/317/head:feature/multiple-custom-domains
git checkout feature/multiple-custom-domains
npm run migrate
npm start
```

**Comment by poeti8** [comment]
Thank you @hugomd for the PR. It's not merged into Kutt however I'm going to remove the functionality from kutt.it website and keep the free version limited for now.
