### ISSUE TITLE
Missing .env inside docker-compose

### ISSUE THREAD

**Issue by 88plug** [thedevs-network/kutt#231]
git clone https://github.com/thedevs-network/kutt.git ;  cd kutt 
docker-compose up
ERROR: Couldn't find env file: /home/testuser/kutt/.env

Seems you forgot to publish the .env!

**Comment by vlude** [comment]
You need to rename the .example env en fill the open variables

**Comment by poeti8** [comment]
Some people just don't read a 4 lines instruction.
