### ISSUE TITLE
docker-compose first run error

### ISSUE THREAD

**Issue by 88plug** [thedevs-network/kutt#232]
kutt        | /usr/src/app/node_modules/passport-jwt/lib/strategy.js:45
kutt        |         throw new TypeError('JwtStrategy requires a secret or key');
kutt        |         ^
kutt        | 
kutt        | TypeError: JwtStrategy requires a secret or key
kutt        |     at new JwtStrategy (/usr/src/app/node_modules/passport-jwt/lib/strategy.js:45:15)
kutt        |     at Object.<anonymous> (/usr/src/app/production-server/passport.js:16:24)
kutt        |     at Module._compile (internal/modules/cjs/loader.js:956:30)
kutt        |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
kutt        |     at Module.load (internal/modules/cjs/loader.js:812:32)
kutt        |     at Function.Module._load (internal/modules/cjs/loader.js:724:14)
kutt        |     at Module.require (internal/modules/cjs/loader.js:849:19)
kutt        |     at require (internal/modules/cjs/helpers.js:74:18)
kutt        |     at Object.<anonymous> (/usr/src/app/production-server/server.js:29:1)
kutt        |     at Module._compile (internal/modules/cjs/loader.js:956:30)
kutt        |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
kutt        |     at Module.load (internal/modules/cjs/loader.js:812:32)
kutt        |     at Function.Module._load (internal/modules/cjs/loader.js:724:14)
kutt        |     at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
kutt        |     at internal/main/run_main_module.js:17:11
kutt        | npm ERR! code ELIFECYCLE
kutt        | npm ERR! errno 1
kutt        | npm ERR! kutt@2.1.5 start: `NODE_ENV=production node production-server/server.js`
kutt        | npm ERR! Exit status 1
kutt        | npm ERR! 
kutt        | npm ERR! Failed at the kutt@2.1.5 start script.
kutt        | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
kutt        | 
kutt        | npm ERR! A complete log of this run can be found in:
kutt        | npm ERR!     /root/.npm/_logs/2019-11-15T09_52_10_451Z-debug.log
kutt exited with code 1

**Comment by poeti8** [comment]
Fill .env file.
