### ISSUE TITLE
Generating short URL problem

### ISSUE THREAD

**Issue by V1TA5** [thedevs-network/kutt#237]
I cant generate short utls if im not logged in (works if iam)
I past the url (e.g. https://www.heise.de/newsticker/ ) and click on submit. 
The "wating circle thingy" appears and nothing happens.

**Comment by V1TA5** [comment]
THis is the "google part" of my .env
# Google Cloud API to prevent from users from submitting malware URLs.
# Get it from https://developers.google.com/safe-browsing/v4/get-started
GOOGLE_SAFE_BROWSING_KEY=

# Google Analytics tracking ID for universal analytics.
# Example: UA-XXXX-XX
GOOGLE_ANALYTICS=
GOOGLE_ANALYTICS_UNIVERSAL=

# Google Analytics tracking ID for universal analytics
# This one is used for links
# GOOGLE_ANALYRICS_UNIVERSAL=

Maybe it gets stuck if im not filling them out but then again. Why should it work if im logged in?

**Comment by poeti8** [comment]
I think you're missing reCAPTCHA config

**Comment by V1TA5** [comment]
Ah, ok. So it doesnt work without sending data to 3rd parties.
So ive to use something else.
Thank you. :)
