### ISSUE TITLE
Password not working for custom domain links

### ISSUE THREAD

**Issue by joaoramos** [thedevs-network/kutt#238]
Passwords seem to be prompted when visiting default generated links, but not when visiting custom links from custom domains. I would expect to be prompted for a password for both cases, but only one is working.

**Comment by poeti8** [comment]
Can you explain more? I'm trying both normal links and links with custom URLs and I see the password page. Are you using a custom domain?

**Comment by joaoramos** [comment]
Yes, I'm using a custom domain with a custom link. I just updated the title and description of the issue to be more explicit.

**Comment by abhijithvijayan** [comment]
The `goToLink()` lack comments which makes it confusing at certain login.

I presume it is where the issue is.

**Comment by abhijithvijayan** [comment]
@joaoramos could you attach the links that shows this behaviour?

**Comment by joaoramos** [comment]
@abhijithvijayan The problem has already been solved 👍
