### ISSUE TITLE
How better does performance improver after migrationg for neo4j to psql

### ISSUE THREAD

**Issue by tim-hub** [thedevs-network/kutt#241]
https://github.com/thedevs-network/kutt/blob/develop/MIGRATION.md

Because our company currently use neo4j as db in production, we have some performance issues either.

I really would like to know how much improvement after migration.

like 100%? 20%?

do not need to be accurate, just a rough number.

Regards

**Comment by poeti8** [comment]
Using Postgres alone I'd say at least x2 better performance. With Neo4j also had bottlenecks regarding server resources and maintenance. 

I've also changed how I store and process data in v2 and I believe v2 is at least 10 times faster and also way more stable.

**Comment by tim-hub** [comment]
thanks, 

Graph is great, but I got a feeling, most of work can be handled in RDBMS in a faster way.
