### ISSUE TITLE
Case-sensitivity should not be required

### ISSUE THREAD

**Issue by dammonburden** [thedevs-network/kutt#242]
Working with the tool today and it seems to be case sensitive. Can there be an option to disable?

**Comment by dammonburden** [comment]
This also means we can easily accidentally create duplicate entries if not searched first.

**Comment by poeti8** [comment]
Sorry it's not possible at the moment.

**Comment by kigali** [comment]
Is this still not possible to disable the case-sensitive ?

**Comment by yodaluca23** [comment]
Bump, think this would be a really great option.

**Comment by ymhcanada** [comment]
Agreed. URLs are typed by humans on phones, in emails, on printed materials. Case sensitivity is an implementation detail that leaks into user experience in the worst way: a link works when copy-pasted but breaks when typed. Case sensitivity has no real-world benefit. iOS autocorrect sometimes capitalizes characters mid-URL.

For now, I have to use a Cloudflare transform rule to address this issue...

<img width="801" height="443" alt="Image" src="https://github.com/user-attachments/assets/6768fdd7-94be-47c1-8ece-588b6e428d2b" />

Case study: Dub.co recognized this and made links case-insensitive by default in 2024
https://dub.co/changelog/case-insensitive-links

Quote:
> Short links on Dub are now case-insensitive by default.
> 
> This means that if you have a short link d.to/GitHub, you can now access it via d.to/Github or d.to/github – and the click events will be aggregated under the lowercase version of the link.
> 
> This will help prevent broken links when users accidentally type the wrong case.
