### ISSUE TITLE
Your Domain (kutt.it) is blocked by Spamhaus DBL

### ISSUE THREAD

**Issue by CMiksche** [thedevs-network/kutt#251]
I use a firewall which uses the Spamhaus Domain Block List (DBL) and i cloudn't access kutt.it because it is listed there.

See https://www.spamhaus.org/query/domain/kutt.it

I think Spamhaus DBL is quite a popular project, so you should probably remove your domain from there.
Also, you maybe are interested to use a service such as https://www.blacklistmaster.com/ to get notified if this domain is blacklisted somewhere ...

**Comment by poeti8** [comment]
Thanks for the notice, I'll try to send a false positive report.

**Comment by poeti8** [comment]
I contacted them and now we're removed from their list. Thanks.
