### ISSUE TITLE
Can't reuse custom URL

### ISSUE THREAD

**Issue by Couto** [thedevs-network/kutt#253]
I'm using a custom domain.
I had a URL with a custom name, which I deleted.

Right after, I tried to create the same link with the same custom name but I got a message saying "Custom URL is already in use."

Example:

1. Create an URL like: https://customdoma.in/gh and set it to point it to https://github.com
2. Delete that URL 
3. Repeat step 1

**Comment by poeti8** [comment]
I think it's a caching issue. Will investigate.

**Comment by abhijithvijayan** [comment]
This is been around for over a month now. I thought it was some issue with deletion from database or something.

**Comment by poeti8** [comment]
This should be fixed now.
