### ISSUE TITLE
Request failed with status code 400

### ISSUE THREAD

**Issue by mzch** [thedevs-network/kutt#258]
I set up Kutt and tried to shorten URL, but Kutt responded `Request failed with status code 400`
Anyone can help me?

**Comment by mzch** [comment]
Well, Kutt doesn't pass RECAPTCHA keys to recaptcha api correctly.

<img width="555" alt="ScreenShot 2019-12-30 8 43 08" src="https://user-images.githubusercontent.com/621178/71564243-bb33da80-2ae0-11ea-813b-bdf63d5cffbf.png">

<img width="724" alt="ScreenShot 2019-12-30 8 43 56" src="https://user-images.githubusercontent.com/621178/71564244-bff88e80-2ae0-11ea-9c5e-21d1c138897d.png">

**Comment by mzch** [comment]
Both Invisible v2 keys and v3 keys don't work.

**Comment by poeti8** [comment]
Seems like your config is wrong. Make sure site key and private key both are in place.

**Comment by mzch** [comment]
Is it mistake only to set `RECAPTCHA_SITE_KEY=site_key` and `RECAPTCHA_SECRET_KEY=secret_key` in .env?

**Comment by poeti8** [comment]
That's correct those 2 should be configured.

**Comment by mzch** [comment]
But both v3 keys and invisible v2 keys makes 400 error...

**Comment by poeti8** [comment]
The error in image clearly says it's missing the key. You can also add it directly to the code for now to test (`ReCaptcha.js`)

**Comment by mzch** [comment]
I put site key in ReCapcha.js and secret key in authController.ts directly but the result is same.

**Comment by mzch** [comment]
I tried to shorten URLs by using node 10.x and 12.x, but kutt responds 400 error.

<img width="554" alt="ScreenShot 2020-01-01 5 37 51" src="https://user-images.githubusercontent.com/621178/71633702-2bfe0280-2c59-11ea-88a7-cfc1a0ce3aaf.png">

**Comment by mzch** [comment]
Hi, I made a mistake about Google Safe Browsing API settings.
Sorry, this is fixed. Thanks!
