### ISSUE TITLE
Redirect not working for custom domains

### ISSUE THREAD

**Issue by k-allika** [thedevs-network/kutt#263]
URL redirection worked well for my custom domain for a couple of months, but when I checked now none of the links work. I checked the A record and it's fine. I get the following error when I click any of the links:
This site can’t be reached
link.datascience.eu.org’s server IP address could not be found.

![image](https://user-images.githubusercontent.com/31384629/71891448-bae4b080-316c-11ea-8711-d0f7f800c933.png)
![image](https://user-images.githubusercontent.com/31384629/71891510-d354cb00-316c-11ea-8b50-7572c55c1fac.png)

**Comment by poeti8** [comment]
When I check  the IP of`link.datascience.eu.org` I get no response because it's not set. `link` is a subdomain and I think you should use a CNAME record instead.

**Comment by k-allika** [comment]
Thank you very much for your response. I am unable to use CNAME record
instead because it requires a "fully qualified domain name" per Namecheap
and is not accepting the IP address there. I have the domain
datascience.eu.org at Namecheap. I added the following A record to the host
"link" as advised by https://kutt.it/settings page

[image: image.png]
But it doesn't seem to work. Am I using the correct IP address?

Also, these settings worked earlier for months. They stopped working
recently and when I checked Kutt.it settings, I noticed there was a change
in A record IP address. I updated the A record in Namecheap but it's still
not working. I wonder if something is wrong with the IP address?

Please advise.

Regards,
Krish

**Comment by poeti8** [comment]
If your search `link.datascience.eu.org` in an IP info checker website like https://ipinfo.info/html/ip_checker.php you get no results. This means domain is not configured properly.

**Comment by k-allika** [comment]
It seems that way for some reason. I'll get in touch with Namecheap for the
reason. Thanks.

**Comment by k-allika** [comment]
The issue was not with Kutt.it but with Namecheap DNS. After several conversations with their technical team, they have confirmed that they have an ongoing issue with **A records** in their DNS system. They were unable to resolve it so I moved my domain to another registrar and everything worked fine. I am therefore closing this issue. Thank you again for your prompt responses.
