### ISSUE TITLE
qr code missing?

### ISSUE THREAD

**Issue by abhijithvijayan** [thedevs-network/kutt#268]
![Screenshot from 2020-01-29 06-44-31](https://user-images.githubusercontent.com/34790378/73319601-e423c880-4262-11ea-8448-5ec080629c0e.png)

There is no QR Code or even the information about the long url

**Comment by poeti8** [comment]
It's now in the table only.

**Comment by abhijithvijayan** [comment]
So not available for non logged in users.

That's too bad.
