### ISSUE TITLE
Inacurate stats.

### ISSUE THREAD

**Issue by poeti8** [thedevs-network/kutt#27]
Stats are not accurate and they usually get multiplied due to way they're being retrieved from database.

**Comment by scottybo** [comment]
Any progress on this one?

**Comment by poeti8** [comment]
@scottybo Have you encountered any problem? I did some fixes a while ago.

**Comment by scottybo** [comment]
Ah, no - I was checking on the status of this as part of due diligence when comparing packages, I've not actually installed it

**Comment by poeti8** [comment]
I have done some improvements and I haven't seen this issue to happen any more. Closing the issue.

**Comment by henndawg** [comment]
Yeah it works fine for me. 

ironic spelling correction= *inaccurate
