### ISSUE TITLE
My account has been hacked somehow

### ISSUE THREAD

**Issue by shiebenaderet** [thedevs-network/kutt#270]
I had some strange things going on with my domain, nw.school, where it was pointing to strange Russian sites last week. Now my password isn't working and I can't reset it. Help?

**Comment by poeti8** [comment]
@shiebenaderet Please first update you DNS settings to point away from Kutt and then send your info to support@kutt.it and I'll be in touch.

**Comment by shiebenaderet** [comment]
Ok

-
Shie

________________________________

**Comment by joseftogo** [comment]
Same.
https://github.com/thedevs-network/kutt/issues/271

**Comment by poeti8** [comment]
As mentioned in #271 we had 2 IPs and forgot the old. Please change to the new IP in settings, we will send emails to the users shortly.

**Comment by shiebenaderet** [comment]
Question so I can confirm: What is the correct IP?

-
Shie

________________________________

**Comment by poeti8** [comment]
The one in settings page.
