### ISSUE TITLE
Hacked IP address?

### ISSUE THREAD

**Issue by joseftogo** [thedevs-network/kutt#271]
Hello,

when I set up my custom domain I was told to set up an A-record to 164.132.153.221.
The service worked fine but your IP address was hacked or even worse you sold to someone and now is the IP a random Russian Minecraft server and trading site (mmage.ru or enter 164.132.153.221).

I checked the dashboard and the A record is now a different address (192.64.116.170).

If you have issues to stay at one IP just use a CNAME record but changing the IP address without any notification is just not acceptable. I appreciate your development but it is impossible to use it under this condition.

**Comment by poeti8** [comment]
Sorry we forgot to pay for our old server, we'll make sure to not let this happen again.
