### ISSUE TITLE
Custom Shortlinks not Forwarding

### ISSUE THREAD

**Issue by shiebenaderet** [thedevs-network/kutt#272]
I have my domain set up with the correct IP address for the A record I believe:

![image](https://user-images.githubusercontent.com/2940433/73551942-30eed700-43fc-11ea-92c1-8c097d5ff4f0.png)

[192.64.116.170]

My pre-existing shortlinks that had been working until recently no longer forward. I get a 502 error. I have tried generating new links and they, too, are not forwarding correctly. 

More details:
I use Google Hosting and have DNSSEC set to disabled
The domain in question is for my school - nw.school - and entering that address does redirect to the default homepage:

![image](https://user-images.githubusercontent.com/2940433/73552395-02bdc700-43fd-11ea-91e9-08a70ab3769e.png)

Any help would be greatly appreciated. Thanks!

**Comment by poeti8** [comment]
Just pushed a fix. Please try now.

**Comment by shiebenaderet** [comment]
It's working! Thank you.
