### ISSUE TITLE
How to ensure Kutt process starts on server start?

### ISSUE THREAD

**Issue by kmanojkumar** [thedevs-network/kutt#273]
I am trying to setup Kutt as a daemon process. I have tried using **[forever](https://www.npmjs.com/package/forever)**. But, it isn't persistent after server restart. 

`forever start /production-server/server.js` after navigating to the app location helps me start the server and exit the server session. 

But, when I am trying to do the same via `crontab -e` the process fails to access the environment variables. They seem to be _undefined_. Tried it with both root and non-root user.

Tried pm2 as well. It didn't work. 

Any recommendation?

**Comment by poeti8** [comment]
I use `pm2`. Create and fill a `.env` file in the root and set `NODE_ENV=production` in it. Make sure you have install dependencies and did `npm run build`, then you can do `pm2 start production-server/server.js`
