### ISSUE TITLE
bash command line tool for kutt broken link

### ISSUE THREAD

**Issue by anntnzrb** [thedevs-network/kutt#274]
this website [0x0.st](https://0x0.st/) holds files/shortens urls temporary and can be easily summoned via the terminal with [curl](https://github.com/curl/curl), i was looking for way of shortening `kutt` just like this...

the answer was probably in [Bash: Simple command line program for Kutt](https://github.com/thedevs-network/kutt#3rd-party-packages) but the link seems to be broken.

**Comment by trgwii** [comment]
The kutt-bash implementation was lost #312, but you can run one of the other command-line tools from bash or write your own.
