### ISSUE TITLE
Reset fffutu.re Links!

### ISSUE THREAD

**Issue by carl-egge** [thedevs-network/kutt#277]
Hi there,
From what I know you guys are the programmers and hosts of "https://fffutu.re/" (Kutt.it)
I have a really big wish. Could you please make it possible to edit the Shortlinks one has created without having to delete them and setting them new. (When you do this you lose all your Statistics and Stuff)
Would be great if one could just reset the Linkdestination of a fffutu.re link.
Thanks!!

**Comment by poeti8** [comment]
Yes, we're working on this feature to be added to Kutt soon. Related to #79
