### ISSUE TITLE
Can't run Kutt with docker. Is docker configuration and documentation correct?

### ISSUE THREAD

**Issue by tucaz** [thedevs-network/kutt#281]
Hi!

I have been trying to install Kutt with docker, but didn't get lucky. I also reviewed all other issues about installation and docker and it seems like none touch this subject.

- I have edited my `.env` file and added the same user/password as specified in `docker-compose.yml` since the data there will be used to bring up pgsql and redis images

When I do `docker-compose up` it runs the build process, but fails because migrations can't run at the build time since the pgsql image is not yet available.

Are the setup instructions correct? 

To me it sounds like they were built with a local postgresql in mind or the migrations were added as an afterthought and not taken into account on the build process.

Any ideas?

**Comment by poeti8** [comment]
You're right, I just added migrations yesterday and forgot about Docker. I can take a look to be sure it's running after Postgres is ready, but PRs are welcome as well.

**Comment by tucaz** [comment]
Thanks @poeti8 for the feedback. I thought about trying to fix it through a PR but I wasn’t sure if it was really a bug. 

Since I’m not very familiar with packing a project into docker I didn’t want to spend the time unless it was a real bug and not just ignorance on my part. 

Also, the knexfile is not reading the server and port from the environment file.
