### ISSUE TITLE
How to change port when port 3000 is already in use?

### ISSUE THREAD

**Issue by brownsugar** [thedevs-network/kutt#285]
I'm running Kutt by Docker, if I left the default port setting, I will get this error:
```
Error starting userland proxy: listen tcp 0.0.0.0:3000: bind: address already in use
```

So I try to change the kutt ports to `"3001:3000"` in `docker-compose.yml`, and `PORT=3001` in .env file, then it seems working:
![image](https://user-images.githubusercontent.com/2935980/76002871-30d58000-5f42-11ea-891c-548db7e11596.png)

But I cannot access the app in browser by url http://{DEFAULT_DOMAIN}:3001 now, I'll get `ERR_CONNECTION_TIMED_OUT` error, did I miss any setting?

**Comment by lmiemus** [comment]
The way you edited docker-compose.yml is essentially just changing the port that will be mapped to the container's service, which should still run at port 3000 according to your specification.

Solution: change PORT value in .env file back to 3000.

**Comment by cdalexndr** [comment]
Alternate solution: use `"3001:3001"` in `docker-compose.yml`
