### ISSUE TITLE
Publish docker hub 

### ISSUE THREAD

**Issue by cdalexndr** [thedevs-network/kutt#289]
It would be nice to publish the docker image on [DockerHub](https://hub.docker.com/search?q=Kutt&type=image) of easy integration without building.

**Comment by andresmazzo** [comment]
Yeah! It simplifies deployment :pray:

**Comment by Moehrenbaum** [comment]
What about https://hub.docker.com/r/dasmeta/kutt ?

There's no description on how to run the image, nor whatelse is needed.

**Comment by poeti8** [comment]
I mage an official image, find it at https://github.com/thedevs-network/kutt#docker
