### ISSUE TITLE
Protect site from others

### ISSUE THREAD

**Issue by JonasOelke** [thedevs-network/kutt#290]
Hey Everyone! 

nice link shortener and props to your great design! 

I had some trouble installing it using docker, but after a couple hours I got it. 
My Problem is now that I can not see a way to protect the site that others can not register. 
Shouldn't be the first person registering also be an admin with more privileges to restrict access to the page? Or do I have to use .htaccess or something like that to make sure that no-one else can use my Kutt.it instance? 

And I am wondering why I should point a custom domain to the Kutt.it IP 192.64.116.170 ? It though I host Kutt.it on my own server so I am in control of everything it does?!

**Comment by fredleger** [comment]
+1 for this one. We found the project very interesting and promising but a bit discouraged to deploy it without way to restrict users to register since it uses our google apis and will end up to increase in our bills if this used widely. Any thoughts / plan about that ?

Ready to help if there is a clear plan

**Comment by poeti8** [comment]
I have plans to add the ability to make the service private(related #34), as a workaround you can use something like NGINX to add basic auth to protect login page and API from others.

>And I am wondering why I should point a custom domain to the Kutt.it IP 192.64.116.170 ? It though I host Kutt.it on my own server so I am in control of everything it does?!

It's just hardcoded in the settings page, you should use your server's IP address instead.

**Comment by NX211** [comment]
+1 This is the only missing feature of kutt that I really would love to see

**Comment by poeti8** [comment]
See #210
