### ISSUE TITLE
May I know where is the URL to login to admin dashboard?

### ISSUE THREAD

**Issue by airwavesmi** [thedevs-network/kutt#291]
I had setup the ADMIN_EMAILS in .env and successfully run kutt url shortener in my vps. However, I wonder where is the URL to login to admin dashboard? Eg. like https://example.com/admin .... and I try to login with admin email from the login/sign up page. But I don't have clue on what is the admin password since there is no mention to set admin password in.env file but only ADMIN_EMAILS. I also try forget password but the email will never arrive in admin email. It works for others user but not admin email. Thank you!

**Comment by airwavesmi** [comment]
I FIGURED it out ! Thank you.!

**Comment by Navan0** [comment]
can you tell us how it works?

**Comment by airwavesmi** [comment]
> can you tell us how it works?

Just make sure you had set the ADMIN_EMAILS, MAIL_HOST, MAIL_PORT, MAIL_SECURE, MAIL_USER, MAIL_FROM, MAIL_PASSWORD in your .env file and test your mail function is working first, then use the admin email that you set to sign up.

**Comment by Navan0** [comment]
i used gmail pop as email host but still getting 'an error occurd'

**Comment by airwavesmi** [comment]
> i used gmail pop as email host but still getting 'an error occurd'

May be you had enabled the two factor authentication of your google account which will trigger an error due to security problem, you can try to set the security to the lowest... The best way is to use your site email such as contact@example.com

**Comment by Likenttt** [comment]
Thanks
