### ISSUE TITLE
Register @ kutt.it not possible: error 500

### ISSUE THREAD

**Issue by danyball** [thedevs-network/kutt#292]
If i try to register at your website, a answer with http 500 occurred. Message "An error occurred."

**Comment by evgeniysevost** [comment]
Also if you download latest version and install in docker - same bug.

**Comment by poeti8** [comment]
The issue was I simply forgot to renew Kutt's email host plan. Should be fine now.

**Comment by bmcgonag** [comment]
So, it's trying to send an email for registration?

That's not a great or informative error.  Can you possibly add something more to it for the error message to be more clear.  I've been fighting with this for an hour.  Nothing in terminal running 'docker-compose up', nothing in browser console to indicate this was, or might be, the issue.
