### ISSUE TITLE
Not able to post link on twitter

### ISSUE THREAD

**Issue by shakesBeardZ** [thedevs-network/kutt#293]
Hello, 
this morning I tried to share a link on twitter but weirdly my twist was rejected by twitter, any idea why this is happening.
to reproduce:
1. create a link in kutt.it
2. put inside a twist 
3. try to publish twitter will refuse

**Comment by rosepac** [comment]
This has always happened to me. I think it is blocked on twitter.. For some reason. I guess, what spam? Or I do not know..

**Comment by poeti8** [comment]
When a domain is being posted constantly in Twitter, they block the link. This happened to Kutt a while ago and I've tried using their form to submit for a review but got no news, and strangely I can not find a single human on their support page to get in touch with.

**Comment by shakesBeardZ** [comment]
I think is banned because somebody used it in a scam or phishing 🤔

**Comment by locomot1f** [comment]
sooo.... is this service not safe to use??? starting to become suspicious.

**Comment by heyakyra** [comment]
> I've tried using their form to submit for a review but got no news

Here's that form if others want to try: https://help.twitter.com/forms/spam

Maybe we need a twitter campaign where we all post:
> Dear @Twitter, links from https://kutt.it are not harmful/malicious/spam, it's just a URL shortener, one of the few decent alternatives to proprietary ones. #FreeSoftware #LibreSoftware #OpenSource

**Comment by heyakyra** [comment]
The domain is also blocked in gmail for bulk emails and newsletters. I discovered this when trying to debug email issues with https://dkimvalidator.com/

which revealed the kutt.it link in https://www.spamhaus.org/dbl/removal/record/kutt.it which reads:

> The domain name kutt.it is listed on the Spamhaus DBL.
> 
> kutt.it has been listed in the DBL because it is a spammer abused URL shortener or redirector.
> 
> If you are an authoritative administrator of kutt.it and you have solved the abuse issues you can write to us at dbl-mmxviii@spamhaus.org from either abuse@kutt.it or postmaster@kutt.it and inform us of the actions you have taken to clean up the current spammer URLs. Please also inform us of any steps you have taken to prevent future abuse of your shortener/redirector. We will review your request and, at our discretion, remove the listing or respond to your request.

So presumably Twitter uses the same or a similar block list, and someone from @thedevs-network like @poeti8 @akash-joshi @trgwii or @MKRhere need to appeal it.

**Comment by MKRhere** [comment]
Thank you for the investigation, @heyakyra, we'll try and appeal it.

**Comment by poeti8** [comment]
Thank you @heyakyra, I contacted Spamhaus and our domain is now removed from their list.

**Comment by heyakyra** [comment]
Thanks! Sadly, still unable to post to Twitter. Not sure how else to investigate.

**Comment by shakesBeardZ** [comment]
Guys, you won't be able to post on twitter forever, so just forget about it, the main goal of me opening this issue is because I used my domain and I was getting extra visits from bots so I tried kutt.it and I wasn't even able to post on twitter with it.
