### ISSUE TITLE
Custom domain error

### ISSUE THREAD

**Issue by viharm** [thedevs-network/kutt#295]
The DNS A record (`192.64.116.170`) for custom domains points to `get.forkful.app`. This generates a security error in the browser.

Please could you confirm if this IP address is accurate, as I suspect that requests are being redirected to the wrong server.

**Comment by evancohen** [comment]
I'm also seeing this behavior on my custom domain.

**Comment by marwanareibi** [comment]
We're also not able to use our custom domain using kutt.it API. We received a 500 server error. Please advise!

**Comment by itsmetambui** [comment]
Hi. not sure it's the same error but I'm also seeing 500 server error when trying to create an url with
`POST /https://kutt.it/api/v2/links`
But able to fetch the links with
`GET /https://kutt.it/api/v2/links`

The form to create URL in https://kutt.it/ also return 500 server error.

**Comment by poeti8** [comment]
I updated default redirection for `192.64.116.170`.

>Hi. not sure it's the same error but I'm also seeing 500 server error when trying to create an url with

This is because of #169, it happened several times during last week, I'm trying to investigate.
