### ISSUE TITLE
Limit Short URL display to just the last part

### ISSUE THREAD

**Issue by Ruco** [thedevs-network/kutt#300]
It would be much easier to find the shortened URLs by only showing the last part of the url (custom address).
Since the first part will always be the same and that is now the prominent part of the Short URL displayed.

For instance instead of showing:
`kutt.it/custom1`
it would instead show just
`custom1` or `/custom1` 

Thank you for considering this.

**Comment by poeti8** [comment]
Users can use custom domains as well so we need to show the domain for those links in the table and showing the domain only those links could create a bit of inconsistency.

**Comment by Ruco** [comment]
Ok, but since there's only one custom domain to be selected. There's only two possibilities. And this could be simply fixed by adding for example an asterisks in one of the cases.

But as it is now. You cannot see the whole URL anyway. In many cases.

Another suggestion then. 
- Is to make this an optional setting.
- And/or instead of shortening and fading out the right side of the URL, do this on the left side instead.

That way, at least the relevant part of the URL is more likely to be shown.

**Comment by trgwii** [comment]
This is such a specific thing, I wouldn't want to clutter settings with stuff like this. Fading for the default domain is a much nicer idea imo.
