### ISSUE TITLE
Custom url always fails "You can't use this custom URL."

### ISSUE THREAD

**Issue by HarasimowiczKamil** [thedevs-network/kutt#303]
I use version: `v2.2.9` Simple short url works so api key is correct and app works. When I add the customurl parameter I get the answer:

```
{"error":"You can't use this custom URL."}
```
Of course, regardless of what I give in the `customurl`. Unless I use illegal characters then I have `{" error ":" Custom URL is not valid "}`

My request:

```
curl 'http://kutt.localhost/api/v2/links' \
  -H 'X-API-KEY: MY_API_KEY' -H 'Content-type: application/json' \
  -X POST \
  -d '{"target":"https:\/\/sometarget.com/abc","customurl":"abc1587629258","domain":"example.com"}'
```

Bug or I do something wrong?

**Comment by poeti8** [comment]
Please use the latest version which right now is `2.3.14`.

**Comment by heyakyra** [comment]
Getting `URL is not valid` for the following url: `https://tx.reel-scout.com/crew_directorylist.aspx?g=&key=&region=Dallas%20%2F%20Fort%20Worth area&subcat=817756,109,817757,817758,817759,114,116,190`
