### ISSUE TITLE
Docker compose is  not working

### ISSUE THREAD

**Issue by Navan0** [thedevs-network/kutt#305]
docker-compose up seems working but browser shows ERR_INVALID_REDIRECT
![Screenshot from 2020-04-27 03-00-30](https://user-images.githubusercontent.com/15803320/80320384-bd5e3980-8833-11ea-9b7c-20700b7bca61.png)

**Comment by minkichoe** [comment]
me too
http://localhost:3000/api/v2/health is OK, but main front page has error with ERR_INVALID_REDIRECT

**Comment by xnaas** [comment]
Funnily enough, I can browse to /home and it'll show the 404. From there I can hit Report and it'll take me to that page, but if I try to load /report directly: same issue:

> The site at http://localhost:3000/ has experienced a network protocol violation that cannot be repaired.

> The page you are trying to view cannot be shown because an error in the data transmission was detected.

**Comment by Akshay090** [comment]
> me too
> http://localhost:3000/api/v2/health is OK, but main front page has error with ERR_INVALID_REDIRECT

Exact same situation for me, I'm currently stuck at this step. 
I also faced issues starting up the project till this step, like i had to use dos2unix.exe on wait-for-it.sh as currently I'm working from windows system. Also change redit host to redis as in [this reply here](https://github.com/thedevs-network/kutt/issues/214#issuecomment-619070277).

**Comment by minkichoe** [comment]
It works when i change some chores like this.


my docker-compose.yml:

version: "3"

services:
  kutt:
    build: .
    container_name: kutt
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - redis
    env_file:
      - .env.production
    networks:
      - kutt-network
    restart: always

  redis:
    image: redis:alpine
    container_name: redis
    networks:.
      - kutt-network
    restart: always

  postgres:
    image: postgres:12-alpine
    container_name: postgres
    env_file:
      - .env.production
    ports:
      - 5432:5432
    networks:
      - kutt-network
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: always

  nginx:
    build: nginx
    ports:
      - 80:80
      - 443:443
    env_file:
      - .env.production
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    networks:
      - kutt-network
    restart: always
    depends_on:
      - kutt

  certbot:
    image: certbot/certbot
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - kutt-network
    

networks:
  kutt-network:
    driver: "bridge"

----

my Dockerfile:

FROM node:12-alpine

RUN apk add --update bash
# Setting working directory. 
WORKDIR /usr/src/app

# Installing dependencies
COPY package*.json ./
RUN npm install

# Copying source files
COPY . /usr/src/app

# Build files
RUN npm run build

# Running the app
ENTRYPOINT ["/usr/src/app/entrypoint.sh"]

----

my entrypoint.sh:

#!/bin/sh

if [ -z "$DB_HOST" ]
then
    echo "\$DB settings are empty"
else
    echo "Trying to db:$DB_PORT";
    until nc -z postgres $DB_PORT; do
        echo "DB is not ready, sleeping..."
        sleep 5
    done
fi

npm run build
npm start

exec "$@"

**Comment by poeti8** [comment]
The `DEFAULT_DOMAIN` environment variable should match the current domain otherwise it keeps redirecting to the default domain. For localhost please exactly use `DEFAULT_DOMAIN=localhost:3000`
