### ISSUE TITLE
When using docker-compose the localhost redirecting to https://%20localhost:3000/

### ISSUE THREAD

**Issue by Navan0** [thedevs-network/kutt#307]
When using docker-compose the localhost redirecting to https://%20localhost:3000/ on chrome browser but working fine with firefox

**Comment by dakotahp** [comment]
@Navan0 I had the same problem and figured it out. That decodes to https://“localhost:3000”/ so I looked in the .env file. Sure enough the example has quotes around it:

https://github.com/thedevs-network/kutt/blob/develop/.example.env#L8

Remove the quotes and see if that helps. In my case it still wanted to redirect so I actually changed it to my actual domain name. I think this example is setup for running locally as a test but it should be `whatever.com` (without the port), hence the redirect.

**Comment by trgwii** [comment]
@poeti8 we probably need to go through each of the ENV values and see if we can remove quotes from all.

**Comment by poeti8** [comment]
Removed quotes from the `.example.env` for clarity.
