### ISSUE TITLE
DEFAULT_DOMAIN property on .env file is not working

### ISSUE THREAD

**Issue by danieldourado** [thedevs-network/kutt#308]
I've already successfully installed and configured Kutt on my localhost. 
I am trying to install Kutt in a remote machine.

I set DEFAULT_DOMAIN property in .env
From:
```

# The domain that this website is on
DEFAULT_DOMAIN="localhost:8080"

```
To:
```

# The domain that this website is on
DEFAULT_DOMAIN="exampledomain.com:8080"

```
But the server always starts as "localhost:8080" and when I try to access exampledomain.com:8080 it redirects to "localhost:8080"
Any tips?
Thank you.

**Comment by poeti8** [comment]
Default domain is used to generate URLs. The app will always run in localhost. On your server you can use port 80 or use a proxy server like NGINX use your domain with other ports.
