### ISSUE TITLE
Custom domain without shorturl (too many redirects)

### ISSUE THREAD

**Issue by f3l1x** [thedevs-network/kutt#310]
Hi guys! Thanks for amazing product.

I've easily added my url `sulc.link` to kutt.it. Everythinkg works just fine. 

But when I open `sulc.link` domain without any other parts, it redirects me to `sulc.link/null` and shows too many redirects.

![image](https://user-images.githubusercontent.com/538058/80801068-91ccad80-8bab-11ea-9262-d2b45b49e529.png)

Is anything I can do about?

**Comment by pixl-8** [comment]
I have the same error.

**Comment by pixl-8** [comment]
I found a solution... You must create a short link with the alias /null that points to any page.

**Comment by f3l1x** [comment]
Great, it works. But is it the right solution for it?

**Comment by poeti8** [comment]
Did you set homepage or is it default?

**Comment by f3l1x** [comment]
If I set explicitly `sulc.link/null` it works well. In my case I redirect to https://kutt.it/, because I don't remember the name. :-D

**Comment by poeti8** [comment]
Reopening the issue to do some research in case if it is a bug.

**Comment by poeti8** [comment]
I can not reproduce it. Please let me know if you encounter this problem again (try deleting the domain and adding it again)

**Comment by rafenden** [comment]
The issue still exists, I tried recreating the custom domain on https://kutt.it/settings, but it didn't change a thing.

**Comment by diegopatinor** [comment]
I have the same error if I leave the Homepage, which is optional, empty.

![image](https://github.com/thedevs-network/kutt/assets/63062347/b8f8e8fa-6d2d-4000-a936-3a5b240817a6)
