### ISSUE TITLE
git-bash doesn't seem to exist

### ISSUE THREAD

**Issue by gotmax23** [thedevs-network/kutt#312]
The link to git-bash in the README results in a 404. I searched for it on duckduckgo and couldn't find it there either.

**Comment by trgwii** [comment]
@caltlgin the URL from #194 now seems broken, is it privatized?

**Comment by caltlgin** [comment]
Unfortunately I lost the code in my server migration :(

**Comment by trgwii** [comment]
@caltlgin Oh RIP, I guess we remove the link and you can open a new PR if you manage to get your data back.
