### ISSUE TITLE
SITE_NAME not working properly

### ISSUE THREAD

**Issue by AragurDEV** [thedevs-network/kutt#314]
When I load my page it work's fine for a split second.  
Test it yourself: https://clbrk.de/terms

Sorry I don't know how to describe this error properly...

**Comment by trgwii** [comment]
How exactly is this page set up? Did you make a fork or do any code changes?

**Comment by AragurDEV** [comment]
No I haven't made any modifications.

> I deployed it using docker-compose.

**Comment by poeti8** [comment]
Fixed.

**Comment by Aragur** [comment]
Same issue still happening...
