### ISSUE TITLE
Email reports

### ISSUE THREAD

**Issue by martinszy** [thedevs-network/kutt#323]
Hi, I'm using kutt.it and I would like to have a weekly report of usage of our shortened links delivered to out email inbox.

So it would be similar to the list of links in the logged in page, but it would be delivered via email, and it would have only those links that did have at least one click during the past week (or, I guess, customizable period) and list both the total clicks and the new clicks for the week. Clicking on each link could direct users to the public stats page described here #73 

I think this is useful to remind users of their links and to help them see the stats.

**Comment by trgwii** [comment]
This sounds pretty out-of-scope for Kutt, you can create your own email service that does this by having a scheduled task / cron job that gets the stats from the Kutt API and sends the email.
