### ISSUE TITLE
editing shortened link does not delete the original

### ISSUE THREAD

**Issue by realToadtoad** [thedevs-network/kutt#324]
By making a shortened URL and editing the short link, e.g from `kutt.it/test` to `kutt.it/test2`, both URLs function, but the original URL cannot be deleted or found in the list of created links. This is an issue, as editing a shortened URL to free up space for another, as would be done through deleting and making a new link, doesn't work, and leads to a sort of a "ghost" URL that cannot be edited or deleted.

**Comment by trgwii** [comment]
Can't reproduce, this might be a caching issue in your browser. Editing links on kutt.it and checking it with `curl` shows that the previous link url goes to 404
