### ISSUE TITLE
Map does not show clicks from China

### ISSUE THREAD

**Issue by C129H223N3O54** [thedevs-network/kutt#325]
Clicks are counted, but map does not show clicks from China. Also, clicks from Luxembourg are marked as France.

<img width="605" alt="Screen Shot 2020-06-04 at 22 50 45" src="https://user-images.githubusercontent.com/426493/83772466-fe106480-a6b5-11ea-96b6-37d4bcbf46df.png">

**Comment by MKRhere** [comment]
Likely a limitation of the MaxMind GeoIP database we're using for IP lookups; nothing Kutt can do to fix this.
