### ISSUE TITLE
Feature request: generate URLs from tokens in a spreadsheet

### ISSUE THREAD

**Issue by markcarver1984** [thedevs-network/kutt#326]
Hi, great tool! I'd like to use it to create survey response tokens on a research project. This is great for longitudinal projects where someone might change their email address over the years - I can use a unique ID in the link I send them so that I know who responded to my survey. Is there any way I can do this with Kutt using a spreadsheet?
For example:
Spreadsheet column has 100 response IDs
Kutt creates kutt.it/survey1, kutt.it/survey2, .... kutt.it/survey100. Each of which redirects to mysite.com/survey?token=ID1, mysite.com/survey?token=ID2,... mysite.com/survey?token=ID100.

Hoping you can help, thanks

Mark

**Comment by lapphan** [comment]
You can [Create a short link](https://docs.kutt.it/#tag/links/paths/~1links/post).

**Comment by trgwii** [comment]
This is something you would have to write your own client script to do, with which you could automatically loop over the rows in the spreadsheet and communicate with the Kutt API. You can consult the API docs or check the third party tools section for client libraries and more information.
