### ISSUE TITLE
Desktop site triggers security warning? 

### ISSUE THREAD

**Issue by GitAlexToTheGreek** [thedevs-network/kutt#328]
Hi,

Opening Kutt.it on mobile is fine, but via pc triggers a Trojan warning...

![87hSDKKFjo](https://user-images.githubusercontent.com/59787873/84322807-7b126280-ab2a-11ea-9061-6fe87b86930f.png)

Assuming it's a false positive but your thoughts would be appreciated...

Cheers, 
Alex

**Comment by poeti8** [comment]
I sent support an email to report false positive. Thank you.

**Comment by poeti8** [comment]
They replied that they have removed kutt.it from the blacklist now. @GitAlexToTheGreek Can you check now?
