### ISSUE TITLE
Possible to add to Dockerhub?

### ISSUE THREAD

**Issue by JoshuaMunoz** [thedevs-network/kutt#329]
I dunno if that's a thing or not - I see it can be run in a Docker container.

**Comment by xianx** [comment]
Yes I built docker image from the source and pushed to my docker hub. But official docker hub images should be added.

**Comment by botzill** [comment]
any plans on this one?

**Comment by poeti8** [comment]
I just added Kutt to the Docker hub: https://hub.docker.com/r/kutt/kutt. I'm not really familiar with Docker, so please let me know if this works as expected so I can add it to the readme.

**Comment by 8sd** [comment]
I tried it on my side, the docker image works so far I think. 
Thank you very much :+1: 

However, now I have a new issue see #357

**Comment by poeti8** [comment]
Thank you @botzill, I added tag recognition to the automatic builds. Will work on the reCaptcha issue.
