### ISSUE TITLE
how to get the UV of the short URL?

### ISSUE THREAD

**Issue by ohblue** [thedevs-network/kutt#33]
how to get the UV of the short URL?

**Comment by trgwii** [comment]
What's a UV?

**Comment by isayme** [comment]
@trgwii [Unique Visitor](https://en.wikipedia.org/wiki/Unique_user#Unique_visitor)

**Comment by trgwii** [comment]
I believe we only track visits at this time. We don't do browser fingerprinting or set cookies on shortened URL visits.

@poeti8 We can probably use this thread to discuss this feature and it's viability

**Comment by poeti8** [comment]
Yes we only track visits we do not store or use any kind of identification. Not sure which way is the most accurate one, so yeah let's discuss it here.

We can simply display the number of unique visitor beside total views.

**Comment by trgwii** [comment]
I guess IP could be used as a rudimentary unique visitor tracker.

I'm not really sure about what the direction of this project should be as far as tracking and fingerprinting goes (That'll have to be up to you Pouria). Tracking has a tendency to quickly become scary.
