### ISSUE TITLE
Uncaught (in promise)

### ISSUE THREAD

**Issue by NoverNobida** [thedevs-network/kutt#332]
I get this error in browser after `npm run dev` or `npm run build && npm start`, and the loading circle won't stop.

![image](https://user-images.githubusercontent.com/46912250/85578624-cb320e80-b66c-11ea-8b96-c5f437dac816.png)

![image](https://user-images.githubusercontent.com/46912250/85578796-ef8deb00-b66c-11ea-94f1-059f9ba0828b.png)

**Comment by shuat** [comment]
Having the same issue? Anyone else?

**Comment by shuat** [comment]
I solved this my switching from localhost to kutt.local and updated my host file
