### ISSUE TITLE
Data Migration from neo4j to postgre

### ISSUE THREAD

**Issue by xianx** [thedevs-network/kutt#334]
I am trying to migrate from v1 neo4j to v2 postgrsql.

If I export json or csv format from neo4j and import those json or csv into postgrsql will it work?

**Comment by vivekshah1801** [comment]
@xianx You can export the CSV for neo4j database than can do some manipulation (using pandas probably) to convert it in a suitable form for SQL.

after that, you can use any CSV to Db ingester.

**Comment by poeti8** [comment]
No you can't. The schema uses in v2 and how we track the stats is different from v1. Please read the migration guide.
