### ISSUE TITLE
Broken .env file

### ISSUE THREAD

**Issue by Vikram-T** [thedevs-network/kutt#336]
Using `docker-compose up` on the default .example.env file didn't work for me and runs into the error:
```events.js:292
kutt        |       throw er; // Unhandled 'error' event
kutt        |       ^
kutt        | 
kutt        | Error: Redis connection to "127.0.0.1":6379 failed - getaddrinfo ENOTFOUND "127.0.0.1"
kutt        |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)
kutt        | Emitted 'error' event on RedisClient instance at:
kutt        |     at RedisClient.on_error (/usr/src/app/node_modules/redis/index.js:406:14)
kutt        |     at Socket.<anonymous> (/usr/src/app/node_modules/redis/index.js:279:14)
kutt        |     at Socket.emit (events.js:315:20)
kutt        |     at Socket.EventEmitter.emit (domain.js:482:12)
kutt        |     at emitErrorNT (internal/streams/destroy.js:92:8)
kutt        |     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
kutt        |     at processTicksAndRejections (internal/process/task_queues.js:84:21) {
kutt        |   errno: 'ENOTFOUND',
kutt        |   code: 'ENOTFOUND',
kutt        |   syscall: 'getaddrinfo',
kutt        |   hostname: '"127.0.0.1"'
```

To solve this I had to change [line 28 in .example.env](https://github.com/thedevs-network/kutt/blob/eda3513dbef729182eba4b29a759c1727937ce22/.example.env#L28 ) from `REDIS_HOST="127.0.0.1"`to `REDIS_HOST=redis`

Additionally, I had to change [line 8](https://github.com/thedevs-network/kutt/blob/eda3513dbef729182eba4b29a759c1727937ce22/.example.env#L8) from `DEFAULT_DOMAIN="localhost:3000"` to `DEFAULT_DOMAIN=localhost:3000` for the browser to recognize the link.

Idk where to submit this since I've never contributed to open source before, but let me know if I should create a pull request fixing these issues.

**Comment by poeti8** [comment]
Well you were supposed to write values in .env file according to your environment.

**Comment by Vikram-T** [comment]
Yea but that isn't very clear from the docs. Telling someone to "fill it properly" is vague and isn't even included in the docker setup instructions. I also noticed that this error has been brought up before so I know I'm not the only one to get confused. Why not explain it more clearly?

**Comment by poeti8** [comment]
Added here now so people don't need fill host: https://github.com/thedevs-network/kutt/blob/develop/docker-compose.yml#L20
