### ISSUE TITLE
[Question] Make the service private

### ISSUE THREAD

**Issue by HannanAkbar** [thedevs-network/kutt#34]
Is it possible to run the service in private mode without giving access to the public?

**Comment by trgwii** [comment]
Add an IP-address on line 110 of server/server.js like so:
```js
// from:
  server.listen(port, err => {
// to:
  server.listen(port, '127.0.0.1', err => {
```

That will make it only listen for local connections

**Comment by HannanAkbar** [comment]
Ok. How to run privately (I.e. restrict public access, sign up, etc) instead of running locally.

**Comment by poeti8** [comment]
I had this idea before starting to code this, but didn't have the enough time to implement it. 
One dirty way I can think of right now that you can use, is that create a white list of emails and only allow them to signup/login, and only allow those guys to be able to shorten links. Should be trivial to do if you know JavaScript.

**Comment by trgwii** [comment]
I think a good idea would be to do it in the same style as Gitea, the first user gets admin rights, and can change settings for the entire instance (like global private mode on / off)

**Comment by NX211** [comment]
+1

**Comment by poeti8** [comment]
See #210
