### ISSUE TITLE
Deactivate Recaptcha

### ISSUE THREAD

**Issue by 8sd** [thedevs-network/kutt#357]
I'm about to set Kutt up on my website. 
I don't want to use recaptchas or analytics on this site.

How can I deactivate it?

In the `.env` file I set the values to `''` and empty-string but the site doesn't work. 
In the console it says:

```
Uncaught Error: Missing required parameters: sitekey
Uncaught (in promise) Error: No reCAPTCHA clients exist.
```

**Comment by 8sd** [comment]
I tested the newest version on the development branch (e5e219) but I still see the error `Uncaught (in promise) Error: No reCAPTCHA clients exist.` and I'm unable to submit queries.

**Comment by poeti8** [comment]
Pushed a fix please try again now.

**Comment by 8sd** [comment]
Awesome works now :+1:

**Comment by 8sd** [comment]
So locally it works fine.

With my current productive-setup, the index-page of `kutt` is shown but any request to the API returns a `401` error and an error-message `ReCaptcha is not valid. try again` appears.

I'm not sure if this is a recaptcha error, maybe this is due to an issue with the reverse-proxy I'm using?

Here is my nginx config for kutt:

```
server {
  include /etc/nginx/ssl.conf; # This is the stuff that is required for ssl

  server_name ~~~~;

  add_header X-Frame-Options SAMEORIGIN;
  location / {
    proxy_set_header X-Forwarded-Host $server_name;
    proxy_set_header Host $host;
    proxy_pass       http://localhost:3000;
  } 
}
```

**Comment by poeti8** [comment]
This error comes from validation on backend. Are you sure you're using the `latest` tag?

**Comment by 8sd** [comment]
I deleted all kutt images on my productive system and pulled the latest tag baucause I was not sure if I had the newest version...

**Comment by 8sd** [comment]
So today, I pulled the new docker-image v-`2.5.0` and the error (`reCAPTCHA is not valid. Try again.`) still appears...

The call to `POST: /api/v2/links` returns with a `401 Unauthorized`-error.

**Comment by poeti8** [comment]
So it does work locally but it does not work with Docker? Are you sure you're not passing any reCaptcha env variables?

**Comment by 8sd** [comment]
Good point, now it works.

In the `.env` file I had the setting `RECAPTCHA_SITE_KEY=''`, now I removed the line and it works.
