### ISSUE TITLE
Output QR code as an SVG

### ISSUE THREAD

**Issue by jayrsmith** [thedevs-network/kutt#359]
Hi, I was hoping to use Kutt but have run into an issue where the generated QR codes are too low quality for use in printed materials. If they were generated as an SVG that would be more useful.

Is there a way to set the QR code output as SVG rather than PNG?

**Comment by abhijithvijayan** [comment]
If you are looking for a 3rd party API(as a temporary solution), I recommend goqr.me)

https://api.qrserver.com/v1/create-qr-code/?size=150x150&format=svg&data=https://kutt.it

**Comment by Robbbb** [comment]
just a note, given that QR codes are pixel-perfect there is not really a quality difference between vector graphics and pixel graphics in this case. The issue can be the way it is up-sampled, but if you use nearest-neighbor it will scale beautifully.
https://www.photoshopessentials.com/basics/how-to-resize-pixel-art-in-photoshop/

**Comment by MKRhere** [comment]
@Robbbb is right; pixel graphics can be upscaled without losing quality. We may reconsider SVG at a later time, but closing issue to keep it manageable for now.
