### ISSUE TITLE
Change email

### ISSUE THREAD

**Issue by Hintsmth** [thedevs-network/kutt#362]
Hi there,
I wonder whether there is an opportunity to change email, that linked to the account? If no, will you add it? That would be great!

**Comment by poeti8** [comment]
I'll add the functionality soon. Meanwhile you can contact support@kutt.it and I'll change it for you.

**Comment by Hintsmth** [comment]
Fantastic! That's very cool. Thank you!

**Comment by poeti8** [comment]
This has been implemented now on version `v2.7.0`
