### ISSUE TITLE
Site flagged as malicious by Google Safe Browsing

### ISSUE THREAD

**Issue by jmbowman** [thedevs-network/kutt#372]
Between yesterday and today Firefox started blocking access to https://kutt.it due to https://transparencyreport.google.com/safe-browsing/search?url=https:%2F%2Fkutt.it%2F .

**Comment by forkbomb9** [comment]
Ooh, and then bit.ly and other shorteners should also be flagged! If some people use kutt to redirect to a (malicious) site, how can kutt check that? Reviewing every shortened URL?

**Comment by jmbowman** [comment]
May be worth getting in touch with them and asking if they have any standard recommendations for this.  Might be able to check target URLs against their "malicious sites" database, or even just ask if they have a standing exception clause for known URL shortener sites

**Comment by sae13** [comment]
how I can report as false alarm ?

**Comment by poeti8** [comment]
Requested a review. Please check again and let me know if fixed.

**Comment by forkbomb9** [comment]
No, still flagged...

**Comment by forkbomb9** [comment]
Looks like I found some interesting info [here](https://www.stopbadware.org/blacklisted-by-google).

There are two options:

1. Use the Google Webmaster Tools (if the only provider blocking the site is Google), but you need a Webmaster Tools account...
2. Request an independent review by StopBadware (which they say it's slower)

For #2, when I search for kutt.it on https://www.stopbadware.org/clearinghouse/search, nothing shows up. The search bar keeps spinning...

**Comment by sae13** [comment]
what if you add a new domain to site only not for redirection

**Comment by trgwii** [comment]
> May be worth getting in touch with them and asking if they have any standard recommendations for this. Might be able to check target URLs against their "malicious sites" database, or even just ask if they have a standing exception clause for known URL shortener sites

Kutt already is capable of using Google's "safe URL" blacklist to block bad URLs from being shortened, and I believe the kutt.it instance is already doing this ¯\_(ツ)_/¯

**Comment by sae13** [comment]
I dont think giving clients urls to google company for analysis is right thing to do, maybe some other more open service ...

**Comment by trgwii** [comment]
It supports it, but you don't have to enable it @sae13

**Comment by gautamkrishnar** [comment]
We need to fix this. It's really bad and some people might think https://kutt.it/ is actually a malicious site.

**Comment by poeti8** [comment]
Reviewed by Google and flagged as safe again. https://transparencyreport.google.com/safe-browsing/search?url=kutt.it&hl=en 

Let me know if you still encounter issues.
