### ISSUE TITLE
Error when create a shortlink

### ISSUE THREAD

**Issue by hanhgia** [thedevs-network/kutt#38]
Hi,

I got error when i try to create a shortlink, as below:

`Erroraxios.lib.core:createError in createError
Error
Request failed with status code 403
/Users/Victoria/dev/projects/shortener/kutt/node_modules/axios/lib/core/createError.js in createError at line 16:15
 * @param {Object} config The config.
 * @param {string} [code] The error code (for example, 'ECONNABORTED').
 * @param {Object} [request] The request.
 * @param {Object} [response] The response.
 * @returns {Error} The created error.
 */
module.exports = function createError(message, config, code, request, response) {
  var error = new Error(message);
  return enhanceError(error, config, code, request, response);
};
/Users/Victoria/dev/projects/shortener/kutt/node_modules/axios/lib/core/settle.js in settle at line 18:12
/Users/Victoria/dev/projects/shortener/kutt/node_modules/axios/lib/adapters/http.js in IncomingMessage.handleStreamEnd at line 201:11
events.js in emitNone at line 111:20
events.js in IncomingMessage.emit at line 208:7
_stream_readable.js in endReadableNT at line 1064:12
internal/process/next_tick.js in _combinedTickCallback at line 138:11
internal/process/next_tick.js in process._tickDomainCallback at line 218:9`

Any help as highly appreciate, thanks

**Comment by poeti8** [comment]
I assume this is because it cannot connect to Neo4j. Make sure Neo4j is running and it's credentials in config file are correct.
