### ISSUE TITLE
Issue: Duplicate Custom Address for Multiple Users

### ISSUE THREAD

**Issue by Eisa01** [thedevs-network/kutt#383]
Currently if we make a duplicate custom address in the same user, it gives an error "Custom URL is already in use." This is functioning properly.
e.g.: https://kutt.it/myCustom -> redirects to google.com

However, if a different user tried to create the same custom address, it will not provide an error, instead it will enforce it instead of the older custom url.
e.g.: different user > https://kutt.it/myCustom -> redirects to youtube.com

Another user should not be able to remove the previous custom URL by overriding.

**Comment by Ktr4ks** [comment]
Yep, there are 3 other people using the same custom link as me, and when I try open it, I'm redirected to one of the 3 randomly.
