### ISSUE TITLE
Settings for admins not working in Docker Compose Edition

### ISSUE THREAD

**Issue by MarianoFacundoArch** [thedevs-network/kutt#385]
I am running the docker compose edition, however the admin settings are not appearing even the emails are in the .env file.
I created an user using the email specified in the .env file but I don't see any special setting.

**Comment by trgwii** [comment]
This might be related to #388 ...

**Comment by MarianoFacundoArch** [comment]
No news on this?

**Comment by poeti8** [comment]
Make sure you have entered your email address correctly without quotes at the start or end. Valid example: `ADMIN_EMAILS=johndoe@example.com`. Note that there's no extra section on settings page for the admins, however you can see all the links on the table and ban or delete them.
