### ISSUE TITLE
API endpoint

### ISSUE THREAD

**Issue by willwade** [thedevs-network/kutt#39]
I'm looking to use my twitter client with kutt. Something like tweetbot. In that app it asks for an API endpoint. I cant see in the docs something like this - https://support.rebrandly.com/hc/en-us/articles/229596467-Custom-URL-Shortening-for-Tweetbot-iOS-and-MAC - does this exist like other url shorteners?

**Comment by poeti8** [comment]
I don't think so. I'm not sure how Tweetbot is sending data, but I assume it appends the URL to the endpoint, so it would be a query parameter, but in Kutt, we rely on body messages. 
You can either customize the code for your need or build a twitter bot for yourself.

See if there are any descriptions on how Tweetbot's custom API works and let me know.

**Comment by willwade** [comment]
Finally found a small amount of docs on this...


Custom URL Shortener

Tweetbot shortens URLs using an HTTP GET request that should be compatible with a number of URL services.

The request will be replace the %@ string with the URL that needs to be shortened.

The response should be one of the following formats:

URL
{ status_code : 200, data : { url : URL } }
{ shortURL : URL }
{ shorturl : URL }
Examples:

http://cli.gs/api/v1/cligs/create?url=%@
http://stnx.at/api?u=%@&i=0
http://dcom.me/api.php?u=%@
