### ISSUE TITLE
'homepage' for custom domain?

### ISSUE THREAD

**Issue by user67x** [thedevs-network/kutt#391]
Hello,

I clicked on "settings" to allow me to point my freshly purchased domain name to kutt.it
When I filled in the domain name, the "homepage" field was filled in automatically. I confess that I don't really understand what is required. Should I leave it like that?

![2020-09-29_12-19-51](https://user-images.githubusercontent.com/13274746/94547840-20735280-0250-11eb-8db9-e1d459d549b9.png)

Thank you.

**Comment by trgwii** [comment]
I believe that homepage field is fine with the default, yes. Did you set DNS settings for your domain to point to the IP? (has to be done on the site where you bought the domain from usually)

**Comment by user67x** [comment]
Hi,
Finally I have installed Yourls. I don’t know if the Kutt.it solution had worked, I prefer to have more control and have a private url shortener.
