### ISSUE TITLE
Is it possible to host the admin console and redirection functions on different ports?

### ISSUE THREAD

**Issue by TheRealBlaineMartin** [thedevs-network/kutt#397]
We were hoping to only expose the admin interface internally on our LAN, while allowing users from the internet to connect on 80 or 443 to receive the redirects. Is there no way to separate or host these two different portions of the application separately so that it can be used securely? Or are we forced to expose the admin console to the internet?!

**Comment by poeti8** [comment]
There's no way to separate them really.

**Comment by MKRhere** [comment]
Since admin is currently part of the same app, it's largely out of scope at the moment.
