### ISSUE TITLE
Dockerised version

### ISSUE THREAD

**Issue by collegeimprovements** [thedevs-network/kutt#4]
Nice job!
It would be great if you can provide some docker based version of kutt.
It would be awesome if domain can be set just by changing some env variable :)

**Comment by poeti8** [comment]
Thanks!
Sounds a good idea although I don't know much about Docker, I'll look into it.

**Comment by ebauman** [comment]
I would be interested in taking this on.

**Comment by poeti8** [comment]
@ebauman Sure, go on.
