### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by vRobM** [thedevs-network/kutt#403]
Please! A toggle in settings would be great.

**Comment by thetaung123** [comment]
I'd like to work on it if the moderators are planning to add this feature.
I have experience with Next.js, Typescript, designing the frontend ui.

**Comment by trgwii** [comment]
I would probably prefer not having a toggle, rather detecting the OS theme of the user (using the [prefers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) media feature).

That way people who have set dark mode for their OS will get dark mode on the site, and people who have light mode OS will get light mode site.

This is much simpler than having a setting that needs to be stored somehow, and means it will in most cases just already be set to the correct option.

**Comment by thetaungg** [comment]
@trgwii  prefers-color-scheme sounds good. I'll get started, then. Is there something I need to know or do before I start contributing?

**Comment by trgwii** [comment]
@thetaungg if you figure out how to run and test your changes that should be more than enough :)

**Comment by thetaungg** [comment]
#405

**Comment by Saleh56** [comment]
Ss

**Comment by trgwii** [comment]
Closing this in favor of the PR, further discussion in the PR
