### ISSUE TITLE
Shortened URL IDs not unique for same Long Url (multiple calls)

### ISSUE THREAD

**Issue by adebisi-fa** [thedevs-network/kutt#41]
Hello,

Thanks for this brilliant initiative in the url-shortening space!

Please, will it not be most preferable if multiple calls to shorten a Long Url (via **~/api/url/submit**) return a **unique short url** (kutt.it/**unique-id-for-this-long-url**)? For the same API Key at least?

[It returns different shortened urls, for each call, **for same long url**, right now.]

This will put this service on par, with goo.gl (which has been shut down).

Thanks, please.

**Comment by poeti8** [comment]
The problem is, what if a user wants to use multiple links for a URL so they can share each one in different platforms and monitor their stats?

**Comment by trgwii** [comment]
Query parameter!

**Comment by trgwii** [comment]
Either add `reuse: bool` or `unique: bool`

Reuse would reuse an existing link (if any), or alternatively, unique would generate a fresh link always

**Comment by poeti8** [comment]
Adding `unique: bool` to the API is a good approach.

**Comment by poeti8** [comment]
#48
