### ISSUE TITLE
Show long url with appending +

### ISSUE THREAD

**Issue by muescha** [thedevs-network/kutt#42]
like other link shorteners it should show the long url with appending `+` to the short url

shor tlink with redirect: `https://kutt.it/abcd`
show full url preview: `https://kutt.it/abcd+`

**Comment by poeti8** [comment]
Since stats are private I'm not really sure about what to show. Maybe only the full URL.

**Comment by muescha** [comment]
Just the full url without redirect

**Comment by stefanes** [comment]
Any way to keep the expansion private for sensitive links, without having to go through the login page? E.g. passing the link password as an URL option?

**Comment by poeti8** [comment]
@stefanes Hmm could be possible. You may want to open a new issue as a feature request.
