### ISSUE TITLE
require login to create short urls

### ISSUE THREAD

**Issue by Grienauer** [thedevs-network/kutt#422]
Is there a way to require a login?
Instead of having an open system where everyone can directly add shorturls, it would be great for some cases, to force users to register, before they can create a short url.

thank you for your tool and that you provide it open source.

**Comment by lukaszs0** [comment]
If you set DISALLOW_ANONYMOUS_LINKS to true, then only logged user can create links.

**Comment by Grienauer** [comment]
Thank you. missed that…
