### ISSUE TITLE
I have made the Chinese Translation Version (2.7.1) based on the official program. I hope the author can modify it and add it into the optional language. Thank you

### ISSUE THREAD

**Issue by 1275788667** [thedevs-network/kutt#425]
#419 I have made the Chinese Translation Version (2.7.1) based on the official program. I hope the author can modify it and add it into the optional language. Thank you
[kutt.zip](https://github.com/thedevs-network/kutt/files/5786310/kutt.zip)
@MFYDev  @MKRhere  @poeti8

**Comment by poeti8** [comment]
Thanks, I'm gonna close this issue so we can address it on the other one.
