### ISSUE TITLE
Delete shortUrls automatically after x days of generating them

### ISSUE THREAD

**Issue by Prathik-Jain** [thedevs-network/kutt#43]
I would love to have an option in the setting to delete all URL's after a set time - That would save memory on Kutt as well. :tada:

**Comment by trgwii** [comment]
As an addition / alternative:
We could also / or delete URLs X days after last click

**Comment by abhijithvijayan** [comment]
But It should be an optional feature for each link.

Otherwise if someone has shortened an important link and saved it somewhere and it gets auto deleted along with every other, it won't be good.

**Comment by poeti8** [comment]
This feature is added now.
