### ISSUE TITLE
false URL is containing malware/scam.

### ISSUE THREAD

**Issue by dolphinsd** [thedevs-network/kutt#436]
After getting URL is containing malware/scam, it would be great to know the source of the issue to go fix it.

For example https://www.rvseasy.com/  short link resolved in false URL is containing malware/scam.

Where does rvseasy.com needs to go to fix it as it is legit business. Thanks for advise, it would more informative to provide source in error message.

**Comment by tcreek** [comment]
It's not an issue with this project. Their web site has probably been compromised.

**Comment by poeti8** [comment]
Sorry for the false positive. You can report to support@kutt.it
