### ISSUE TITLE
"View Stats" button does not appear (gone)

### ISSUE THREAD

**Issue by DouglasRenato** [thedevs-network/kutt#443]
Hello, first of all I would like to thank and congratulate you for the incredible open source tool.

It turns out that it will be 2 weeks now that the button to see the statistics of the short link simply does not appear.

![print](https://i.imgur.com/hQdISlt.png)

I logged out and logged in again.
I removed the browser chache and cookies.
I even created a new account, and the one in the new account also doesn't have the button to check the performance of the short link.

I don't know exactly if it's a platform bug.

Could you please help us?

Keep up the good work.

**Comment by poeti8** [comment]
When the view is 0 there are no stats as well. If kutt.it has issues processing the views and stats it might be because of the volume of the requests, if it didn't get resolved after some time can let us know.

**Comment by DouglasRenato** [comment]
Hello, thanks for the feedback. Statistics again appeared 🙆‍♂️.

I appreciate the support
