### ISSUE TITLE
Admin account logged in but can not see any admin action

### ISSUE THREAD

**Issue by minhuy58** [thedevs-network/kutt#447]
The file env saved with new admin email address but after logged in, there is no admin action. The admin actions section never show up. Tried to re installed the app multiple times already. Please help.

**Comment by minhuy58** [comment]
Hello,
Can someone help me please?

**Comment by poeti8** [comment]
There's no admin page (yet). You can see extra actions on the table to ban and remove links.

**Comment by SecureCPU** [comment]
Hey, Is there an admin panel now? Where I can see all the users signed up?
I can't seem to find it from the admin account
