### ISSUE TITLE
How to customize the front page

### ISSUE THREAD

**Issue by minhuy58** [thedevs-network/kutt#452]
Hello, 

Is there a way to customize the front page of Kutt? I want to change some sentences in there, change the logo to company logo and add a hyperlink to that front page.

Thank you,

**Comment by poeti8** [comment]
You can fork the repository and edit the code. There's no configurable customization right now.

**Comment by Sponkolit** [comment]
still not possible? Would be great to have the possibility to change link to the imprint e.g.

**Comment by trgwii** [comment]
[v3 seems to have some stuff now](https://github.com/thedevs-network/kutt/blob/main/README.md#themes-and-customizations)
