### ISSUE TITLE
https certificate expired

### ISSUE THREAD

**Issue by veerjd** [thedevs-network/kutt#453]
I know it's not code related, but I'm not sure how else to flag that https://kutt.it/ doesn't load

**Comment by poeti8** [comment]
It does load for me, what do you see exactly?

**Comment by veerjd** [comment]
![image](https://user-images.githubusercontent.com/26885867/112759727-4fca0880-8fc2-11eb-8922-d3b45ced41b6.png)

**Comment by veerjd** [comment]
Turns out it's because Avast flags it as URL:Phishing. May still want to do something about that
