### ISSUE TITLE
How do I enable HTTPS without a port number, when port 443 is already in use?

### ISSUE THREAD

**Issue by EmilyLove26** [thedevs-network/kutt#457]
I'm using an Apache Reverse Proxy to achieve HTTPS on Port 443 but I'm running into an issue. Keep in mind I must use a reverse proxy since other services also run on the same port.

Whenever I make a new shortlink on https://go.loveazure.cloud/, the links it creates always have port 3000 added to it. As it is, any generated links don't work since Kutt isn't listening on https port 3000, only http.

I want to hide the port entirely. How do I do this?
( https://go.loveazure.cloud:3000/7OX >> https://go.loveazure.cloud/7OX )

Attached: (Apache config & Kutt Docker Config)
[go.loveazure.cloud.zip](https://github.com/thedevs-network/kutt/files/6236979/go.loveazure.cloud.zip)

![image](https://user-images.githubusercontent.com/7028351/113154425-ffdb8380-9205-11eb-824c-f148b882efd2.png)

**Comment by poeti8** [comment]
I assume your have set `DEFAULT_DOMAIN` to `go.loveazure.cloud:3000`, in that case, you can change it to `go.loveazure.cloud`.

**Comment by EmilyLove26** [comment]
That was it, thank you!
