### ISSUE TITLE
it is possible to create shortURL via API with Kutt ?

### ISSUE THREAD

**Issue by JOduMonT** [thedevs-network/kutt#466]
Hey I just found a function for function.php (WordPress) which generate shorturl from TtinyUrl and I was wondering if it's possible to do something similar with Kutt.

Basically it call an API to create a shortURL.

```
    function getTinyUrl($url) {
        $tinyurl = file_get_contents("http://tinyurl.com/api-create.php?url=".$url);
        return $tinyurl;
    }
```

**Comment by poeti8** [comment]
Yes. Please visit https://docs.kutt.it/
