### ISSUE TITLE
Wrong user-agent detection in Kutt

### ISSUE THREAD

**Issue by AriaShishegaran** [thedevs-network/kutt#47]
Hi i'm using Kutt service with custom domain, i'm currently tracking a link inside instagram stories, most users are coming from Android and iOS but the most visit is coming from IE which is obviously not true, even if it was it should have been MS Edge not IE. wanted to report this issues, i hope i gets fixed.
![2018-05-19_16-15-42](https://user-images.githubusercontent.com/15879200/40268290-f5eefc18-5b7f-11e8-8812-bf4c68cacd83.png)

**Comment by poeti8** [comment]
Couldn't reproduce the issue. If Instagram or another app changes the user-agent I don't think if I can do something, I grab the user-agent as it is and parse it, I don't change it.
Let me know if you had more info on this.

**Comment by MKRhere** [comment]
Closing for housekeeping.
