### ISSUE TITLE
Error 500 on link creation

### ISSUE THREAD

**Issue by JunkiEDM** [thedevs-network/kutt#479]
(self-hosted) I haven't been able to find any other leads to what the issue is, I don't see any discrepancies in the server's logs; the only thing is a `POST https://<private>/api/v2/links 500` in the client console logs. env should be fine, safe browsing vars aren't set as I'm not using it for this private instance.

**Comment by AlphaNecron** [comment]
Recheck your request body & header.

**Comment by JunkiEDM** [comment]
Not exactly sure what I should be checking for, but here are my request headers:
```
:authority: <private>
:method: POST
:path: /api/v2/links
:scheme: https
accept: application/json, text/plain, */*
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9
authorization: <private>
content-length: 65
content-type: application/json;charset=UTF-8
cookie: token=<private>
dnt: 1
origin: https://<private>
referer: https://<private>/
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: same-origin
sec-gpc: 1
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36
```
& Request Body:
`{showAdvanced: true, target: "google.com", domain: "<private>"}`

**Comment by AlphaNecron** [comment]
You are missing `X-API-KEY` ?
