### ISSUE TITLE
I want to add my C# package to the 3rd packages list.

### ISSUE THREAD

**Issue by AlphaNecron** [thedevs-network/kutt#482]
Since KuttSharp is outdated, i made a new C# API Wrapper, and it uses API V2 instead of V1
Here's the repo: [Kutt.NET](https://github.com/AlphaNecron/Kutt.NET/tree/master/Kutt.NET)
NuGet package: https://www.nuget.org/packages/Kutt.NET/

Thanks in advance.

**Comment by poeti8** [comment]
Please make a pull request to update README.md file
