### ISSUE TITLE
Add logging mechanism 

### ISSUE THREAD

**Issue by Rupeshiya** [thedevs-network/kutt#486]
**Present scenario:** 
Right now there is no logging mechanism which makes it tougher to debug

**Expected scenario:** 
Some logging mechanism should be there so that the error can be caught easily when server is running
Like Winston or morgan

**Comment by Rupeshiya** [comment]
Should I proceed @poeti8 ?

**Comment by poeti8** [comment]
@Rupeshiya Sure. I also had plans to use a third-party logging service like [loggly](https://www.loggly.com). Do you think you can integrate it as well?

**Comment by Rupeshiya** [comment]
@poeti8 I think it's not open source right?
So if we have the credentials to use it. I can try to integrate it with the existing codebase
