### ISSUE TITLE
Verification email error

### ISSUE THREAD

**Issue by siwel** [thedevs-network/kutt#5]
Hey,

Clicking the link in the verification email give me this error;

![image](https://user-images.githubusercontent.com/6073481/36307785-a25b617a-1315-11e8-8f54-e2d2f6c1c95e.png)

Thanks,
Lewis

**Comment by poeti8** [comment]
@siwel I guess that you tried to sign up multiple times, in that case only the last verification email will work. Please check if you got same email multiple times and open the last one.

**Comment by siwel** [comment]
@poeti8 Hmm, I did get Two emails - the verification links for both do not work though 🤔

**Comment by siwel** [comment]
Just attempted to login and appears to be working.
