### ISSUE TITLE
Why Graphical Database?

### ISSUE THREAD

**Issue by zhilevan** [thedevs-network/kutt#50]
Thank you for develop such a great tool with the new tools, but as a Web developer and Data Engineer I have a question , why you using Neo4j for database of this tool while this tool ( url shortener) dosen't need  the features of graphical database?

### Are you going to implement some features which use the features of graph concepts or you just use it because it's a new and trending database?

**Comment by poeti8** [comment]
I talked about it here
https://youtu.be/MUsvRbOnrNY?t=17m55s

Sorry about the sound and accent, it was live and I had no idea the sound was like that. But you can at least take a look at relationships and get the idea.

**Comment by zhilevan** [comment]
Thank you for replying, but as a data engineer I guess you can have better performance with using no graphical database ( and as you know neo4j is not in the top performance graph database  and this model you've shared in the presentation you can simply get better performance with ArangonDB  and you use neo4j just because it's the easiest  graph database to learning)

by the way, I appreciate your work and as a developer suggest you implement the database layer az an interface and let the user choose their database type, I'll strongly recommend providing a performance test in this tool with using graph database and non-graph database in high traffic with a huge number of records. 
in my opinion, Neo4j for this project and application is not the best.

**Comment by trgwii** [comment]
ArangoDB looks very interesting!
