### ISSUE TITLE
Statistics are not working on selfhosted kutt

### ISSUE THREAD

**Issue by svsem** [thedevs-network/kutt#501]
Hello!

I'm running kutt on my ubuntu linode VPS with custom subdomain. I'm using docker-compose, nginx-proxy (For auto reverse proxy) and acme-companion (for auto-ssl).

Total clicks are counted correctly (Although they are not displayed on the statistics page), but statistics are empty.

I've attached screenshots, docker-compose.yml and .kutt.env

Am I doing something wrong or is it a bug?

I would be grateful for any help. Thank you.

![Screenshot_16](https://user-images.githubusercontent.com/87268679/128171371-1b7919f9-65c5-4190-9fba-8d3e17521f5a.png)
![Screenshot_17](https://user-images.githubusercontent.com/87268679/128171375-b7f683ba-83b2-4b16-8458-9d9f2fe2b830.png)
[kutt env.txt](https://github.com/thedevs-network/kutt/files/6930727/kutt.env.txt)
[kutt docker compose.txt](https://github.com/thedevs-network/kutt/files/6930728/kutt.docker.compose.txt)

**Comment by svsem** [comment]
I've noticed just that for some reason only the first click is tracked. I've tried using multiple browsers and different devices, but it does not help

**Comment by poeti8** [comment]
There's a limit for detailed stats for each user's link. You have set it to **1** on your env file: 

```
DEFAULT_MAX_STATS_PER_LINK=1
```

You can update it to your desired value.
