### ISSUE TITLE
Sign-up email Prompt “An error occurred.”

### ISSUE THREAD

**Issue by coppea** [thedevs-network/kutt#507]
I'm sorry if I can't speak English well.

I use Docker to install

`.env `The configuration is as follows

> PORT=3000
> 
> SITE_NAME=xxxxx
> DEFAULT_DOMAIN=xxxxxx.com
> LINK_LENGTH=5
> DB_HOST=postgres
> DB_PORT=5432
> DB_NAME=postgres
> DB_USER=
> DB_PASSWORD=
> DB_SSL=false
> .......
> ADMIN_EMAILS=xxxxx@outlook.com
> MAIL_HOST=smtp.office365.com
> MAIL_PORT=587
> MAIL_SECURE=false
> MAIL_requireTLS=true
> MAIL_USER=
> MAIL_FROM=xxxxxx@outlook.com
> MAIL_PASSWORD=xxxxxxxxx
> 
> REPORT_EMAIL=xxxxxx@outlook.com
> 
> CONTACT_EMAIL=xxxxx@outlook.com

Prompt this
<img width="632" alt="截屏2021-08-07 15 12 15" src="https://user-images.githubusercontent.com/86509331/128592189-acdc558d-d65f-4360-bea0-1e63232cdc29.png">

#269 ”but you can connect to the database, go to the users table, find your user, and retrieve the verification_token, then put that in a URL“
Excuse me, is this also applicable to docker? how to operate it?

**Comment by coppea** [comment]
docker postgres
How to link postgres to find token

**Comment by BuckyTM** [comment]
How did you do it?

**Comment by aparaschiv** [comment]
For docker you can try `docker exec -ti $CONTAINER_NAME psql -U $DB_USER -c "SELECT verification_token FROM users WHERE email='yourmail@provider.com';"`

**Comment by coppea** [comment]
> > docker exec -ti kutt-postgres-1 psql -U user -c "SELECT verification_token FROM users WHERE email='[XXXXXX@gmail.com](mailto:XXXXXX@gmail.com)';"
> > **The following error occurred in the run command**
> > ![图片](https://user-images.githubusercontent.com/74865147/170507874-a31cb70d-5f47-4978-aa61-f529b29f60f6.png)
> > **The following figure shows the configuration file**
> > ![图片](https://user-images.githubusercontent.com/74865147/170508526-f33f17c1-1aac-45f3-9e59-4646bfa606ad.png)
这些我都默认没有动,你重点关注email设置,可以换用腾讯企业邮箱试试
