### ISSUE TITLE
Title for each long/short link pair

### ISSUE THREAD

**Issue by liquid06** [thedevs-network/kutt#51]
kutt.it is the best tool for link shortening. It feels modern, straightforward, and it's easy to use. One thing that I think would make it even better is allowing the user to optionally add a title for their long/short link pair.

I'm often using kutt-it to shorten links to Google docs. Once you've got ten of them in there it's not easy to tell at a glance which is which. Which document was the work plan? There are too many links for which the beginning has exactly the same name to know.

Sometimes I skirt this problem by using custom path to describe what I am linking to. But if the app tells me that the custom path is not valid, then it's a mystery link. A mystery long ling and a mystery short link for which case I need to click through them all to find the one I intend to use.

Adding an optional title field for link pairs could solve both of these problems! 💡

**Comment by trgwii** [comment]
Hmmm, I guess we could call this field "Comment" or "Description", since "title" usually implies it will be displayed to the visitor, would that be a good idea?

**Comment by poeti8** [comment]
Good idea. I'll start implementing once I got time and figured out where to place the input.
So I need to:
1- Add description input.
2- Show the description on the table.
3- Being able to search through descriptions.

**Comment by UnlimitedCookies** [comment]
What's the status on this issue?

And I would prefer to call it an alias (description is also fine).
