### ISSUE TITLE
Duplicated custom short URL

### ISSUE THREAD

**Issue by mikelgmh** [thedevs-network/kutt#513]
At kutt.it I can create a new custom short url. Sometimes, when I go into that URL the destination is a random one.

It's like the custom url was duplicated in other user's account and randomly chooses between one of these destinations.

**There's another problem related to this:**
When you create a new custom short url (for example https://kutt.it/a) it will say the custom url is already taken. This is ok, but if you generate a random short url and then you edit the kutt.it/{url} and use a taken one, it will work.

You can check these links below and see how sometimes the destination is different:

[https://kutt.it/m]()
[https://kutt.it/a]()

**Comment by poeti8** [comment]
Thanks for the report!
