### ISSUE TITLE
Short links to user/link

### ISSUE THREAD

**Issue by lfdajr** [thedevs-network/kutt#52]
Would be great to have a way to make links inside my folder, for instance:

some url => www.kutt.it/username/shortlink

Or maybe we could at least use "/" in custom links.

**Comment by trgwii** [comment]
I'm not sure we would want to expose usernames like this. Why not just do it yourself with _ or some other character?

`kutt.it/lfdajr_mylink`

**Comment by lfdajr** [comment]
This could be an option. If the user wants it, that's ok. 
I think it's more readable links like /lfdajr/presentation1 than /presentation2341 as /presentation1 may be taken at the time. But as I said, this could be an option for users. I would love to use my links under my ID/USERNAME.

**Comment by poeti8** [comment]
I don't think this is a good idea. We support custom domains which are a better solution. Also, what's the point of a URL shortener if the shortened URL is going to be long.
