### ISSUE TITLE
Signups are disabled

### ISSUE THREAD

**Issue by AlvesR0** [thedevs-network/kutt#534]
There is a predictions to open registrations on the Kutt website? I tried to shorten a link. But it does not work. 
![image](https://user-images.githubusercontent.com/76485731/142732863-1242a82b-061c-44cb-9abe-0c9198564480.png)

thank you.
AlvesRO.

**Comment by CaptnCodr** [comment]
"(Signup has been disabled temporarily.)" appears too.
Why is it disabled and why can't we shorten links?

**Comment by poeti8** [comment]
Hey guys, really sorry for that. Unfortunately the number of phishing and malware links have been increasing a lot and it's really hard for me, one person, to put hours every day to take care of the reports. And if I don't, the server provider would shut the website down, not to mention that people would potentially lose money over these phishing links.

I'm already using Google Safe API to detect spams but it's not enough, so until the number of spam links gets decreased and I find a better way to prevent spams and handle the reports I'm gonna keep the sign-in disabled for a short while.

**Comment by Loki-L1130** [comment]
Is there any ETA Signups become alive again ?

**Comment by francisyzy** [comment]
@poeti8 was thinking if you can enable signups but only for people with custom domains so that they can use this service without affecting the kutt.it domain phishing/malware rating as they are forced to use their own domain rating.

**Comment by poeti8** [comment]
@francisyzy Hmm that's a good idea! I'll see if I find time to implement this.

**Comment by CaptnCodr** [comment]
or some kind of invitation from administrators.

**Comment by elimisteve** [comment]
@focusonyoursite The Kutt software works fine when you set it up on your own domain. I did just that and my instance is independent of https://kutt.it/ , and so it works :+1: .

**Comment by SaiPanneerselvam** [comment]
Wondering why this issue hasn't been closed but other issues that are related to this has been closed.

**Comment by francisyzy** [comment]
> Wondering why this issue hasn't been closed but other issues that are related to this has been closed.

This is the first one for this issue, the related ones are dupe.

The service still works if you had an existing account before the abuse started and the new account signups are disabled.

I think kutt.it was flagged as a dangerous domain previously due to the abuse and thus new signups are disabled

**Comment by poeti8** [comment]
>Wondering why this issue hasn't been closed but other issues that are related to this has been closed.

Need one (or two) of them open so I can track it.

**Comment by SaiPanneerselvam** [comment]
its been 2+ years since the original debut of the problem. Any fix? I still see the option is blocked, and the last change/pr has been 2 years ago.

**Comment by poeti8** [comment]
Check out [v3](https://github.com/thedevs-network/kutt/tree/v3), it's almost done, and hopefully released by the end of this year.

**Comment by poeti8** [comment]
Signups are enabled now
