### ISSUE TITLE
Where is example.env ?

### ISSUE THREAD

**Issue by mostfurious** [thedevs-network/kutt#544]
Hello,
Want to try this url shortener but it seems files are missing. In the documentation it says "Copy .example.env to .env and fill it properly"
There is no .env dir and there is no example.env file in unzip folder. Find commands doesnt find anything either.

**Comment by francisyzy** [comment]
There is `.example.env` here https://github.com/thedevs-network/kutt/blob/develop/.example.env

"Copy .example.env to .env" is equivalent to this command line command `cp .env.example .env`

**Comment by mostfurious** [comment]
> There is `.example.env` here https://github.com/thedevs-network/kutt/blob/develop/.example.env
> 
> "Copy .example.env to .env" is equivalent to this command line command `cp .env.example .env`

Thanks
