### ISSUE TITLE
Is the service still alive ?

### ISSUE THREAD

**Issue by Loki-L1130** [thedevs-network/kutt#546]
The Webpage is currently unavailable. Why signup is blocked right now ?

**Comment by francisyzy** [comment]
https://github.com/thedevs-network/kutt/issues/534#issuecomment-977545278

**Comment by Loki-L1130** [comment]
@francisyzy Signup is blocked that is Okay. But the website is totally inaccessible is it also due to this reason ?

**Comment by poeti8** [comment]
@Loki-L1130 No it's up. What's the problem you're encountering? Could be an anti-virus or even your iSP is blocking you from accessing Kutt?

**Comment by francisyzy** [comment]
> @francisyzy Signup is blocked that is Okay. But the website is totally inaccessible is it also due to this reason ?

https://kutt.it/8uREZW I just accessed the website and made a link as I had an account last time. https://www.isitdownrightnow.com/kutt.it.html

**Comment by Loki-L1130** [comment]
@poeti8 It is my VPN, It cannot reach kutt after changing country it worked well.
