### ISSUE TITLE
403 error when generating API Key

### ISSUE THREAD

**Issue by dewittn** [thedevs-network/kutt#552]
I've got Kutt set up on a custom domain, and everything works as expected except for generating an API Key. Nginx reports a 403 error for the request `POST /api/v2/auth/apikey`

Any suggestions on what is causing this or how I can debug it?

**Comment by elimisteve** [comment]
@dewittn I also just got Kutt set up and seem to be running into some of the same issues you are :sweat_smile: . When I do

    $ curl -i -H "Content-Type: application/json" -X POST -d '{}' https://myactualdomain.com/api/v2/auth/apikey

I get back a `401 Unauthorized`. What are you sending in your POST that triggers the 403?

**Comment by dewittn** [comment]
@elimisteve I'm guessing you need to send the admin email when generating an API key, and that's why you are getting the 401 error. 

I got the 403 error simply by clicking on the "Generate API Key" button on the `/settings` page. I haven't looked into the JS request that gets generated yet so I haven't been able to test via the command line. 

But I'll do some digging and report back!

**Comment by dewittn** [comment]
Ok I figured it out. The problem was that my nginx conf file was blocking the API route. I removed that restriction and everything work as expected. Will close this issue.

@elimisteve To get an API via the command line you need to attach an `Authorization` header to your request, which is the cookie value when you login. You request above should look like this:

`$ curl -i -H "Content-Type: application/json" -H "Authorization: <COOKIE-VAULE>" -X POST -d 'null' https://myactualdomain.com/api/v2/auth/apikey`

That worked for me and allowed me to generate an API key.
