### ISSUE TITLE
Service seems to be down

### ISSUE THREAD

**Issue by goear** [thedevs-network/kutt#556]
Just to let you know that seems that the servers are overloaded.

**Comment by elimisteve** [comment]
Looks like it's not that the servers are overloaded, but that the Content Security Policy is too strict:

![kutt-jsconsole-error-Screenshot_2022-01-24_01-24-50](https://user-images.githubusercontent.com/139603/150756026-435a4baf-e8d9-44dc-b575-de46bbddbdd3.png)

**Comment by GalaxySH** [comment]
The API continues to respond with 504 and 522 so I would assume the servers are overloaded

**Comment by dimo414** [comment]
@poeti8 you seem to be a primary contributor - is this service discontinued?
