### ISSUE TITLE
Error in Signup when run locally

### ISSUE THREAD

**Issue by vbmade2000** [thedevs-network/kutt#561]
I am trying to run **kutt** using docker-compose. When I try to signup for new user, it says "**An error occured**". In browser console it shows the API endpoint returns 500 code. I have no idea if any setting if required for user management. Also, in **docker logs** I see following error. Posting here in case it helps.

```
(node:89) UnhandledPromiseRejectionWarning: ReplyError: ERR AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?
    at parseError (/usr/src/app/node_modules/ioredis/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/usr/src/app/node_modules/ioredis/node_modules/redis-parser/lib/parser.js:302:14)
```

**Comment by kengher** [comment]
See if my [comment](https://github.com/thedevs-network/kutt/issues/545#issuecomment-1030413542) on another issue helps.

**Comment by vbmade2000** [comment]
Solved. Thanks @kengher.
