### ISSUE TITLE
kutt.it is down - permanent 504 gateway timeout on everything

### ISSUE THREAD

**Issue by mRokita** [thedevs-network/kutt#571]
I would appreciate a quick fix - I used kutt.it for some links in my bachelor thesis which has been already submitted for review.

**Comment by mamodrzejewski** [comment]
I am experiencing the same error. Quick fix much appreciated 🙏

**Comment by poeti8** [comment]
@mRokita At the time you created this issue I checked Kutt and it wasn't down. Do you have any more information on this? Were the links not redirecting? Was the homepage not opening?

**Comment by mRokita** [comment]
> @mRokita At the time you created this issue I checked Kutt and it wasn't down. Do you have any more information on this? Were the links not redirecting? Was the homepage not opening?

The homepage opened normally (probably cached by cloudflare), but the API didn't work. The links weren't redirecting - cloudflare was returning 504 instead, suggesting that kutt.it malfunctioned.
