### ISSUE TITLE
[Docker] Unable to make it work despite the documentation

### ISSUE THREAD

**Issue by thepra** [thedevs-network/kutt#577]
>mar 13 16:29:36 <someUser> systemd[1]: Started Kutt.
mar 13 16:29:37 <someUser> docker-compose[26762]: Creating network "kutt_default" with the default driver
mar 13 16:29:37 <someUser> docker-compose[26762]: Creating kutt_redis_1 ...
mar 13 16:29:37 <someUser> docker-compose[26762]: Creating kutt_postgres_1 ...
mar 13 16:29:39 <someUser> docker-compose[26762]: [122B blob data]
mar 13 16:29:39 <someUser> docker-compose[26762]: [102B blob data]
mar 13 16:29:39 <someUser> docker-compose[26762]: postgres_1  |
mar 13 16:29:39 <someUser> docker-compose[26762]: redis_1     | 1:C 13 Mar 2022 15:29:39.123 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
mar 13 16:29:39 <someUser> docker-compose[26762]: redis_1     | 1:C 13 Mar 2022 15:29:39.123 # Redis version=6.0.16, bits=64, commit=00000000, modified=0, pid=1, just started
mar 13 16:29:39 <someUser> docker-compose[26762]: redis_1     | 1:C 13 Mar 2022 15:29:39.123 # Warning: no config file specified, using the default config. In order to specify a config file us>
mar 13 16:29:39 <someUser> docker-compose[26762]: postgres_1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
mar 13 16:29:39 <someUser> docker-compose[26762]: postgres_1  |
mar 13 16:29:39 <someUser> docker-compose[26762]: redis_1     | 1:M 13 Mar 2022 15:29:39.125 * Running mode=standalone, port=6379.
mar 13 16:29:39 <someUser> docker-compose[26762]: redis_1     | 1:M 13 Mar 2022 15:29:39.125 # Server initialized
mar 13 16:29:39 <someUser> docker-compose[26762]: postgres_1  | 2022-03-13 15:29:39.211 UTC [1] LOG:  starting PostgreSQL 12.10 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.3.1_git20211>
mar 13 16:29:39 <someUser> docker-compose[26762]: redis_1     | 1:M 13 Mar 2022 15:29:39.125 * Loading RDB produced by version 6.0.16
mar 13 16:29:39 <someUser> docker-compose[26762]: redis_1     | 1:M 13 Mar 2022 15:29:39.125 * RDB age 7 seconds
mar 13 16:29:39 <someUser> docker-compose[26762]: postgres_1  | 2022-03-13 15:29:39.212 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
mar 13 16:29:39 <someUser> docker-compose[26762]: postgres_1  | 2022-03-13 15:29:39.212 UTC [1] LOG:  listening on IPv6 address "::", port 5432
mar 13 16:29:39 <someUser> docker-compose[26762]: redis_1     | 1:M 13 Mar 2022 15:29:39.125 * RDB memory usage when created 0.77 Mb
mar 13 16:29:39 <someUser> docker-compose[26762]: redis_1     | 1:M 13 Mar 2022 15:29:39.125 * DB loaded from disk: 0.000 seconds
mar 13 16:29:39 <someUser> docker-compose[26762]: redis_1     | 1:M 13 Mar 2022 15:29:39.125 * Ready to accept connections
mar 13 16:29:39 <someUser> docker-compose[26762]: postgres_1  | 2022-03-13 15:29:39.229 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
mar 13 16:29:39 <someUser> docker-compose[26762]: postgres_1  | 2022-03-13 15:29:39.268 UTC [23] LOG:  database system was shut down at 2022-03-13 15:29:32 UTC
mar 13 16:29:39 <someUser> docker-compose[26762]: postgres_1  | 2022-03-13 15:29:39.278 UTC [1] LOG:  database system is ready to accept connections
mar 13 16:29:39 <someUser> docker-compose[26762]: kutt_1      | wait-for-it.sh: waiting 15 seconds for postgres:5432
mar 13 16:29:39 <someUser> docker-compose[26762]: kutt_1      | wait-for-it.sh: postgres:5432 is available after 0 seconds
mar 13 16:29:40 <someUser> docker-compose[26762]: kutt_1      |
mar 13 16:29:40 <someUser> docker-compose[26762]: kutt_1      | > kutt@2.7.4 start /usr/src/app
mar 13 16:29:40 <someUser> docker-compose[26762]: kutt_1      | > npm run migrate && cross-env NODE_ENV=production node production-server/server.js
mar 13 16:29:40 <someUser> docker-compose[26762]: kutt_1      |
mar 13 16:29:40 <someUser> docker-compose[26762]: kutt_1      |
mar 13 16:29:40 <someUser> docker-compose[26762]: kutt_1      | > kutt@2.7.4 migrate /usr/src/app
mar 13 16:29:40 <someUser> docker-compose[26762]: kutt_1      | > knex migrate:latest --env production
mar 13 16:29:40 <someUser> docker-compose[26762]: kutt_1      |
mar 13 16:29:41 <someUser> docker-compose[26762]: kutt_1      | Requiring external module ts-node/register
mar 13 16:29:46 <someUser> docker-compose[26762]: kutt_1      | Using environment: production
mar 13 16:29:46 <someUser> docker-compose[26762]: kutt_1      | Already up to date
mar 13 16:29:48 <someUser> docker-compose[26762]: kutt_1      | > Ready on http://localhost:6544

From the service logs (run with docker-compose up) it does seems that the startup is successful and no errors in sight but trying to locally reach `http://localhost:6544/` is to no avail, firefox says just: "Unable to connect". Plus it does seem to don't have any table created in it's database at startup, is this normal?

What can I further check out to understand what's wrong?

Meanwhile the docker.env looks like:
>PORT=6544
SITE_NAME=Hosted Kutt
DEFAULT_DOMAIN=redacted
LINK_LENGTH=6
DB_HOST=postgres
DB_PORT=5432
DB_NAME=redacted
DB_USER=redacted
DB_PASSWORD=redacted
DB_SSL=false
REDIS_HOST=redis
REDIS_PORT=6379
REDIS_PASSWORD=
DISALLOW_REGISTRATION=false
DISALLOW_ANONYMOUS_LINKS=true
USER_LIMIT_PER_DAY=100
NON_USER_COOLDOWN=0
DEFAULT_MAX_STATS_PER_LINK=100000
CUSTOM_DOMAIN_USE_HTTPS=false
JWT_SECRET=redacted
ADMIN_EMAILS=redacted
RECAPTCHA_SITE_KEY=
RECAPTCHA_SECRET_KEY=
GOOGLE_SAFE_BROWSING_KEY=
GOOGLE_ANALYTICS=
GOOGLE_ANALYTICS_UNIVERSAL=
MAIL_HOST=redacted
MAIL_PORT=redacted
MAIL_SECURE=false
MAIL_requireTLS=true
MAIL_USER=redacted
MAIL_FROM=redacted
MAIL_PASSWORD=redacted
REPORT_EMAIL=redacted
CONTACT_EMAIL=redacted

**Comment by lukaszs0** [comment]
If you changed PORT in .env you should also change port in section ports in docker-compose.yml. Replace both 3000 with 6544.

**Comment by AIndoria** [comment]
> If you changed PORT in .env you should also change port in section ports in docker-compose.yml. Replace both 3000 with 6544.

This has not worked for me fwiw. nginx simply redirects me to localhost:3015 that errors out(I only changed the 3015:300 in compose.yml, and .env is default). Virtually every other nginx proxy_pass works.

**Comment by lukaszs0** [comment]
@AIndoria probably you have another problem. You should change DEFAULT_DOMAIN in .env to your nginx external address and port.
domain: example.com:80
docker inside port: 3000
docker outside (host) port: 3015

.env
```
PORT=3000
DEFAULT_DOMAIN=example.com:80
```
docker-compose.yml
```yml
ports:
    - "3015:3000"
```

nginx example.com config file
```nginx
server {
  listen *:80;
  location / {
    proxy_pass http://localhost:3015;
  }
}
```

**Comment by AIndoria** [comment]
@lukaszs0 sadly, I have already tried that. My installation looks almost 1:1 to what you posted.

**Comment by lukaszs0** [comment]
@AIndoria It's probably issue with cache in your browser. Server returns ```301 Moved Permanently``` code. And next time browser remember old redirection target.
Try on another browser or another PC.

**Comment by lacafjh** [comment]
> It's probably issue with cache in your browser. Server returns `301 Moved Permanently` code. And next time browser remember old redirection target. Try on another browser or another PC.

After clearing my browser cache, I found that the set subdomain did stop redirecting to localhost. Thanks for the reminder!
