### ISSUE TITLE
Feature request: custom shortener domains without a 3rd party

### ISSUE THREAD

**Issue by shruuub** [thedevs-network/kutt#583]
Hello, could you please allow to used custom short domains to be setup by a admin, without using a 3rd party (when using the normal add domain feature, for some reason rebrand.ly is used). 

Edit:/Plus, how does the SITE_NAME var work? It doesnt display anything for me.

**Comment by SamGreenwood1** [comment]
You could just self host it.

**Comment by shruuub** [comment]
> You could just self host it.

Please read my message correctly. I selfhost kutt, but when i add a custom domain, rebrandly is used, with no config option to change this

**Comment by TyraVex** [comment]
Here's a solution :
```
server {
    listen 80;
    server_name <custom domain>;
    
    # Redirect requests without arguments to a default page
    if ($request_uri = '/') {
        return 302 $scheme://<default domain redirect>$request_uri;
    }
    
    # Redirect requests with arguments
    if ($request_uri != '/') {
        rewrite ^/(.*)$ $scheme://<self hosted kutt domain>/$1 permanent;
    }
}
```

**Comment by shruuub** [comment]
Damn, has been so long that I even stopped using kutt. However, yes, that seems to be a pretty good workaround, thanks a lot!
