### ISSUE TITLE
Links Not Working

### ISSUE THREAD

**Issue by SamGreenwood1** [thedevs-network/kutt#591]
I'm running a self hosted instance on a Cloudron server hosted on Linode. I am having issues with the short URLs 404ing.

**Comment by SamGreenwood1** [comment]
Still waiting for a response.

**Comment by kengher** [comment]
Can you try launching with `npm run dev` and see what debug message shows when trying to access short urls?

**Comment by SamGreenwood1** [comment]
This is what I get when I run the command in the Cloudron terminal: 

<img width="948" alt="image" src="https://user-images.githubusercontent.com/20076209/166820934-db856337-5b35-4210-b3ba-6658dac1815a.png">

**Comment by SamGreenwood1** [comment]
I think I figured out the problem, not realizing it's a placeholder I copied the IP from the example in the settings page (which isn't the server's IP it's your server's IP).

**Comment by SamGreenwood1** [comment]
Never mind it's totally on me, I just noticed that I mistyped the urls when I connected my domains to the server. Is there a way to bulk edit the list to change all the domains?

**Comment by hashlash** [comment]
@SamGreenwood1 You could programmatically use the API https://docs.kutt.it/

**Comment by SamGreenwood1** [comment]
Ended up being a server-side issue

**Comment by poeti8** [comment]
@SamGreenwood1 You mean is there an issue in the code?

**Comment by SamGreenwood1** [comment]
I meant an issue with the server I'm running it on. Works now.
