### ISSUE TITLE
abuse@kutt.it not working

### ISSUE THREAD

**Issue by bani6809** [thedevs-network/kutt#605]
abuse reports to abuse@kutt.it do not work. the mailbox appears to be broken.

<abuse@kutt.it>: host mx2.privateemail.com[198.54.122.250] said: 554 5.7.1
    <abuse@kutt.it>: Relay access denied (in reply to RCPT TO command)

**Comment by poeti8** [comment]
The email subscription hadn't been renewed for couple days, I fixed them at that time so I'm gonna close this since it's resolved.
