### ISSUE TITLE
Android App

### ISSUE THREAD

**Issue by abhijithvijayan** [thedevs-network/kutt#63]
Is developing an android app possible with the api?

**Comment by poeti8** [comment]
Yes, it's possible if you want to build it for yourself. Remember that there is a daily limit on the app.
If you want to create an Android app I recommend you to host your own version of Kutt and change the daily limit number.

**Comment by abhijithvijayan** [comment]
And I can provide it to the people right

**Comment by poeti8** [comment]
I don't know what are you trying to achieve, but I think so, yes.
