### ISSUE TITLE
CRASHED ON FIRST USE: A cross-origin error was thrown. React doesn't have access to the actual error object in development. 

### ISSUE THREAD

**Issue by iamtelo** [thedevs-network/kutt#64]
Trying to set up for first time use. But the page doesnt load on the ports, i editted my config file. I dont understand why its not working.

After taking all day to load the page, i eventually get the error below. All though for a brief second it shows the page before the error, and i cant figure this out.

![screenshot 1](https://user-images.githubusercontent.com/23028206/41533293-918137cc-72fa-11e8-8545-a4439e5c8223.png)

**Comment by poeti8** [comment]
Please fill everything you see in both config files and rename them config.js.

**Comment by iamtelo** [comment]
done all that and got it fixed, my problem now is the features dont work, cant sign up or shorten link, is that a problem with my database or something?

**Comment by poeti8** [comment]
Yep that should be a database problem. Open Neo4j Desktop app and create and start a database.

**Comment by iamtelo** [comment]
do i input the db_uri as bolt://localhost:2934 or as bolt://1934

**Comment by poeti8** [comment]
Enter it as `bolt://localhost` . If you have set a custom bolt port add the port as well: `bolt://localhost:<port>`.

See ports in details tab:
https://vgy.me/312YBc.png

**Comment by iamtelo** [comment]
okay done, but one last question, in the default domian section, do i input it as localhost:<port> or just localhost
