### ISSUE TITLE
Creates custom url even if already used by someone else

### ISSUE THREAD

**Issue by abhijithvijayan** [thedevs-network/kutt#65]
I created https://kutt.it/blog and it showed in the stats the url assigned to it

I browse to the shortened link and found someone else using that link.

**Comment by abhijithvijayan** [comment]
![bug](https://user-images.githubusercontent.com/34790378/41543010-b359b9c6-7333-11e8-94c9-9c6a757a5805.JPG)

**Comment by poeti8** [comment]
I tried to shorten it and it gave me the correct error, which is "the custom domain is already in use."
Can you provide more info? The steps you took?

**Comment by abhijithvijayan** [comment]
I just logged in and entered the site to shorten and entered the custom url.
I can remove the one I added if you want and let you give a try.

**Comment by poeti8** [comment]
Yep, was able to reproduce. I'll look into it.
