### ISSUE TITLE
Error deploying via Vercel: Error: The file "/vercel/path0/.next/routes-manifest.json" couldn't be found. 

### ISSUE THREAD

**Issue by DejavuMoe** [thedevs-network/kutt#658]
I use a remote Postgre SQL and Redis instance, I tested my configuration locally, and there is no problem in starting the development server. I want to try to deploy Kutt to Vercel, but Vercel reports the following error:

```
error: uncaughtException: ENOENT: no such file or directory, open '/vercel/path0/production-server/mail/template-reset.html'
```

<img width="1201" alt="image" src="https://user-images.githubusercontent.com/57177121/205212392-c1f8a99b-1b36-479c-afaa-1f80a83bb639.png">

It seems that Vercel can't recognize the routing of the next application. How can I solve it? (All related variables are imported through the vercel environment variable)
<img width="1039" alt="image" src="https://user-images.githubusercontent.com/57177121/205212587-0c80b814-2c01-44ca-bd23-2cc953db742c.png">

**Comment by poeti8** [comment]
That part is to load the email HTML template files from the projects directory and I use `__dirname` for that. It could be that it's pointing to the wrong spot. Do you have access to the directory to see what's inside the `production-server/mail` folder?

**Comment by DejavuMoe** [comment]
> That part is to load the email HTML template files from the projects directory and I use `__dirname` for that. It could be that it's pointing to the wrong spot. Do you have access to the directory to see what's inside the `production-server/mail` folder?

Yes, the whole deployment gets completely stuck when it reports this error, and doesn't automatically report an error to stop this, so I think Vercel shouldn't recognize `__dirname` and it can't access the `email` directory at all.

<img width="1260" alt="image" src="https://user-images.githubusercontent.com/57177121/205256046-c79a2892-1575-441d-9ed1-fe34f1fecf5c.png">
