### ISSUE TITLE
How to Manage other users short url

### ISSUE THREAD

**Issue by xianx** [thedevs-network/kutt#69]
Hello,

How to manage other users short url to maintain reported abuse link?

**Comment by trgwii** [comment]
An automatic tool for this doesn't exist yet, but we might add it in the future.

**Comment by poeti8** [comment]
I'll add a section for admin to be able to remove a link based on an id and ban a user based on email.

**Comment by poeti8** [comment]
This is done, we now have a admin form to ban links and their users and domain.

**Comment by mimalef70** [comment]
Hello,

I can't see any other links on the admin home page. 
I just see my own links on the admin account :)

please see the screenshot below: 
admin:
<img width="1341" alt="Screen Shot 2021-07-08 at 10 12 50 PM" src="https://user-images.githubusercontent.com/17767869/124967613-dc607a00-e039-11eb-9b54-9290d1bb5605.png">

normal user:
<img width="1328" alt="Screen Shot 2021-07-08 at 10 13 02 PM" src="https://user-images.githubusercontent.com/17767869/124967632-e2eef180-e039-11eb-9af3-e214761c040c.png">
