### ISSUE TITLE
Signup has been disabled temporarily

### ISSUE THREAD

**Issue by ILshopping** [thedevs-network/kutt#692]
When I try to sign up, this is the message I see:
`(Signup has been disabled temporarily.)`

Will signups be enabled anytime soon?
Thank you!

**Comment by JosephMcGreene** [comment]
I don't know any details on this, per se, but it's an issue I'd be happy to try to tackle if necessary, assuming eyes are still on this.

**Comment by kengher** [comment]
It was mentioned a while back by the devs that there were too many people abusing the system so it's disabled. You'll have to set this up on your own host.

**Comment by poeti8** [comment]
Please refer to https://github.com/thedevs-network/kutt/issues/534#issuecomment-977545278
