### ISSUE TITLE
Disable expired link deletions

### ISSUE THREAD

**Issue by prithvisharma** [thedevs-network/kutt#693]
Hello,
I noticed that the links are deleted if expired, is there a way to disable this setting?

**Comment by Prymeklickng** [comment]
There is no way to disable it except it pulled up from db.
Which I believe can added to their next update.

**Comment by Prymeklickng** [comment]
There is no way to disable it except it pulled up from db.
Which I believe can added to their next update.

**Comment by prithvisharma** [comment]
Do let me know once the update is out, thank you very much!
