### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'auth' of null

### ISSUE THREAD

**Issue by AleksandrKrokis** [thedevs-network/kutt#71]
When tried to click on image in the logo. 
I was getting this error `Uncaught (in promise) TypeError: Cannot read property 'auth' of null`

On your prod.

**Comment by andrewmedina** [comment]
I'm getting the same issue bruv

**Comment by trungquan17** [comment]
@AleksandrKrokis @andrewmedina 
You can edit a little code in: **/client/components/Header/HeaderLogo.js**
**Line 34:** use **e.currentTarget** instead **e.target**
Hope this help!
