### ISSUE TITLE
Simply DOES NOT WORK!

### ISSUE THREAD

**Issue by SaiPanneerselvam** [thedevs-network/kutt#716]
When I type a link, even GOOGLE.COM doesn't work. I type the link "google.com" in the text box, and hit send. It starts loading. It has NEVER stopped. Please help, as I am trying to look for a new open-source link shortener since git.io stop.

**Comment by shaik11r** [comment]
> When I type a link, even GOOGLE.COM doesn't work. I type the link "google.com" in the text box, and hit send. It starts loading. It has NEVER stopped. Please help, as I am trying to look for a new open-source link shortener since git.io stop.

yeah i took now tired to use it but its not even sending any network request

**Comment by SaiPanneerselvam** [comment]
I made a few other id's, which has #540 and #539

**Comment by SaiPanneerselvam** [comment]
@poeti8 referred this in another issue ([#534](https://github.com/thedevs-network/kutt/issues/534#issuecomment-977545278)), but that was in 2021. Is it true that this project is dead? (#546). 
I only found out about this "Kutt.it" project when I was looking at the SmartTube README, when I noticed that the download link was a kutt.it link (kutt.it/stn_stable).

**Comment by francisyzy** [comment]
The service works on my end. You need to have an account before the signups closed.

https://github.com/thedevs-network/kutt/assets/24467184/8a17c5f4-4ca0-440f-b69e-ace6fe2eaa12

**Comment by poeti8** [comment]
Guys, the service is only available for current users that already have an account. No new users can signup for now until I found a solution to prevent spamming and phishing links. Please refer to #534. I'll close the issue, but feel free to open a "discussion" if you have questions.
