### ISSUE TITLE
kutt.it down, its returning error code 522

### ISSUE THREAD

**Issue by thesyaf** [thedevs-network/kutt#730]
Hi, just reporting that kutt.it is returning error code 522. Not sure how long its been like this.

![image](https://github.com/thedevs-network/kutt/assets/23518574/a7c1699d-5f6a-4364-a618-588c56357ef8)

**Comment by dr5hn** [comment]
Yes! It's down since morning.

**Comment by vscodesyncsettings** [comment]
I see the same.

**Comment by vscodesyncsettings** [comment]
It's back online. This issue may be closed.

**Comment by sae13** [comment]
its offline now
