### ISSUE TITLE
Duplicates

### ISSUE THREAD

**Issue by abhijithvijayan** [thedevs-network/kutt#74]
Better if a url is checked for an existing shortened link before shortening to avoid duplicate links

https://kutt.it/6EkU2v

https://kutt.it/4U0AVW

both redirects to same page

**Comment by trgwii** [comment]
This exists now through the API's `reuse` parameter. The reason this is not the default option is that separate links created by separate people leading to the same location should display separate stats. Otherwise private stats would get leaked.
