### ISSUE TITLE
kutt login & short url seems down and not working

### ISSUE THREAD

**Issue by Reefaq** [thedevs-network/kutt#740]
Hi Kutt Team,

I am using Kutt for a long time and recently using it extensively. Since today morning I am facing following issue.
- Unable to login to kutt
- existing short url are not working

<img width="300" alt="Screenshot 2024-03-21 at 12 03 47 PM" src="https://github.com/thedevs-network/kutt/assets/660426/66fc783f-3744-49b1-916a-53601b3d9797"> <img width="300" alt="Screenshot 2024-03-21 at 12 05 10 PM" src="https://github.com/thedevs-network/kutt/assets/660426/9431a6f6-0b76-4c54-8e9e-a79bba64c637">

**Comment by Vucko130** [comment]
same here

**Comment by poeti8** [comment]
It should be fixed now, please check.

**Comment by Reefaq** [comment]
Working now. Thanks @poeti8

**Comment by ThreeDeeJay** [comment]
Seems down again 👀💦 
Is it working for anyone else right now?

**Comment by samiralibabic** [comment]
Nope, it's down.

**Comment by Vucko130** [comment]
> Nope, it's down.

Nope. Down.

**Comment by Vucko130** [comment]
Down for me too

**Comment by Reefaq** [comment]
It's down again.
