### ISSUE TITLE
Can't reach the domain and use kutt.it

### ISSUE THREAD

**Issue by WesleyKln** [thedevs-network/kutt#751]
Hello.

Since today, I can't reach the domain. There is a hosting error (error code 522). None of my shortened URL work :/
Could you check your hosting configuration to make kutt.it work again ?

Thx

**Comment by poeti8** [comment]
Sorry, didn't notice the hosting provider's payment is due. It's back up now.

**Comment by danimiku9** [comment]
Really really thank you for your service <3, this help me a lot.. i'm not a good developer, but if i can pay you a coffee tell me how

**Comment by poeti8** [comment]
@danimiku9 Hey, I'm happy to see it was a help. No need for anything, this warm comment was enough.

**Comment by WesleyKln** [comment]
> Sorry, didn't notice the hosting provider's payment is due. It's back up now.

Nice. Thank you a lot.

#Request : To avoid this kind of inconvenience, would it be possible for you to offer via a button, to download in json format for example a table with the different short and long links recorded?
This would allow in case the kutt.it service is inaccessible to always be able to retrieve the original link to access it.
Kind regards
