### ISSUE TITLE
[Bug] Stats not updating despite increase in total views

### ISSUE THREAD

**Issue by zhaolinlau** [thedevs-network/kutt#765]
Total views increased from around 341 to 777 on October 11, but the tracked visits in the stats didn't update.

![image](https://github.com/user-attachments/assets/cdbf04c0-0c6c-420d-8516-e53a6065d407)

**Comment by zhaolinlau** [comment]
It's quite urgent because we're using Kutt to track the number of visitors for our KPI goal, and we hope this issue can be fixed as soon as possible.

**Comment by zhaolinlau** [comment]
@poeti8

**Comment by poeti8** [comment]
@zhaolinlau Hey, sorry for the late reply, I was on vacation.
You just like any other user on Kutt are on the free plan, and currently the free plan has the limit of tracking the details for the first 100 views per link only. We don't have an official paid plan yet, but if you really need to bypass this limitation send me an email and I'll see what I can do for you.

**Comment by zhaolinlau** [comment]
@poeti8 my email is zhaolinlau@gmail.com

**Comment by poeti8** [comment]
@zhaolinlau I said you send me an email, not me sending you an email.

**Comment by zhaolinlau** [comment]
@poeti8 My bad, I have sent you an email.

![image](https://github.com/user-attachments/assets/258975ca-282e-422c-944e-7ecb40964270)
