### ISSUE TITLE
Custom domain homepage forwarding not working

### ISSUE THREAD

**Issue by DananFlander** [thedevs-network/kutt#770]
Forwarding for my custom domain seems to have broken sometime recently. Has worked for a long time before this, but now redirects direct to kutt.it instead of my Linktree page even though all my settings are still the same as they've ever been.

![image](https://github.com/user-attachments/assets/4519955a-7b52-4c4c-8005-11f0d9d3ae52)

![image](https://github.com/user-attachments/assets/185038df-b6da-46ff-a3b3-58655cd957a1)

**Comment by poeti8** [comment]
Fixed by https://github.com/thedevs-network/kutt/commit/1a5ddb23f33063299d576dde21d5ea7e2fd1f6cf. Thanks for reporting the issue.

**Comment by DananFlander** [comment]
Thanks!
