### ISSUE TITLE
Unable to generate shortened links using kutt.it or custom domain

### ISSUE THREAD

**Issue by DananFlander** [thedevs-network/kutt#771]
Shortened links weren't returning through ShareX, so I went to test generating links manually and am receiving this error for both default kutt.it shortening as well as for my custom domain.

![image](https://github.com/user-attachments/assets/304169f0-a223-4f9c-a0e5-e94139ddc0ad)

**Comment by poeti8** [comment]
Kutt is a free service. I've limited it to 10 links per month per user so I can manage the app and maintain the server. 

I'm planing on adding a donation or sponsors page so I could increase the limit with the help of donation. Paid subscription are out of question for now.

**Comment by DananFlander** [comment]
Ah, makes sense.
