### ISSUE TITLE
Cloudflare CF-IPCountry header support

### ISSUE THREAD

**Issue by AR2000AR** [thedevs-network/kutt#774]
Cloudflare used as a proxy can provide the client country in the `CF-IPCountry` request header. It would be nice if Kutt could use this header.
https://cloudflare.zendesk.com/hc/en-us/articles/200168236-Configuring-IP-geolocation

**Comment by poeti8** [comment]
I've been using it in production for kutt.it for several weeks now. I wasn't sure to add the code to GitHub since not everyone is going to use Cloudflare.

**Comment by AR2000AR** [comment]
the more option the better.

**Comment by poeti8** [comment]
Done by https://github.com/thedevs-network/kutt/commit/d7ad5062f7a6dfe4e85cfa5554b051fbd2f882bd
