### ISSUE TITLE
Ability to EDIT "Original URL"

### ISSUE THREAD

**Issue by pramitbiswas** [thedevs-network/kutt#79]
Say, `example1.com` is shortened to `https://kutt.it//abcd`.
Now by editing "Original URL" to `example2.com` can be shortened to same previous `https://kutt.it//abcd`.
This feature is available in [beam.to](http://beam.to)

**Comment by trgwii** [comment]
I don't think we want to allow changeable shortened links. This would probably remove some sense of security around our platform. Imagin a user gets hacked and all his links get changed to a malware site. Or someone checks the link before visiting for the first time (using +), and then gets tricked to a bad site afterwards.

@poeti8 thoughts?

**Comment by poeti8** [comment]
Exactly as @trgwii said. I won't implement this feature.

**Comment by aksh1618** [comment]
@trgwii and @poeti8 I feel like this wouldn't affect security that much, because presently I simply delete the short link, and recreate it with the new link. So if someone gets access to my account, they could still change the links, right? If there is no other reason to not have this feature, maybe reconsider this? (It's a chore currently to change links and all stats are lost)

**Comment by trgwii** [comment]
No, they couldn't change the links if they got access to your account. And why should stats remain the same for different URLs?

**Comment by aksh1618** [comment]
@trgwii If they have access to my account, can't they just delete the link and create a new one with the same custom URL? That's what I do to change links currently.

Regarding retaining stats, I could tell you two scenarios I have found myself in: 
- I created a temporary slack workspace, and generated an invite link that was valid for 30 days, and used kutt.it to get a short link. Then I decided to keep the workspace, so I created a permanent join link, and wanted to change the short link to point to the new URL, but to do it, I had to give up on the stats.
- I was organizing a 4 week event, and wanted a short link to point to the ongoing week's problem statement, but was forced to create separate links to preserve stats.

**Comment by poeti8** [comment]
This is a security concern for the user. Imagine a link is pointing to a safe website and then the link owner changes the original URL to an unsafe website, now users are redirected to an unsafe website.
What you can do is to use a custom URL for your link, then you can delete the link and shorten another URL with the same custom URL.

**Comment by aksh1618** [comment]
@poeti8 If I'm getting this right, you are saying there shouldn't be an option to change the long URL for random short URLs which are auto-generated when custom URL isn't specified. I agree that it wouldn't make any sense either.

But couldn't this feature be implemented for short links with Custom URLs only? It would make it convenient to edit links while preserving stats. And, if one doesn't want to preserve stats, they could use the delete-recreate method.

**Comment by poeti8** [comment]
Yes that one makes sense a bit. But still there are still more important features that need to be done, and this one is not a priority here.
For now I'm reopening the issue.

**Comment by trgwii** [comment]
I think we should change custom URLs so that they get a prefix or something, since this is a vulnerability. something like kutt.it/c/my-custom-url would be better, so users can differentiate between safe and unsafe URLs

**Comment by edmundlaugasson** [comment]
Just let you know that this was a huge disappointment that cannot change either original or shortened URL. If you really afraid about userspace security - why not allow 2-step authentication (2FA)? E.g. new random code via QR code pairing (e.g. FreeOTP+), confirmation code via e-mail, chat, SMS.
Also why not just allow edit original and short link but e.g. give a warning that for better security and allowing edit original, short link please allow 2FA - would be reasonable.

**Comment by trgwii** [comment]
To answer "Why not 2FA / Edit / etc", the answer is mostly "time-constraints".

**Comment by poeti8** [comment]
@edmundlaugasson I'll add this feature to the list of features that I need to add for the next major version.
