### ISSUE TITLE
Make the country pie chart more readable

### ISSUE THREAD

**Issue by mahdiyazdani** [thedevs-network/kutt#83]
Hello

Thanks for this great tool.
I would like to suggest an update regarding the pie charts and a way to make them more humanly readable.

![](https://i.gyazo.com/ba32be59387cf469c90ff6985ce9447b.png)

**Comment by poeti8** [comment]
Using a map was in my todos. Haven't got time for that yet.

**Comment by poeti8** [comment]
Replaced it with map chart!

<img width="584" alt="image" src="https://user-images.githubusercontent.com/23660003/75105690-b9434f00-562b-11ea-8727-c66cbd4d9988.png">

**Comment by francisyzy** [comment]
Hi, just checking if it is possible to have a list of countries as well? Some countries are too small to show up on the map like SG.
