### ISSUE TITLE
www results in 404

### ISSUE THREAD

**Issue by abhijithvijayan** [thedevs-network/kutt#84]
https://kutt.it/uyhXyr

https://www.kutt.it/uyhXyr   (404)

both directs to different links

**Comment by abhijithvijayan** [comment]
I think this issue can be solved by forwarding all requests from **www.kutt.it**  to just **kutt.it** within the nginx config.


also if you visit the www. site, it says invalid ssl.

**Comment by trgwii** [comment]
@poeti8 LE cert needs updating, should work with `-d kutt.it -d www.kutt.it`, that'll issue a single cert which is valid for both (then do the redirect in nginx config from www -> @)
