### ISSUE TITLE
Kutt is ot working after successful installation

### ISSUE THREAD

**Issue by git-pavan** [thedevs-network/kutt#91]
I have followed the installation instruction given here 
- https://github.com/thedevs-network/kutt/tree/develop/docker-examples

After final command step, I hit the URL in the browser. But it get stuck. 

I observed(in FireFox inspector Network Tab) that, 
- KUTT is rendering the page at server side and responding to browser too (Screenshot attached FireFox and Chromium).
![image](https://user-images.githubusercontent.com/3107960/43366205-81df105a-9357-11e8-8ffe-8ab273d0d2e1.png)
![image](https://user-images.githubusercontent.com/3107960/43366220-d4468364-9357-11e8-95ba-6be4f70d5994.png)

- analytics.js is not returning any response
- similarly other image files are also not responding

To resolve this - I tried to change the FILE PERMISSION in docker container (/code) folder to 777 .... even though it didn't worked.

Any help in order to make kutt runnable on local would be highly appreciable.
My local system - Ubuntu-16.04

**Comment by Theragus** [comment]
Got the same problem on Ubuntu 18.04. 
Analytics.js is not responding.
