### ISSUE TITLE
can not delete short links so sad :(

### ISSUE THREAD

**Issue by mojtabatmj** [thedevs-network/kutt#94]

**Comment by poeti8** [comment]
What? The feature is already there.

**Comment by mojtabatmj** [comment]
I know and this is the reason why I choose Kutt, but this huge future doesn't functional for the **Custom domain** when I try to delete a short link list of links will be fade.
error : main.js:formatted:11648 POST https://kutt.it/api/url/deleteurl 400
{error: "Couldn't find the short URL."}
error: "Couldn't find the short URL."

**Comment by GriffinMartin** [comment]
Has there been any movement on this front? About to host our own to mitigate this issue.

**Comment by GriffinMartin** [comment]
@mojiTMJ make sure your request body is as follows
```
{
  "domain": "customDomain",
  "id": "customDomainRoute"
}
```
