### ISSUE TITLE
Feature Request: go-links?

### ISSUE THREAD

**Issue by xinbenlv** [thedevs-network/kutt#95]
Hi thedevs-network@ team

This is a great repo. Awsome! I wonder, have you every considered integrate "golink" feature into this project. Go Links means you allow the creator to set arbitrary (meaningful) short url as opposed to randomly generated short url? (e.g. https://www.golinks.io/)

For example, see https://github.com/zgzgorg/open-golinks
I am developing [OpenGoLinks](https://github.com/zgzgorg/open-golinks) as a replacement for http://bit.ly. A friend pointed me to your project kutt. I wonder if I shall just add the feature directly to the kutt.

Victor

**Comment by xinbenlv** [comment]
Well, it's the custom URL feature. NVM 👍

**Comment by willwade** [comment]
I realise this is is closed but just wanted to raise a usability issue. The fact that Victor couldn’t find this immediately I think is down to the wording. Does “set custom url” mean “use your own domain name” or does it mean “use your own shotened url path”. What I’m saying is in trying to be brief I think “set custom url” loses the point on some people. The missing word is path.
