### ISSUE TITLE
Deployment Notes => Documentation

### ISSUE THREAD

**Issue by xinbenlv** [thedevs-network/kutt#96]
I realize there is no documentation for production deployment, I plan to try to deploy kutt for my community. I will document the process and hopefully it will help others.

## Deployment Example
@xinbenlv deployed an instance onto [Heroku](heroku.com) + [Heroku Add-on:GrapheneDB](graphenedb.com) 

1. According to the `Setup` section in the Readme.md
```
cp server/config.example.js server/config.js
cp client/config.example.js client/config.js
```

2. Fill in reCAPCHA [portal](https://www.google.com/recaptcha/admin#list)
Create an **Invisible** version of reCAPCHA. 
In the Keys on the reCAPCHA portal, `Keys` section, there are two subsections: `Site key` and `Server key`. Fill in the `RECAPTCHA_SITE_KEY`@`client/config.js` and `RECAPTCHA_SECRET_KEY`@`server/config.js` with `Site key` and `Server key` respectively

3. Go to Google Analytics, Create a new project, new site and new property, copy the `Tracking Id` into `GOOGLE_ANALYTICS_ID`

4. Create an heroku project with project name `<project>`

5. For Database, add an Heroku Add-On with `GrapheneDB`
In the heroku project setting `https://dashboard.heroku.com/apps/<project>/settings`, click on button `Reveal Config Vars` and then copy `GRAPHENEDB_BOLT_URL`, `GRAPHENEDB_BOLT_USER` and `GRAPHENEDB_BOLT_PASSWORD` 's values into `server/config.js`'s `DB_URI`, `DB_USERNAME`, and `DB_PASSWORD` respectively

5. Update `server/config.js`'s `DEFAULT_DOMAIN` to your new url, e.g. `<project>.herokuapp.com` or your custom domain.

6. Update `server/config.js`'s `GOOGLE_SAFE_BROWSING_KEY` from `console.cloud.google.com`, create a new project with enabled `Safe Browsing API` and an API key credentials.

6. Update `server/config.js`'s mail information

```
  /*
    Your email host details to use to send verification emails.
    More info on http://nodemailer.com/
  */
  MAIL_HOST: 'smtp.gmail.com',
  MAIL_PORT: 465,
  MAIL_SECURE: true,
  MAIL_USER: '<your email>',
  MAIL_PASSWORD: '<your email password, or if 2-step auth, use App-Specific Passwords>',

```

For a workable configuration, see https://github.com/xinbenlv/kutt/tree/deploy-heroku

**Comment by poeti8** [comment]
That would be useful. Thanks.
